functionality:
  name: "rna_multisample"
  namespace: "multiomics"
  description: "Processing unimodal multi-sample RNA transcriptomics data."
  authors:
    - name: Dries De Maeyer
      email: ddemaeyer@gmail.com
      roles: [ author ]
      props: { account: ddemaey1 }
    - name: Robrecht Cannoodt
      email: robrecht@data-intuitive.com
      roles: [ author, maintainer ]
      props: { github: rcannood, orcid: "0000-0003-3641-729X" }
    - name: Dries Schaumont
      email: dries@data-intuitive.com
      roles: [ author ]
      props: { github: DriesSchaumont, orcid: "0000-0002-4389-0440" }
  arguments:
    - name: "--id"
      required: true
      type: string
      description: ID of the concatenated file
      example: concatenated
    - name: "--sample_id"
      required: true
      type: string
      multiple_sep: ';'
      multiple: true
      description: IDs of the sample.
      example: foo
    - name: "--input"
      required: true
      type: file
      multiple_sep: ';'
      multiple: true
      description: Path to the samples.
      example: dataset.h5mu
  resources:
    - type: nextflow_script
      path: main.nf
  test_resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: test_wf