functionality:
  name: cross_check_genes
  namespace: "scgpt"
  description: |
    Cross-check genes with pre-trained scGPT model.
  authors:
    - __merge__: /src/authors/jakub_majercik.yaml
      roles: [ maintainer, author ]
    - __merge__: /src/authors/dorien_roosen.yaml
      roles: [ maintainer, author ]

  argument_groups:
    - name: Inputs
      arguments:
        - name: "--input"
          type: file
          direction: input
          required: true
          example: input.h5mu
          description: |
            The input h5mu file containing of pre-processed data.
        - name: "--modality"
          type: string
          default: "rna"
          required: false
          description: |
            The modality key of the MuData object containing the RNA AnnData object.
        - name: "--vocab_file"
          type: file
          direction: input
          required: true
          example: resources_test/scgpt/vocab.json
          description: |
            Model vocabulary file path.
        - name: "--var_gene_names"
          type: string
          example: "gene_name"
          required: false
          description: |
            The name of the adata.var column containing gene names. By default the .var index will be used.
    - name: Outputs
      arguments:
        - name: "--output"
          type: file
          direction: output
          required: true
          example: output.h5mu
          description: |
            The output cross-checked anndata file.
        - name: "--output_compression"
          type: string
          choices: ["gzip", "lzf"]
          required: false
          example: "gzip"
    - name: Arguments
      arguments:
        - name: "--pad_token"
          type: string
          default: "<pad>"
          required: false
          description: |
            The padding token used in the model.
  resources:
    - type: python_script
      path: script.py
    - path: /src/utils/setup_logger.py
  test_resources:
    - type: python_script
      path: test.py
    - path: /resources_test/scgpt/test_resources/Kim2020_Lung_subset.h5mu
    - path: /resources_test/scgpt/source/vocab.json

platforms:
  - type: docker
    image: nvcr.io/nvidia/pytorch:23.09-py3
    setup:
      - type: python
        __merge__: [ /src/base/requirements/anndata_mudata.yaml, /src/base/requirements/scanpy.yaml, .]
      - type: python
        packages:
          - scgpt==0.2.1
    test_setup:
      - type: python
    __merge__: [ /src/base/requirements/python_test_setup.yaml, .]
  - type: nextflow
    directives:
      label: [ lowmem, lowcpu ]
