functionality:
  name: add_metadata
  namespace: "integrate"
  description: "Add a csv containing metadata to the .obs or .var field of a mudata file."
  authors:
    - name: Dries Schaumont
      email: dries@data-intuitive.com
      roles: [ author ]
      props: { account: DriesSchaumont, orcid: "0000-0002-4389-0440" }
  arguments:
    - name: "--input"
      alternatives: ["-i"]
      type: file
      description: Input h5mu file
      direction: input
      required: true
    - name: "--output"
      alternatives: ["-o"]
      type: file
      description: Output h5mu file.
      direction: output
      required: true
    - name: "--modality"
      type: string
      multiple: true
      default: "rna"
      required: false
    - name: "--csv"
      type: file
      required: false
      direction: input
      description: .csv file containing metadata"
    - name: "--matrix"
      type: string
      description: Matrix to set new metadata for (.obs or .var)
      choices: ["obs", "var"]
      required: True
    - name: "--csv_sample_column"
      type: string
      required: false
      default: "id"
      description: "column of the the csv that corresponds to the sample id."
    - name: "--sample_id"
      type: string
      required: false
      description: "Set the sample id to a fixed value. "
    - name: "--matrix_sample_column"
      description: "Obs or var column (depending on --matrix) name where the sample id can 
                    be found for each observation to join on. Usefull when adding metadata
                    to concatenated samples. Mutually exclusive with --sample_id"
      type: string
      required: false

  resources:
    - type:  python_script
      path: script.py

  test_resources:
    - type: python_script
      path: test.py
platforms:
  - type: docker
    image: python:3.10
    python:
      packages:
        - mudata~=0.2.0
        - anndata~=0.8.0
  - type: nextflow
    variant: vdsl3
