# Inputs
input: # please fill in - example: "input.h5mu"
modality: "rna"
model: # please fill in - example: "best_model.pt"
model_vocab: # please fill in - example: "vocab.json"
model_config: # please fill in - example: "args.json"
input_obsm_gene_tokens: "gene_id_tokens"
input_obsm_tokenized_values: "values_tokenized"
input_obsm_padding_mask: "padding_mask"
# input_var_gene_names: "foo"
# input_obs_batch_label: "foo"

# Outputs
# output: "$id.$key.output.h5mu"
# output_compression: "gzip"
embedding_layer_key: "X_scGPT"

# Arguments
pad_token: "<pad>"
pad_value: -2
dropout: 0.2
DSBN: true
batch_size: 64

# Nextflow input-output arguments
publish_dir: # please fill in - example: "output/"
# param_list: "my_params.yaml"
