functionality:
  name: "bd_rhapsody_wta"
  namespace: "ingestion"
  description: "A pipeline for processing BD Rhapsody WTA data."
  authors:
    - name: Robrecht Cannoodt
      email: rcannood@gmail.com
      roles: [ author, maintainer ]
      props: { github: rcannood, orcid: "0000-0003-3641-729X" }
  inputs:
    - name: "--input"
      required: true
      description: One or more fastq paths, separated with semicolons.
      example: file.fastq
      multiple: true
      multiple_sep: ";"
    - name: "--reference_genome"
      required: true
      description: A path to STAR index as a tar.gz file.
      example: reference.tar.gz
    - name: "--transcriptome_annotation"
      required: true
      description: A path to GTF annotation file.
      example: transcriptome.gtf
    - name: "--abseq_reference"
      description: Path to the AbSeq reference file in FASTA format. Only needed if BD AbSeq Ab-Oligos are used.
      multiple: true
      multiple_sep: ':'
    - name: "--supplemental_reference"
      description: Path to the supplemental reference file in FASTA format. Only needed if there are additional transgene sequences used in the experiment.
      multiple: true
      multiple_sep: ':'
  arguments:
    - name: "--id"
      required: true
      type: string
      description: ID of the sample.
      example: foo
  argument_groups:
    - name: Inputs
      description: Description of inputs
      arguments: [id, input, reference_genome, transcriptome_annotation, abseq_reference, supplemental_reference]
    # - name: Output
    #   arguments: [output]
  resources:
    - type: nextflow_script
      path: main.nf
  test_resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: test_wf