functionality:
  name: "mkgtf"
  namespace: "reference"
  version: "integration_build"
  authors:
  - name: "Jakub Majercik"
    roles:
    - "author"
    info:
      role: "Contributor"
      links:
        email: "jakub@data-intuitive.com"
        github: "jakubmajercik"
        linkedin: "jakubmajercik"
      organizations:
      - name: "Data Intuitive"
        href: "https://www.data-intuitive.com"
        role: "Bioinformatics Engineer"
  arguments:
  - type: "file"
    name: "--input_gtf"
    description: "Reference GTF annotation."
    info: null
    example:
    - "transcriptome_annotation.gtf.gz"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output_gtf"
    description: "Output GTF file."
    info: null
    example:
    - "output.gtf.gz"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--attribute"
    description: "Key-value pair in attributes field to be kept in the GTF file of\
      \ the format attribute:attribute_value."
    info: null
    example:
    - "gene_type:transcribed_unprocessed_pseudogene"
    - "gene_type:miRNA"
    required: true
    direction: "input"
    multiple: true
    multiple_sep: ";"
    dest: "par"
  resources:
  - type: "bash_script"
    path: "script.sh"
    is_executable: true
  - type: "file"
    path: "./src/workflows/utils/labels.config"
    dest: "nextflow_labels.config"
  description: "Make a GTF file - filter by a specific attribute."
  test_resources:
  - type: "python_script"
    path: "test.py"
    is_executable: true
  - type: "file"
    path: "resources_test/reference_gencodev41_chr1"
  - type: "file"
    path: "src/base/openpipelinetestutils"
    dest: "openpipelinetestutils"
  info: null
  status: "enabled"
  requirements:
    commands:
    - "ps"
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "ghcr.io/data-intuitive/cellranger:8.0"
  target_organization: "openpipelines-bio"
  target_registry: "ghcr.io"
  target_tag: "integration_build"
  namespace_separator: "/"
  resolve_volume: "Automatic"
  chown: true
  setup_strategy: "ifneedbepullelsecachedbuild"
  target_image_source: "https://github.com/openpipelines-bio/openpipeline"
  setup:
  - type: "docker"
    run:
    - "DEBIAN_FRONTEND=noninteractive apt update && \\\napt upgrade -y && apt install\
      \ -y pigz procps && rm -rf /var/lib/apt/lists/*\n"
  test_setup:
  - type: "docker"
    copy:
    - "openpipelinetestutils /opt/openpipelinetestutils"
  - type: "python"
    user: false
    packages:
    - "/opt/openpipelinetestutils"
    upgrade: true
  - type: "python"
    user: false
    packages:
    - "viashpy==0.6.0"
    upgrade: true
  entrypoint: []
  cmd: null
- type: "nextflow"
  id: "nextflow"
  directives:
    label:
    - "midmem"
    - "lowcpu"
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      mem1gb: "memory = 1.GB"
      mem2gb: "memory = 2.GB"
      mem4gb: "memory = 4.GB"
      mem8gb: "memory = 8.GB"
      mem16gb: "memory = 16.GB"
      mem32gb: "memory = 32.GB"
      mem64gb: "memory = 64.GB"
      mem128gb: "memory = 128.GB"
      mem256gb: "memory = 256.GB"
      mem512gb: "memory = 512.GB"
      mem1tb: "memory = 1.TB"
      mem2tb: "memory = 2.TB"
      mem4tb: "memory = 4.TB"
      mem8tb: "memory = 8.TB"
      mem16tb: "memory = 16.TB"
      mem32tb: "memory = 32.TB"
      mem64tb: "memory = 64.TB"
      mem128tb: "memory = 128.TB"
      mem256tb: "memory = 256.TB"
      mem512tb: "memory = 512.TB"
      cpu1: "cpus = 1"
      cpu2: "cpus = 2"
      cpu5: "cpus = 5"
      cpu10: "cpus = 10"
      cpu20: "cpus = 20"
      cpu50: "cpus = 50"
      cpu100: "cpus = 100"
      cpu200: "cpus = 200"
      cpu500: "cpus = 500"
      cpu1000: "cpus = 1000"
    script:
    - "includeConfig(\"nextflow_labels.config\")"
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/openpipeline/openpipeline/src/reference/cellranger_mkgtf/config.vsh.yaml"
  platform: "docker"
  output: "/home/runner/work/openpipeline/openpipeline/target/docker/reference/mkgtf"
  executable: "/home/runner/work/openpipeline/openpipeline/target/docker/reference/mkgtf/mkgtf"
  viash_version: "0.8.6"
  git_commit: "b7c90e8165c03654bc13de4288aa67b7084f56e5"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
