name: "scgpt_integration_knn_test"
namespace: "test_workflows/annotation"
description: "This component test the output of the integration test of the scgpt_annotation workflow."
authors:
  - __merge__: /src/authors/dorien_roosen.yaml
argument_groups:
  - name: Inputs
    arguments:
      - name: "--input"
        type: file
        required: true
        description: Path to h5mu output.
        example: foo.final.h5mu
      - name: "--orig_input"
        type: file
        required: true
        description: Path to the original input file.
        example: input.h5mu
      - name: "--n_hvg"
        type: integer
        required: true
        description: Number of HVG that the input file was subset for
        example: 500
        
resources:
  - type: python_script
    path: script.py
engines:
  - type: docker
    image: python:3.12-slim
    __merge__: /src/base/requirements/testworkflows_setup.yaml
runners:
  - type: executable
  - type: nextflow
    directives:
      label: ["midmem"]