functionality:
  name: celltypist
  namespace: "annotate"
  description: ""
  authors:
    - __merge__: /src/authors/jakub_majercik.yaml
      roles: [ author ]

  argument_groups:
    - name: Inputs
      description: Arguments related to the input (aka query) dataset.
      arguments:
        - name: "--input"
          alternatives: [-i]
          type: file
          description: Input h5mu file.
          direction: input
          required: true
          example: input.h5mu
        - name: "--modality"
          description: Which modality to process.
          type: string
          default: "rna"
          required: false
        - name: "--input_layer"
          type: string
          description: Which layer to use. If no value is provided, the counts are assumed to be in the `.X` slot. Otherwise, count data is expected to be in `.layers[input_layer]`.
          required: false
        - name: "--input_obs_batch"
          type: string
          description: Key in obs field of input adata for batch information. If no value is provided, batch label is assumed to be unknown.
          required: false
        - name: "--input_var_subset"
          type: string
          description: Subset the input object with this column.
          required: false
        - name: "--input_obs_label"
          type: string
          description: Key in obs field of input adata for label information. This is only used for training scANVI. Unlabelled cells should be set to `"unknown_celltype_label"`.
          required: false
    - name: Reference
      description: Arguments related to the reference dataset.
      arguments:
        - name: "--reference"
          type: file
          description: "User-provided reference tissue. The data that will be used as reference to call cell types."
          example: TS_Bladder_filtered.h5ad
          direction: input
          required: false
        - name: "--reference_layer"
          type: string
          description: Which layer to use. If no value is provided, the counts are assumed to be in the `.X` slot. Otherwise, count data is expected to be in `.layers[reference_layer]`.
          required: false
        - name: "--reference_obs_label"
          type: string
          description: Key in obs field of reference AnnData with cell-type information.
          default: "cell_ontology_class"
          required: false
        - name: "--reference_obs_batch"
          type: string
          description: Key in obs field of input adata for batch information.
          default: "donor_assay"
          required: false
    - name: Outputs
      description: Output arguments.
      arguments:
        - name: "--output"
          type: file
          description: Output h5mu file.
          direction: output
          required: true
          example: output.h5mu
        - name: "--output_compression"
          type: string
          choices: ["gzip", "lzf"]
          required: false
          example: "gzip"
    - name: Model arguments
      description: Model arguments.
      arguments:
        - name: "--model"
          type: file
          description: "Pretrained model. Can be a directory or a tar gz."
          required: false
          example: pretrained_model.pkl
        - name: "--model_save_path"
          type: file
          description: "Path to save the trained model."
          required: false
          example: trained_model.pkl
        - name: "--feature_selection"
          type: boolean
          description: "Whether to perform feature selection."
          default: true
        - name: "--majority_voting"
          type: boolean
          default: True

  resources:
    - type: python_script
      path: script.py
    - path: /src/utils/setup_logger.py
    
  test_resources:
    - type: python_script
      path: test.py
    - path: /resources_test/annotation_test_data/
    - path: /resources_test/pbmc_1k_protein_v3/

platforms:
  - type: docker
    image: python:3.10-slim
    setup:
      - type: apt
        packages:
          - libhdf5-dev
          - procps
      # - type: docker
      #   run: pip install git+https://github.com/Teichlab/celltypist.git
      - type: python
        __merge__: [ /src/base/requirements/scanpy.yaml, .]
      - type: python
        packages:
          - celltypist==1.6.3
      - type: python
        __merge__: [ /src/base/requirements/anndata_mudata.yaml, .]
    __merge__: [ /src/base/requirements/python_test_setup.yaml, .]
  - type: nextflow