functionality:
  name: knn
  namespace: "labels_transfer"
  description: "Performs label transfer from reference to query using KNN classifier"
  info:
    method_id: KNN_pynndescent
  authors:
    - __merge__: /src/authors/vladimir_shitov.yaml
      roles: [ author ]
  __merge__: ../api/common_arguments.yaml
  argument_groups:
    - name: "Learning parameters"
      arguments:
        - name: "--n_neighbors"
          alternatives: ["-k"]
          type: integer
          description: "Number of nearest neighbors to use for classification"
          required: true
  resources:
    - type: python_script
      path: script.py
    - path: ../utils/helper.py
    - path: ../../utils/setup_logger.py
  test_resources:
    - type: python_script
      path: test.py
    - path: /resources_test/annotation_test_data/
    - path: /resources_test/pbmc_1k_protein_v3/
platforms:
  - type: docker
    image: python:3.10-slim
    setup:
      - type: apt
        packages: 
          - procps
          - git
      - type: python
        __merge__: [/src/base/requirements/anndata_mudata.yaml, .]
      - type: apt
        packages:
          - libopenblas-dev
          - liblapack-dev
          - gfortran
      - type: python
        __merge__: [/src/base/requirements/scanpy.yaml, .]
        packages:
          - pynndescent~=0.5.8
          - numba~=0.56.4
          - numpy~=1.23.5
    test_setup:
      - type: python
        __merge__: [ /src/base/requirements/viashpy.yaml, .]
  - type: nextflow
    directives:
      label: [highmem, highcpu]
  - type: native
