functionality:
  name: knn
  namespace: "labels_transfer"
  version: "dev"
  description: "Performs label transfer from reference to query using KNN classifier"
  authors:
    - __merge__: /src/authors/vladimir_shitov.yaml
      roles: [ author ]
  argument_groups:
    - name: Inputs
      arguments:
        - name: "--input"
          alternatives: ["-i"]
          direction: input
          required: true
          __merge__: ../api/file_input.yaml
        - name: "--modality"
          type: string
          default: "rna"
          required: false
        - name: "--reference"
          required: false
          __merge__: ../api/file_reference.yaml
        - name: "--targets"
          type: string
          default: [ ann_level_1, ann_level_2, ann_level_3, ann_level_4, ann_level_5, ann_finest_level ]
          required: false
          multiple: true
          multiple_sep: ","
        - name: "--reference_obsm_key"
          type: string
          required: false
          description: ".obsm key of the data to use as the feature space for training classifier. If None, X is used. It is recommended to use low-dimensional representation (e.g., PCA or scvi embedding)"
        - name: "--query_obsm_key"
          type: string
          required: false
          description: ".obsm key of the data to use as the feature space for inference of the model. If None, X is used. It is recommended to use low-dimensional representation (e.g., PCA or scvi embedding)"
    - name: Outputs
      arguments:
        - name: "--output"
          alternatives: ["-o"]
          direction: output
          required: true
          __merge__: ../api/file_output.yaml
        - name: "--output_obs_suffix"
          type: string
          default: "_pred"
          required: false
          description: "Suffix to add to each target name in .obs slot to store the predicted classes. For example, if `targets` is `cell_type`, predicted target in query will be `cell_type_pred`"
        - name: "--output_uns_key"
          type: string
          default: "labels_transfer"
          required: false
          description: "Key to store the information about the parameters in .uns slot"
    - name: "Learning parameters"
      arguments:
        - name: "--n_neighbors"
          alternatives: ["-k"]
          type: integer
          description: "Number of nearest neighbors to use for classification"
          required: true
  resources:
    - type: python_script
      path: script.py
  test_resources:
    - type: python_script
      path: test.py
    - path: ../../../resources_test/pbmc_1k_protein_v3/pbmc_1k_protein_v3_mms.h5mu
platforms:
  - type: docker
    image: python:3.8
    setup:
      - type: apt
        packages:
          - libopenblas-dev
          - liblapack-dev
          - gfortran
      - type: python
        packages:
          - mudata~=0.2.0
          - pynndescent~=0.1.1
          - numba~=0.56.4
          - numpy~=1.23.5
          - scanpy~=1.9.1
  - type: nextflow
    directives:
      label: [highmem, highcpu]
  - type: native
