
functionality:
  name: annotation
  namespace: "scgpt"
  description: |
    Annotate adata with cell types through the scGPT model.
  authors:
    - __merge__: /src/authors/dorien_roosen.yaml
      roles: [ maintainer, author ]
    - __merge__: /src/authors/jakub_majercik.yaml
      roles: [ maintainer, author ]

  argument_groups:
    - name: Inputs
      arguments:
        - name: "--input"
          type: file
          direction: input
          required: true
          example: resources_test/scgpt/test_resources/Kim2020_Lung_preprocessed.h5mu
          description: |
            The input h5mu file containing of pre-processed data.
        - name: "--modality"
          type: string
          default: "rna"
          required: false
        - name: "--model_vocab"
          type: file
          required: true
          example: resources_test/scgpt/vocab.json
          description: |
            Model vocabulary file directory.
        - name: "--input_gene_ids"
          type: file
          required: true
          example: resources_test/scgpt/test_resources/Kim2020_Lung_gene_ids.pt
          description: |
            The input gene ids file.
        - name: "--input_values"
          type: file
          required: true
          example: resources_test/scgpt/test_resources/Kim2020_Lung_values.pt
          description: |
            The input values file.
        - name: "--input_padding_mask"
          type: file
          required: true
          example: resources_test/scgpt/test_resources/Kim2020_Lung_padding_mask.pt
          description: |
            The input padding mask file.
        - name: "--model"
          type: file
          required: true
          example: "resources_test/scgpt/source/best_model.pt"
          description: |
            The model file.
        - name: "--model_config"
          type: file
          required: true
          example: "resources_test/scgpt/source/args.json"
          description: |
            The model configuration file. 

    - name: Outputs
      arguments:
        - name: "--output"
          type: file
          direction: output
          required: true
          example: Kim2020_Lung_cell_type_annotation.h5mu
          description: |
            The output cross-checked anndata file.
        - name: "--output_compression"
          type: string
          example: "gzip"
          required: false
          default: None
          description: |
            The compression algorithm to use for the output h5mu file.

    - name: Arguments
      arguments:
        - name: "--gene_name_layer"
          type: string
          default: "gene_name"
          required: false
          description: |
            The name of adata.var column containing the gene names.
        - name: "--batch_id_layer"  
          type: string
          default: "batch_id"
          description: |
            The name of the adata.obs column to write categorical batch ids to.
        - name: "--predicted_cell_type_layer"
          type: string
          default: "predicted_cell_type"
          description: |
            The name of the adata.obs column to write predicted cell types to.
        - name: "--pad_token"
          type: string
          default: "<pad>"
          required: false
          description: |
            The padding token used in the model.
        - name: "--mask_ratio"
          type: integer
          default: 0
          required: false
          description: |
            The ratio of the input to mask.
        - name: "--mask_value"
          type: integer
          default: -1
          required: false
          description: |
            The value of the mask.
        - name: "--pad_value"
          type: integer
          default: -2
          required: false
          description: |
            The value of the padding.
        - name: "--n_cls"
          type: integer
          default: 8
          required: false
          description: |
            The number of classes.
        - name: "--n_input_bins"
          type: integer
          default: 51
          required: false
          description: |
            The number of input bins.
        - name: "--batch_size"
          type: integer
          default: 64
          required: false
          description: |
            The batch size. 
        
  resources:
    - type: python_script
      path: script.py
    - path: /src/utils/setup_logger.py
  test_resources:
    - type: python_script
      path: test.py
    - path: /resources_test/scgpt/test_resources/Kim2020_Lung.h5mu
    - path: /resources_test/scgpt/test_resources/Kim2020_Lung_preprocessed.h5mu
    - path: /resources_test/scgpt/test_resources/Kim2020_Lung_gene_ids.pt
    - path: /resources_test/scgpt/test_resources/Kim2020_Lung_values.pt
    - path: /resources_test/scgpt/test_resources/Kim2020_Lung_padding_mask.pt
    - path: /resources_test/scgpt/source/best_model.pt
    - path: /resources_test/scgpt/source/args.json
    - path: /resources_test/scgpt/source/vocab.json

platforms:
  - type: docker
    image: nvcr.io/nvidia/pytorch:23.09-py3
    setup:
      - type: python
        __merge__: /src/base/requirements/anndata_mudata.yaml
      - type: docker
        run:
          echo "build --jobs 4" >> /etc/bazel.bazelrc
      - type: python
        packages:
          - scgpt==0.2.1
    test_setup:
      - type: python
    __merge__: [ /src/base/requirements/python_test_setup.yaml, .]
  - type: nextflow
