functionality:
  name: cross_check_genes
  namespace: labels_transfer
  description: 
  authors:
    - __merge__: /src/authors/jakub_majercik.yaml
      roles: [ author ]

  argument_groups:
    - name: Inputs
      description: Arguments related to the input (aka query) dataset.
      arguments:
        - name: "--input"
          type: file
          description: Input (query) h5mu file.
          direction: input
          required: true
          example: input.h5mu
        - name: "--modality"
          description: Which modality to process.
          type: string
          default: "rna"
          required: false
        - name: "--var_query_gene_names"
          type: string
          required: false
          description: |
            The name of the adata var column in the input data containing gene names; when no gene_name_layer is provided, the var index will be used.

    - name: Reference
      description: Arguments related to the reference dataset.
      arguments:
        - name: "--reference"
          type: file
          description: Reference h5mu file.
          direction: input
          required: true
          example: reference.h5mu
        - name: "--var_reference_gene_names"
          type: string
          required: false
          description: |
            The name of the adata var column in the reference data containing gene names; when no gene_name_layer is provided, the var index will be used.

    - name: Outputs
      description: Output arguments.
      arguments:
        - name: "--output_query"
          type: file
          description: Output h5mu file.
          direction: output
          example: output.h5mu
        - name: "--output_reference"
          type: file
          description: Output h5mu file.
          direction: output
          example: output.h5mu
        - name: "--output_compression"
          type: string
          choices: ["gzip", "lzf"]
          required: false
          example: "gzip"

  resources:
    - type: python_script
      path: script.py
    - path: /src/utils/setup_logger.py

  test_resources:
    - type: python_script
      path: test.py
    - path: /resources_test/annotation_test_data/
    - path: /resources_test/pbmc_1k_protein_v3/

platforms:
  - type: docker
    image: python:3.10-slim
    setup:
      - type: apt
        packages:
          - libhdf5-dev
          - procps
      - type: python
        __merge__: [ /src/base/requirements/anndata_mudata.yaml, .]
    __merge__: [ /src/base/requirements/python_test_setup.yaml, .]
  - type: nextflow