functionality:
  name: score_genes_scanpy
  namespace: feature_annotation
  description: |
    Calculates the score of a set of genes for each cell, as implemented by scanpy. 
    The score is the average expression of a set of genes subtracted with the average expression of a reference set of genes.
  argument_groups:

    - name: Inputs
      arguments:
        - name: --input
          type: file
          description: Input h5mu file
          required: true
          example: input_file.h5mu
        - name: --gene_list
          type: file
          description: |
            Path to a .txt file containing the gene list to be scored.
            The gene list file should be formatted as a single column with gene symbols.
          required: true
          example: gene_list.txt
        - name: --gene_pool
          type: file
          description: |
            File with genes for sampling the reference set. Default is all genes.
            The gene pool file should be formatted as a single column with gene symbols.
          required: false
          example: gene_pool.txt

    - name: Outputs
      arguments:
        - name: --output
          type: file
          direction: output
          description: |
            Output h5mu file
          required: true
          example: output_file.h5mu

    - name: Arguments
      arguments:
        - name: --ctrl_size
          type: integer
          default: 50
          required: false
          description: |
            Number of reference genes to be sampled from each bin. 
            If len(gene_list) is not too low, you can set ctrl_size=len(gene_list).
        - name: --n_bins
          type: integer
          default: 25
          required: false
          description: |
            Number of expression level bins for sampling.
        - name: --score_name
          type: string
          default: score
          required: false
          description: |
            Name of the score field to be added in .obs.
        - name: --random_state
          type: integer
          description: |
            The random seed for sampling.
          default: 0
          required: false
        - name: --use_raw
          type: boolean
          description: |
            Whether to use raw attribute of adata. Defaults to True if .raw is present.
          required: false

  resources:
    - path: script.py
      type: python_script

  test_resources:
    - type: python_script
      path: test.py
    - path: /resources_test/merge_test_data/

platforms:
  - type: docker
    image: python:3.11
    setup:
      - type: python
        __merge__: [ /src/base/requirements/scanpy.yaml, /src/base/requirements/anndata_mudata.yaml ]
