repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.8.1
  hooks:
    - id: ruff
    - id: ruff-format
- repo: https://github.com/lorenzwalthert/precommit
  rev: v0.4.3
  hooks:
    - id: style-files
    - id: lintr
