functionality:
  name: cellxgene_census
  namespace: "query"
  description: "Query CellxGene Census or user-specified TileDBSoma object, and eventually fetch cell and gene metadata or/and expression counts."
  authors:
    - __merge__: ../../authors/matthias_beyens.yaml
      roles: [ author ]
  argument_groups:
    - name: Inputs
      description: "Arguments related to the input (aka query) dataset."
      arguments:
        # TODO: add user-provided release of census, e.g. TileDBSoma
        - name: "--input_database"
          type: string
          description: "Full input database S3 prefix URL. Default: CellxGene Census"
          required: false
          example: "s3://"
          default: "CellxGene"
        - name: "--modality"
          description: "Which modality to store the output in."
          type: string
          default: "rna"
          required: false
        - name: "--cellxgene_release"
          description: "CellxGene Census release date. More information: https://chanzuckerberg.github.io/cellxgene-census/cellxgene_census_docsite_data_release_info.html"
          type: string
          default: "2023-05-15"
          required: false
    - name: Query
      description: Arguments related to the query.
      arguments:
        - name: "--species"
          type: string
          description: "Specie(s) of interest. If not specified, Homo Sapiens will be queried."
          required: false
          example: "homo_sapiens"
          default: "homo_sapiens"
          choices: ["homo_sapiens", "mus_musculus"]
          multiple: false
        - name: "--cell_type"
          type: string
          description: "Cell type(s) of interest. Cell type should be one of the Cell Ontology terms. If not specified, all cell types will be queried."
          required: false
          example: ["mesothelial fibroblast"]
          multiple: true
        - name: "--tissue"
          type: string
          description: "Tissue(s) of interest. If not specified, all tissues will be queried."
          required: false
          example: ["lung"]
          multiple: true
        - name: "--technology"
          type: string
          description: "Technology(ies) of interest. If not specified, all technologies will be queried."
          required: false
          example: ["10x 3' v3"]
          # TODO: add all possible technologies
          choices: ["10x 3' v1", "10x 3' v2", "10x 3' v3", "10x 5' v1", "10x 5' v2"]
          multiple: true
        - name: "--suspension"
          type: string
          description: "Suspension(s) of interest. If not specified, all suspensions will be queried."
          required: false
          example: ["cell"]
          # TODO: add all possible suspensions
          choices: ["cell", "nucleus"]
          multiple: true
        - name: "--is_primary_data"
          type: boolean
          default: True
          description: "Allow only primary data in the query in order to prevent of data duplication."
          required: false
        - name: "--obs_column_names"
          type: string
          description: "obs columns of interest. If not specified, all columns will be returned."
          required: false
          multiple: true   
        - name: "--metadata_only"
          type: boolean
          default: True
          description: By default only returns metadata of obs layer of query. If False, returns metadata of obs layer and gene expression matrix of query
          required: false
    - name: Outputs
      description: Output arguments.
      arguments:
        - name: "--output"
          type: file
          description: Output h5mu file.
          direction: output
          required: true
          example: output.h5mu
        - name: "--output_compression"
          type: string
          choices: ["gzip", "lzf"]
          required: false
          example: "gzip"
  resources:
    - type: python_script
      path: script.py
    - path: ./cl-base.obo
  test_resources:
    - type: python_script
      path: test.py
platforms:
  - type: docker
  # TODO: increase python version
    image: python:3.9
    setup:
      - type: python
        packages:
          - mudata~=0.2.0
          - anndata~=0.8.0
          - cellxgene-census~=1.2.0
          - obonet~=1.0.0
    test_setup:
      - type: python
        packages:
          - viashpy
  - type: nextflow
    directives:
      label: [highmem]