functionality:
  name: pynndescent_knn
  namespace: "labels_transfer"
  description: |
    This component generates a neighborhood graph based using the PyNNDescentTransformer, followed by classification using a k-nearest neighborhood vote.
  authors:
    - __merge__: /src/authors/dorien_roosen.yaml
      roles: [ maintainer ]
  argument_groups:
    - name: Input files
      arguments:
        - type: file
          name: --input
          required: false
          description: |
            The FASTQ files to be analyzed. FASTQ files should conform to the naming conventions of bcl2fastq and mkfastq:
            `[Sample Name]_S[Sample Index]_L00[Lane Number]_[Read Type]_001.fastq.gz`
          example: [ mysample_S1_L001_R1_001.fastq.gz, mysample_S1_L001_R2_001.fastq.gz ]
          multiple: true
          
  resources:
    - type: python_script
      path: script.py

platforms:
  - type: docker
    image: python:3.12
    setup:
      - type: apt
        packages: 
          - procps
          - pkg-config
          - libhdf5-dev
      - type: python
        __merge__: /src/base/requirements/anndata_mudata.yaml
  - type: native
  - type: nextflow
    directives:
      label: [singlecpu, lowmem]