functionality:
  name: pynndescent_knn
  namespace: "labels_transfer"
  description: |
    This component generates a neighborhood graph based using the PyNNDescentTransformer, followed by classification using a k-nearest neighborhood vote.
  authors:
    - __merge__: /src/authors/dorien_roosen.yaml
      roles: [ maintainer, author ]
    - __merge__: /src/authors/vladimir_shitov.yaml
      roles: [ author ]

  __merge__: ../api/common_arguments.yaml

  argument_groups:

    - name: KNN label transfer arguments
      arguments:
        - name: "--weights"
          type: string
          choices: ["uniform", "distance", "gaussian"]
          default: "uniform"
          description: |
            Weight function used in prediction. Possible values are:
            - `uniform` - all points in each neighborhood are weighted equally 
            - `distance` - weight points by the inverse of their distance
            - `gaussian` - weight points by the sum of their Gaussian kernel similarities to each sample
        - name: "--n_neighbors"
          type: integer
          min: 5
          default: 15
          description: |
            The number of neighbors to use in k-neighbor graph structure used for fast approximate nearest neighbor search with PyNNDescent. 
            Larger values will result in more accurate search results at the cost of computation time.
  resources:
    - type: python_script
      path: script.py
    - path: ../utils/helper.py

  test_resources:
    - type: python_script
      path: test.py
    - path: /resources_test/annotation_test_data/
    - path: /resources_test/pbmc_1k_protein_v3/

platforms:
  - type: docker
    image: python:3.12
    setup:
      - type: apt
        packages: 
          - procps
          - pkg-config
          - libhdf5-dev
      - type: python
        __merge__: /src/base/requirements/anndata_mudata.yaml
      - type: python
        packages:
          - pynndescent~=0.5.10
          - numpy<2
    test_setup:
      - type: python
        __merge__: [ /src/base/requirements/viashpy.yaml ]
  - type: nextflow
    directives:
      label: [highmem, highcpu]
