functionality:
  name: pynndescent_knn
  namespace: "labels_transfer"
  description: |
    This component generates a neighborhood graph based using the PyNNDescentTransformer, followed by classification using a k-nearest neighborhood vote.
  authors:
    - __merge__: /src/authors/dorien_roosen.yaml
      roles: [ maintainer ]
  arguments:
    - name: "--input"
      type: file
      description: Path to a single .h5mu file.
      required: true
    - name: "--modality"
      type: string
      default: "rna"
      required: false
    - name: "--output"
      type: file
      required: true
      direction: output
      example: "/path/to/output"
      description: Output directory containing multiple h5mu files.
    - name: "--obs_feature"
      type: string
      required: true
      description: The obs column to split the samples on.
      example: "celltype"
    - name: "--drop_obs_nan"
      type: boolean_true
      description: whether to drop all .obs columns that contain only nan values after splitting.
    - name: "--output_compression"
      type: string
      description: The compression format to be used on the output h5mu object.
      choices: ["gzip", "lzf"]
      required: false
      example: "gzip"
    - name: "--output_files"
      type: file
      required: true
      direction: output
      example: sample_files.csv
      description: A csv containing the base filename and modality type per output file.

  resources:
    - type: python_script
      path: script.py

platforms:
  - type: docker
    image: python:3.12
    setup:
      - type: apt
        packages: 
          - procps
          - pkg-config
          - libhdf5-dev
      - type: python
        __merge__: /src/base/requirements/anndata_mudata.yaml
  - type: native
  - type: nextflow
    directives:
      label: [singlecpu, lowmem]