functionality:
  name: pynndescent_knn
  namespace: "labels_transfer"
  description: |
    This component generates a neighborhood graph based using the PyNNDescentTransformer, followed by classification using a k-nearest neighborhood vote.
  authors:
    - __merge__: /src/authors/dorien_roosen.yaml
      roles: [ maintainer, author ]
  argument_groups:
    - name: Input files
      arguments:
        - name: "--input"
          type: file
          direction: input
          required: true
          example: input.h5mu
          description: "The query data to transfer the labels to. Should be a .h5mu file."
        - name: "--modality"
          type: string
          default: "rna"
          required: false
          description: Which modality to use.
        - name: "--input_obsm_features"
          type: string
          required: true
          description: |
            The `.obsm` key of the embedding to use for the classifier's inference.
            Make sure that embedding was obtained in the same way as the reference embedding (e.g. by the same model, preprocessing and/or integration).
          example: X_scvi

  resources:
    - type: python_script
      path: script.py

platforms:
  - type: docker
    image: python:3.12
    setup:
      - type: apt
        packages: 
          - procps
          - pkg-config
          - libhdf5-dev
      - type: python
        __merge__: /src/base/requirements/anndata_mudata.yaml
  - type: native
  - type: nextflow
    directives:
      label: [singlecpu, lowmem]