functionality:
  name: "scgpt_integration_knn"
  namespace: "workflows/annotation"
  description: "Pipeline for cell type annotation using leiden integration of reference and query dataset followed by KNN label transfer."
  authors:
    - __merge__: /src/authors/dorien_roosen.yaml
      roles: [ author, maintainer ]
    - __merge__: /src/authors/weiwei_schultz.yaml
      roles: [ contributor ]
    - __merge__: /src/authors/elizabeth_mlynarski.yaml
      roles: [ author ]

  __merge__: ../api/common_arguments_scgpt.yaml
  __merge__: ../api/common_arguments_integration_knn.yaml

  argument_groups:
    - name: scGPT integration options
      arguments:
        - name: "--obsm_integrated"
          type: string
          default: "X_scGPT"
          required: false
          description: "In which .obsm slot to store the resulting integrated embedding."
        - name: --dsbn
          type: boolean
          default: true
          description: |
            Apply domain-specific batch normalization
        - name: "--batch_size"
          type: integer
          default: 64
          description: |
            The batch size to be used for embedding inference.

  dependencies:
    - name: workflows/integration/scgpt_leiden
      alias: scgpt_leiden_workflow
    - name: labels_transfer/pynndescent_knn
    - name: dataflow/split_samples
    - name: dataflow/concatenate_h5mu
    - name: metadata/add_id

  resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: run_wf

platforms:
  - type: nextflow