functionality:
  name: "cell_type_annotation"
  namespace: "scgpt"
  version: "main_build"
  authors:
  - name: "Dorien Roosen"
    roles:
    - "maintainer"
    - "author"
    info:
      role: "Contributor"
      links:
        email: "dorien@data-intuitive.com"
        github: "dorien-er"
        linkedin: "dorien-roosen"
      organizations:
      - name: "Data Intuitive"
        href: "https://www.data-intuitive.com"
        role: "Data Scientist"
  - name: "Jakub Majercik"
    roles:
    - "author"
    info:
      role: "Contributor"
      links:
        email: "jakub@data-intuitive.com"
        github: "jakubmajercik"
        linkedin: "jakubmajercik"
      organizations:
      - name: "Data Intuitive"
        href: "https://www.data-intuitive.com"
        role: "Bioinformatics Engineer"
  argument_groups:
  - name: "Model input"
    arguments:
    - type: "file"
      name: "--model"
      description: "The model file containing checkpoints and cell type label mapper.\n"
      info: null
      example:
      - "best_model.pt"
      must_exist: true
      create_parent: true
      required: true
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--model_config"
      description: "The model configuration file. \n"
      info: null
      example:
      - "args.json"
      must_exist: true
      create_parent: true
      required: true
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--model_vocab"
      description: "Model vocabulary file directory.\n"
      info: null
      example:
      - "vocab.json"
      must_exist: true
      create_parent: true
      required: true
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--finetuned_checkpoints_key"
      description: "Key in the model file containing the pretrained checkpoints.\n"
      info: null
      default:
      - "model_state_dict"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--label_mapper_key"
      description: "Key in the model file containing the cell type class to label\
        \ mapper dictionary.\n"
      info: null
      default:
      - "id_to_class"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  - name: "Query input"
    arguments:
    - type: "file"
      name: "--input"
      description: "The input h5mu file containing of data that have been pre-processed\
        \ (normalized, binned, genes cross-checked and tokenized).\n"
      info: null
      example:
      - "scgpt_preprocess_ouput.h5mu"
      must_exist: true
      create_parent: true
      required: true
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--modality"
      info: null
      default:
      - "rna"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--obs_batch_label"
      description: "The name of the adata.obs column containing the batch labels.\
        \ Required if dsbn is set to true.\n"
      info: null
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--obsm_gene_tokens"
      description: "The key of the .obsm array containing the gene token ids\n"
      info: null
      default:
      - "gene_id_tokens"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--obsm_tokenized_values"
      description: "The key of the .obsm array containing the count values of the\
        \ tokenized genes\n"
      info: null
      default:
      - "values_tokenized"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  - name: "Outputs"
    arguments:
    - type: "file"
      name: "--output"
      description: "The output mudata file.\n"
      info: null
      example:
      - "output.h5mu"
      must_exist: true
      create_parent: true
      required: true
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--output_compression"
      description: "The compression algorithm to use for the output h5mu file.\n"
      info: null
      example:
      - "gzip"
      default:
      - "gzip"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--output_obs_predictions"
      description: "The name of the adata.obs column to write predicted cell type\
        \ labels to.\n"
      info: null
      default:
      - "scgpt_pred"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--output_obs_probability"
      description: "The name of the adata.obs column to write the probabilities of\
        \ the predicted cell type labels to.\n"
      info: null
      default:
      - "scgpt_probability"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  - name: "Arguments"
    arguments:
    - type: "string"
      name: "--pad_token"
      description: "The padding token used in the model.\n"
      info: null
      default:
      - "<pad>"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--pad_value"
      description: "The value of the padding.\n"
      info: null
      default:
      - -2
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--n_input_bins"
      description: "The number of input bins.\n"
      info: null
      default:
      - 51
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--batch_size"
      description: "The batch size. \n"
      info: null
      default:
      - 64
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "boolean"
      name: "--dsbn"
      description: "Whether to use domain-specific batch normalization.\n"
      info: null
      default:
      - true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--seed"
      description: "Seed for random number generation. If not specified, no seed is\
        \ used.\n"
      info: null
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  resources:
  - type: "python_script"
    path: "script.py"
    is_executable: true
  - type: "file"
    path: "src/utils/setup_logger.py"
  - type: "file"
    path: "./src/workflows/utils/labels.config"
    dest: "nextflow_labels.config"
  description: "Annotate gene expression data with cell type classes through the scGPT\
    \ model.\n"
  test_resources:
  - type: "python_script"
    path: "test.py"
    is_executable: true
  - type: "file"
    path: "resources_test/scgpt/test_resources/Kim2020_Lung_subset_tokenized.h5mu"
  - type: "file"
    path: "resources_test/scgpt/source/best_model.pt"
  - type: "file"
    path: "resources_test/scgpt/source/args.json"
  - type: "file"
    path: "resources_test/scgpt/source/vocab.json"
  - type: "file"
    path: "src/base/openpipelinetestutils"
    dest: "openpipelinetestutils"
  info: null
  status: "enabled"
  requirements:
    commands:
    - "ps"
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "nvcr.io/nvidia/pytorch:23.09-py3"
  target_organization: "openpipelines-bio"
  target_registry: "ghcr.io"
  target_tag: "main_build"
  namespace_separator: "/"
  resolve_volume: "Automatic"
  chown: true
  setup_strategy: "ifneedbepullelsecachedbuild"
  target_image_source: "https://github.com/openpipelines-bio/openpipeline"
  setup:
  - type: "python"
    user: false
    packages:
    - "anndata~=0.10.8"
    - "mudata~=0.2.4"
    - "pandas!=2.1.2"
    - "numpy<2.0.0"
    - "scanpy~=1.9.6"
    upgrade: true
  - type: "python"
    user: false
    packages:
    - "scgpt==0.2.1"
    upgrade: true
  test_setup:
  - type: "docker"
    copy:
    - "openpipelinetestutils /opt/openpipelinetestutils"
  - type: "python"
    user: false
    packages:
    - "/opt/openpipelinetestutils"
    upgrade: true
  - type: "python"
    user: false
    packages:
    - "viashpy==0.6.0"
    upgrade: true
  - type: "python"
    user: false
    packages:
    - "scanpy~=1.9.6"
    upgrade: true
  entrypoint: []
  cmd: null
- type: "nextflow"
  id: "nextflow"
  directives:
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      mem1gb: "memory = 1.GB"
      mem2gb: "memory = 2.GB"
      mem4gb: "memory = 4.GB"
      mem8gb: "memory = 8.GB"
      mem16gb: "memory = 16.GB"
      mem32gb: "memory = 32.GB"
      mem64gb: "memory = 64.GB"
      mem128gb: "memory = 128.GB"
      mem256gb: "memory = 256.GB"
      mem512gb: "memory = 512.GB"
      mem1tb: "memory = 1.TB"
      mem2tb: "memory = 2.TB"
      mem4tb: "memory = 4.TB"
      mem8tb: "memory = 8.TB"
      mem16tb: "memory = 16.TB"
      mem32tb: "memory = 32.TB"
      mem64tb: "memory = 64.TB"
      mem128tb: "memory = 128.TB"
      mem256tb: "memory = 256.TB"
      mem512tb: "memory = 512.TB"
      cpu1: "cpus = 1"
      cpu2: "cpus = 2"
      cpu5: "cpus = 5"
      cpu10: "cpus = 10"
      cpu20: "cpus = 20"
      cpu50: "cpus = 50"
      cpu100: "cpus = 100"
      cpu200: "cpus = 200"
      cpu500: "cpus = 500"
      cpu1000: "cpus = 1000"
    script:
    - "includeConfig(\"nextflow_labels.config\")"
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/openpipeline/openpipeline/src/scgpt/cell_type_annotation/config.vsh.yaml"
  platform: "nextflow"
  output: "/home/runner/work/openpipeline/openpipeline/target/nextflow/scgpt/cell_type_annotation"
  executable: "/home/runner/work/openpipeline/openpipeline/target/nextflow/scgpt/cell_type_annotation/cell_type_annotation"
  viash_version: "0.8.6"
  git_commit: "701a8375418dfe0819302517756d3706c4305b52"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
