# Inputs
input: # please fill in - example: "resources_test/scgpt/test_resources/Kim2020_Lung_preprocessed.h5mu"
modality: "rna"
model: # please fill in - example: "resources_test/scgpt/source/best_model.pt"
model_config: # please fill in - example: "resources_test/scgpt/source/args.json"
model_vocab: # please fill in - example: "resources_test/scgpt/vocab.json"
# obs_batch_label: "foo"
obsm_gene_tokens: "gene_id_tokens"
obsm_tokenized_values: "values_tokenized"

# Outputs
# output: "$id.$key.output.h5mu"
output_compression: "gzip"
obs_predicted_cell_type: "predicted_cell_type"

# Arguments
pad_token: "<pad>"
pad_value: -2
n_cls: 8
n_input_bins: 51
batch_size: 64
dsbn: true
# seed: 123

# Nextflow input-output arguments
publish_dir: # please fill in - example: "output/"
# param_list: "my_params.yaml"
