functionality:
  name: "multisample"
  namespace: "multiomics"
  description: |
    This workflow serves as an entrypoint into the 'full_pipeline' in order to
    re-run the multisample processing and the integration setup. An input .h5mu file will 
    first be split in order to run the multisample processing per modality. Next, the modalities
    are merged again and the integration setup pipeline is executed. Please note that this workflow
    assumes that samples from multiple pipelines are already concatenated. 
  authors:
    - __merge__: /src/authors/dries_schaumont.yaml
      roles: [ author, maintainer ]
  argument_groups:
    - name: Inputs
      arguments:
        - name: "--id"
          required: true
          type: string
          description: ID of the sample.
          example: foo
        - name: "--input"
          alternatives: [-i]
          description: Path to the sample.
          required: true
          example: input.h5mu
          type: file
    - name: "Outputs"
      arguments:
        - name: "--output"
          type: file
          required: true
          direction: output
          description: Destination path to the output.
          example: output.h5mu
    - name: "Highly variable gene detection"
      arguments:
        - name: "--filter_with_hvg_var_output"
          required: false
          type: string
          default: "filter_with_hvg"
          description: In which .var slot to store a boolean array corresponding to the highly variable genes.
        - name: "--filter_with_hvg_obs_batch_key"
          type: string
          default: "sample_id"
          required: false
          description: |
            If specified, highly-variable genes are selected within each batch separately and merged. This simple 
            process avoids the selection of batch-specific genes and acts as a lightweight batch correction method.
    - name: "QC metrics calculation options"
      arguments:
        - name: "--var_qc_metrics"
          description: |
            Keys to select a boolean (containing only True or False) column from .var.
            For each cell, calculate the proportion of total values for genes which are labeled 'True', 
            compared to the total sum of the values for all genes.
          type: string
          multiple: True
          multiple_sep: ','
          required: false
          default: ["filter_with_hvg"]
          example: "ercc,highly_variable"
        - name: "--top_n_vars"
          type: integer
          description: |
            Number of top vars to be used to calculate cumulative proportions.
            If not specified, proportions are not calculated. `--top_n_vars 20,50` finds
            cumulative proportion to the 20th and 50th most expressed vars.
          multiple: true
          multiple_sep: ','
          required: false
          default: [50, 100, 200, 500]
  resources:
    - type: nextflow_script
      path: main.nf
  test_resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: test_wf
    - path: ../../../resources_test/concat_test_data
