functionality:
  name: "dimensionality_reduction_test"
  namespace: "test_workflows/multiomics"
  description: "This component test the output of the integration test of dimensionality_reduction."
  authors:
    - __merge__: /src/authors/kai_waldrant.yaml
  argument_groups:
    - name: Inputs
      arguments:
        - name: "--input"
          type: file
          required: true
          description: Path to h5mu output.
          example: foo.final.h5mu
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: python:3.12-slim
    setup:
      - type: apt
        packages: 
          - procps
      - type: python
        pypi:
          - mudata
  - type: nextflow