functionality:
  name: "harmony_knn"
  namespace: "workflows/annotation"
  description: "Pipeline for cell type annotation using leiden integration of reference and query dataset followed by KNN label transfer."
  authors:
    - __merge__: /src/authors/dorien_roosen.yaml
      roles: [ author, maintainer ]
  argument_groups:
    - name: Inputs
      arguments:
        - name: "--id"
          required: true
          type: string
          description: ID of the sample.
          example: foo
        - name: "--input_query_dataset"
          required: true
          type: file
          description: Input dataset consisting of the (unlabeled) query observations. The dataset is expected to be pre-processed in the same way as --input_reference_dataset.
          example: input.h5mu
        - name: "--input_reference_dataset"
          required: true
          type: file
          description: Input dataset consisting of the (labeled) reference observations. The dataset is expected to be pre-processed in the same way as --input_query_dataset.
        - name: "--modality"
          description: Which modality to process.
          type: string
          default: "rna"
          required: false
        - name: "--embedding"
          example: "X_pca"
          type: string
          description: "Embedding to use as input"
        - name: "--obs_reference_targets"
          type: string
          example: [ ann_level_1, ann_level_2, ann_level_3, ann_level_4, ann_level_5, ann_finest_level ]
          required: true
          multiple: true
          description: The `.obs` key(s) of the target labels to tranfer.

    - name: "Outputs"
      arguments:
        - name: "--output"
          type: file
          required: true
          direction: output
          description: Destination path to the output.
          example: output.h5mu
        - name: "--output_obs_predictions"
          type: string
          required: false
          multiple: true
          description: |
            In which `.obs` slots to store the predicted information.
            If provided, must have the same length as `--reference_obs_targets`.
            If empty, will default to the `reference_obs_targets` combined with the `"_pred"` suffix.
        - name: "--output_obs_probability"
          type: string
          required: false
          multiple: true
          description: |
            In which `.obs` slots to store the probability of the predictions.
            If provided, must have the same length as `--reference_obs_targets`.
            If empty, will default to the `reference_obs_targets` combined with the `"_probability"` suffix.
        - name: "--output_compression"
          type: string
          description: |
            The compression format to be used on the output h5mu object.
          choices: ["gzip", "lzf"]
          required: false
          example: "gzip"
      
    - name: Harmony integration options
      arguments:
        - name: "--theta"
          type: double
          description: |
            Diversity clustering penalty parameter. Specify for each variable in group.by.vars. 
            theta=0 does not encourage any diversity. Larger values of theta
            result in more diverse clusters."
          default: 2
          multiple: true
        - name: "--obs_covariates"
          type: string
          description: "The .obs field(s) that define the covariate(s) to regress out."
          example: ["batch", "sample"]
          required: true
          multiple: true
        - name: "--obsm_integrated"
          type: string
          default: "X_integrated_harmony"
          required: false
          description: "In which .obsm slot to store the resulting integrated embedding."

    - name: Neighbor classifier arguments
      arguments:
        - name: "--weights"
          type: string
          default: "uniform"
          choices: ["uniform", "distance"]
          description: |
            Weight function used in prediction. Possible values are:
            `uniform` (all points in each neighborhood are weighted equally) or 
            `distance` (weight points by the inverse of their distance)
        - name: "--n_neighbors"
          type: integer
          default: 15
          required: false
          description: |
            The number of neighbors to use in k-neighbor graph structure used for fast approximate nearest neighbor search with PyNNDescent. 
            Larger values will result in more accurate search results at the cost of computation time.

  dependencies:
    - name: integrate/harmonypy
    - name: labels_transfer/pynndescent_knn
    - name: dataflow/split_samples
    - name: dataflow/concatenate_h5mu
    - name: metadata/add_id
    - name: workflows/multiomics/split_modalities
      alias: split_modalities_workflow

  resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: run_wf

platforms:
  - type: nextflow
