functionality:
  name: "integration_metrics"
  namespace: "qc"
  version: "integration-qc_build"
  authors:
  - name: "Dorien Roosen"
    roles:
    - "author"
    info:
      role: "Contributor"
      links:
        email: "dorien@data-intuitive.com"
        github: "dorien-er"
        linkedin: "dorien-roosen"
      organizations:
      - name: "Data Intuitive"
        href: "https://www.data-intuitive.com"
        role: "Data Scientist"
  argument_groups:
  - name: "Inputs"
    arguments:
    - type: "file"
      name: "--input"
      description: "Input h5mu file"
      info: null
      example:
      - "input.h5mu"
      must_exist: true
      create_parent: true
      required: true
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--modality"
      info: null
      default:
      - "rna"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--obsm_embeddings"
      description: "The name of the adata.obsm array containing scGPT cell embeddings.\n"
      info: null
      example:
      - "X_scGPT"
      required: true
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--obs_batch_label"
      description: "The name of the adata obs column containing the batch labels.\n"
      info: null
      example:
      - "sample"
      required: true
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--obs_cell_label"
      description: "The name of the adata obs column containing the cell type labels.\n"
      info: null
      example:
      - "cell_type"
      required: true
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--obs_cluster"
      description: "The name of the adata obs column containing the cluster labels.\n"
      info: null
      example:
      - "cluster"
      required: true
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--uns_neighbors"
      description: "The name of the adata uns object containing the neighbors information."
      info: null
      example:
      - "neighbors"
      required: true
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--obsp_neighbor_connectivities"
      description: "The name of the adata obsp object containing the neighbor connectivities.\n"
      info: null
      example:
      - "connectivities"
      required: true
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  - name: "Outputs"
    arguments:
    - type: "file"
      name: "--output"
      description: "Output h5mu file."
      info: null
      example:
      - "output.h5mu"
      must_exist: true
      create_parent: true
      required: false
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--output_compression"
      description: "The compression format to be used on the output h5mu object."
      info: null
      example:
      - "gzip"
      required: false
      choices:
      - "gzip"
      - "lzf"
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  resources:
  - type: "python_script"
    path: "script.py"
    is_executable: true
  - type: "file"
    path: "./src/workflows/utils/labels.config"
    dest: "nextflow_labels.config"
  description: "Add integration qc metrics to an .h5mu file.\n\nThe metrics are generated\
    \ using the scib library and stored in the uns column:\n  - nmi_score: scib.metrics.nmi\n\
    \  - ari_score: scib.metrics.ari\n  - asw_batch: scib.metrics.silhouette_batch\n\
    \  - asw_label: scib.metrics.silhouette\n  - pcr_score: scib.metrics.pcr_comparison\n\
    \  - graph_connectivity: scib.metrics.graph_connectivity\n  - avg_bio: mean of\
    \ nmi_score, ari_score and asw_label\n  \n"
  test_resources:
  - type: "file"
    path: "src/base/openpipelinetestutils"
    dest: "openpipelinetestutils"
  info: null
  status: "enabled"
  requirements:
    commands:
    - "ps"
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "python:3.11"
  target_organization: "openpipelines-bio"
  target_registry: "ghcr.io"
  target_tag: "integration-qc_build"
  namespace_separator: "/"
  resolve_volume: "Automatic"
  chown: true
  setup_strategy: "ifneedbepullelsecachedbuild"
  target_image_source: "https://github.com/openpipelines-bio/openpipeline"
  setup:
  - type: "apt"
    packages:
    - "procps"
    - "libhdf5-dev"
    - "gfortran"
    - "cmake"
    - "libopenblas-dev"
    interactive: false
  - type: "python"
    user: false
    packages:
    - "anndata~=0.9.1"
    - "mudata~=0.2.3"
    - "pandas!=2.1.2"
    upgrade: true
  - type: "python"
    user: false
    packages:
    - "scib==1.1.5"
    upgrade: true
  test_setup:
  - type: "python"
    user: false
    packages:
    - "viashpy==0.6.0"
    upgrade: true
  entrypoint: []
  cmd: null
- type: "nextflow"
  id: "nextflow"
  directives:
    label:
    - "singlecpu"
    - "lowmem"
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      mem1gb: "memory = 1.GB"
      mem2gb: "memory = 2.GB"
      mem4gb: "memory = 4.GB"
      mem8gb: "memory = 8.GB"
      mem16gb: "memory = 16.GB"
      mem32gb: "memory = 32.GB"
      mem64gb: "memory = 64.GB"
      mem128gb: "memory = 128.GB"
      mem256gb: "memory = 256.GB"
      mem512gb: "memory = 512.GB"
      mem1tb: "memory = 1.TB"
      mem2tb: "memory = 2.TB"
      mem4tb: "memory = 4.TB"
      mem8tb: "memory = 8.TB"
      mem16tb: "memory = 16.TB"
      mem32tb: "memory = 32.TB"
      mem64tb: "memory = 64.TB"
      mem128tb: "memory = 128.TB"
      mem256tb: "memory = 256.TB"
      mem512tb: "memory = 512.TB"
      cpu1: "cpus = 1"
      cpu2: "cpus = 2"
      cpu5: "cpus = 5"
      cpu10: "cpus = 10"
      cpu20: "cpus = 20"
      cpu50: "cpus = 50"
      cpu100: "cpus = 100"
      cpu200: "cpus = 200"
      cpu500: "cpus = 500"
      cpu1000: "cpus = 1000"
    script:
    - "includeConfig(\"nextflow_labels.config\")"
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/openpipeline/openpipeline/src/qc/integration_metrics/config.vsh.yaml"
  platform: "docker"
  output: "/home/runner/work/openpipeline/openpipeline/target/docker/qc/integration_metrics"
  executable: "/home/runner/work/openpipeline/openpipeline/target/docker/qc/integration_metrics/integration_metrics"
  viash_version: "0.8.5"
  git_commit: "3561431e6b44df6a0352c06ed83df97e41b0d649"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
  git_tag: "0.2.0-1581-g3561431e6b"
