functionality:
  name: cellranger_multi
  namespace: mapping
  description: Align fastq files using Cell Ranger multi.
  authors:
    - __merge__: /src/authors/angela_pisco.yaml
      roles: [ author ]
    - __merge__: /src/authors/robrecht_cannoodt.yaml
      roles: [ author, maintainer ]
    - __merge__: /src/authors/dries_de_maeyer.yaml
      roles: [ author ]
  __merge__: /src/mapping/cellranger_multi/cellranger_multi.yaml
  argument_groups:
    - name: Outputs
      arguments:
        - type: file
          name: --output
          direction: output
          description: The folder to store the alignment results.
          example: "/path/to/output"
          required: true

    - name: Executor arguments
      arguments:
        - name: "--dryrun"
          type: boolean_true
          description: "If true, the output directory will only contain the CWL input files, but the pipeline itself will not be executed."
        - name: "--disable_library_compatibility_check"
          type: boolean_true
          description: |
            Disable the check that evaluates 10x Barcode overlap between libraries when multiple libraries are specified 
            (e.g., Gene Expression + Antibody Capture). Setting this option will disable the check across all library combinations
  resources:
    - type: python_script
      path: script.py
    - path: /src/utils/setup_logger.py
  test_resources:
    - type: python_script
      path: test.py
    - path: /resources_test/10x_5k_anticmv/raw/
      dest: 10x_5k_anticmv/raw/
    - path: /resources_test/10x_5k_lung_crispr/raw/
      dest: 10x_5k_lung_crispr/raw/
    - path: /resources_test/10x_5k_beam/raw/
      dest: 10x_5k_beam/raw/
    - path: /resources_test/10x_5k_fixed/raw/
      dest: 10x_5k_fixed/raw 
    - path: /resources_test/10x_5k_beam/raw/ 
    - path: /resources_test/reference_gencodev41_chr1
platforms:
  - type: docker
    image: ghcr.io/data-intuitive/cellranger:8.0
    setup:
      - type: docker
        run: |
          DEBIAN_FRONTEND=noninteractive apt update && \
          apt upgrade -y && apt install -y procps && rm -rf /var/lib/apt/lists/*
      - type: python
        packages: 
          - pandas
          - pyyaml
    __merge__: [ /src/base/requirements/python_test_setup.yaml, .] 
  - type: nextflow
    directives:
      label: [ veryhighmem, highcpu ]
