id: sample

# Input files
input:
  - "resources_test/10x_5k_anticmv/raw/5k_human_antiCMV_T_TBNK_connect_GEX_1_subset_S1_L001_R1_001.fastq.gz"
  - "resources_test/10x_5k_anticmv/raw/5k_human_antiCMV_T_TBNK_connect_GEX_1_subset_S1_L001_R2_001.fastq.gz"
  - "resources_test/10x_5k_anticmv/raw/5k_human_antiCMV_T_TBNK_connect_AB_subset_S2_L004_R1_001.fastq.gz"
  - "resources_test/10x_5k_anticmv/raw/5k_human_antiCMV_T_TBNK_connect_AB_subset_S2_L004_R2_001.fastq.gz"
  - "resources_test/10x_5k_anticmv/raw/5k_human_antiCMV_T_TBNK_connect_VDJ_subset_S1_L001_R1_001.fastq.gz"
  - "resources_test/10x_5k_anticmv/raw/5k_human_antiCMV_T_TBNK_connect_VDJ_subset_S2_L001_R1_001.fastq.gz"
gex_reference: resources_test/reference_gencodev41_chr1/reference_cellranger.tar.gz
vdj_reference:
feature_reference: resources_test/10x_5k_anticmv/raw/feature_reference.csv

# Library arguments
library_id:
  - "5k_human_antiCMV_T_TBNK_connect_GEX_1"
  - "5k_human_antiCMV_T_TBNK_connect_AB"
  - "5k_human_antiCMV_T_TBNK_connect_VDJ"
library_type:
  - "Gene Expression"
  - "Antibody Capture"
  - "VDJ"
library_subsample: 
  - 0.95
  - 0.8
  - 0.9

# Gene expression arguments
gex_expect_cells: 1000
gex_chemistry: threeprime
gex_secondary_analysis: false
gex_generate_bam: false
gex_include_introns: true

# Outputs
output: output/