functionality:
  name: "from_10xh5_to_h5ad"
  enabled: false
  namespace: "convert"
  version: "dev"
  description: |
    Converts a 10x h5 into an h5ad file.
  authors:
    - name: Robrecht Cannoodt
      email: rcannood@gmail.com
      roles: [ maintainer ]
      props: { github: rcannood, orcid: "0000-0003-3641-729X" }
  arguments:
    - name: "--input"
      alternatives: ["-i"]
      type: file
      description: Input h5 file
      example: input.h5
      direction: input
      required: true
    - name: "--output"
      alternatives: ["-o"]
      type: file
      description: Output h5ad file.
      example: output.h5ad
      direction: output
    - name: "--gex_only"
      type: boolean_true
      description: Only keep 'Gene Expression' data and ignore other feature types, e.g. 'Antibody Capture', 'CRISPR Guide Capture', or 'Custom'.
  resources:
    - type: python_script
      path: script.py
  test_resources:
    - type: python_script
      path: run_test.py
    - path: ../../../resources_test/pbmc_1k_protein_v3
platforms:
  - type: docker
    image: python:3.8-slim
    setup:
      - type: python
        packages: [ scanpy~=1.9.1, anndata<0.8]
  - type: nextflow
    variant: vdsl3
