functionality:
  name: cellranger_atac_mkfastq
  namespace: demux
  description: Demultiplex raw sequencing data for ATAC experiments
  usage: |
    cellranger_atac_mkfastq \
      --input /path/to/bcl \
      --csv simple_layout_sample_sheet.csv \
      --output /path/to/output
  authors:
    - __merge__: /src/authors/vladimir_shitov.yaml
      roles: [ author ]
  arguments:
    - type: file
      name: --input
      description: Path of Illumina BCL run folder.
      example: /path/to/bcl
      required: true
    - type: file
      name: --csv
      description: The path to the simple layout sample sheet.
      example: SampleSheet.csv
      required: true
    - type: file
      name: --output
      direction: output
      description: The folder to store the demux results
      example: "/path/to/output"
      default: fastqs
      required: true
    - name: "--reports"
      type: file
      direction: output
      required: false
      description: Reports directory
      example: reports_dir
  resources:
    - type: bash_script
      path: script.sh
    - path: /src/utils/setup_logger.py
  test_resources:
    - type: python_script
      path: test.py
    - path: /resources_test/cellranger_tiny_bcl
platforms:
  - type: docker
    image: ghcr.io/data-intuitive/cellranger:6.1
    setup:
      - type: docker
        run: apt-get update && apt-get upgrade -y
    test_setup:
      - type: python
        __merge__: [ /src/base/requirements/viashpy.yaml, .]

  - type: nextflow
    directives:
      label: [ highmem, highcpu ]
