functionality:
  name: demux
  namespace: ingestion
  description: |
    Convert `.bcl` files to `.fastq` files using bcl2fastq, bcl-convert or Cell Ranger mkfastq.
  info:
    name: Demux
    short_description: A generic pipeline for running bcl2fastq, bcl-convert or Cell Ranger mkfastq.
  authors:
    - name: Toni Verbeiren
      roles: [ author, maintainer ]
      props: { github: tverbeiren }
    - name: Marijke Van Moerbeke
      roles: [ author ]
      props: { orcid: 0000-0002-3097-5621 }
    - name: Angela Pisco
      roles: [ author ]
      props: { github: aopisco, orcid: "0000-0003-0142-2355" }
    - name: Samuel D'Souza
      roles: [ author ]
      props: { github: srdsam }
    - name: Robrecht Cannoodt
      email: robrecht@data-intuitive.com
      roles: [ author ]
      props: { github: rcannood, orcid: "0000-0003-3641-729X" }
  arguments:
    - name: "--id"
      required: true
      type: string
      description: ID of the sample.
      example: foo
    - name: "--input"
      alternatives: [ "-i" ]
      type: file
      required: true
      description: Input run directory
      example: bcl_dir
    - name: "--sample_sheet"
      alternatives: [ "-s" ]
      type: file
      required: true
      description: Pointer to the sample sheet
      example: bcl_dir
    - name: "--demultiplexer"
      type: string
      description: The multiplexer to use, one of bclconvert or mkfastq
      choices: [ bclconvert, bcl2fastq, mkfastq ]
      default: bcl2fastq
    - name: "--ignore_missing"
      type: boolean
      description: Should the demultiplexer ignore missing entities (filter, ...)
  resources:
    - type: nextflow_script
      path: main.nf
  test_resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: test_wf
