functionality:
  name: pca
  namespace: "dimred"
  version: "dev"
  description: |
    Computes PCA coordinates, loadings and variance decomposition. Uses the implementation of scikit-learn [Pedregosa11].
  authors:
    - name: Dries De Maeyer
      email: ddemaeyer@gmail.com
      roles: [ maintainer ]
      props: { account: ddemaey1 }
  arguments:
    # inputs
    - name: "--input"
      alternatives: ["-i"]
      type: file
      description: Input h5mu file
      direction: input
      required: true
      example: input.h5mu

    - name: "--modality"
      type: string
      multiple: true
      default: "rna"
      required: false

    # outputs
    - name: "--output"
      alternatives: ["-o"]
      type: file
      description: Output h5mu file.
      direction: output
      required: true
      example: output.h5mu

    - name: "--output_key"
      type: string
      description: The pre/postfix under which to store the PCA results. More specifically, .obsm["X_"+key], .uns[key] and .varm["loadings_"+key].
      default: "pca"
    
    # arguments
    - name: "--num_components"
      type: integer
      example: 25
      description: Number of principal components to compute. Defaults to 50, or 1 - minimum dimension size of selected representation.
  resources:
    - type: python_script
      path: script.py
  test_resources:
    - type: python_script
      path: run_test.py
    - path: ../../../resources_test/pbmc_1k_protein_v3
platforms:
  - type: docker
    image: python:3.8-slim
    python:
      packages:
        - scanpy~=1.9.1
        - muon
        - mudata~=0.1.2
        - anndata<0.8
  - type: nextflow
    variant: vdsl3
    directives:
      label: highcpu
