name: "conversion_test"
namespace: "test_workflows/ingestion"
description: "This component test the output of the integration test of the conversion workflow."
authors:
  - __merge__: /src/authors/jakub_majercik.yaml
argument_groups:
  - name: Inputs
    arguments:
      - name: "--input"
        type: file
        required: true
        description: Path to h5mu output.
        example: foo.final.h5mu
resources:
  - type: python_script
    path: script.py
  - path: /src/utils/setup_logger.py
  - path: /src/base/openpipelinetestutils
    dest: openpipelinetestutils
engines:
  - type: docker
    image: python:3.12-slim
    setup:
      - type: docker
        copy: ["openpipelinetestutils /opt/openpipelinetestutils"]
      - type: apt
        packages: 
          - procps
      - type: python
        packages: /opt/openpipelinetestutils
        pypi:
          - mudata
        __merge__: /src/base/requirements/viashpy.yaml
runners:
  - type: executable
  - type: nextflow