functionality:
  name: build_cellranger_reference
  namespace: reference
  description: Build a Cell Ranger-compatible reference folder from user-supplied genome FASTA and gene GTF files. Creates a new folder named after the genome.
  authors:
    - __merge__: /src/authors/angela_pisco.yaml
      roles: [ author ]
    - __merge__: /src/authors/robrecht_cannoodt.yaml
      roles: [ author, maintainer ]
  arguments:
    # inputs
    - type: file
      name: --genome_fasta
      required: true
      description: Reference genome fasta.
      example: genome_sequence.fa.gz
    - type: file
      name: --transcriptome_gtf
      required: true
      description: Reference transcriptome annotation.
      example: transcriptome_annotation.gtf.gz
    - type: file
      name: --output
      direction: output
      required: true
      description: Output folder
      example: cellranger_reference
  resources:
    - type: bash_script
      path: script.sh
  test_resources:
    - type: bash_script
      path: run_test.sh
    - path: ../../../resources_test/reference_gencodev41_chr1
platforms:
  - type: docker
    image: ghcr.io/data-intuitive/cellranger:7.0
    setup:
      - type: apt
        packages: [ pigz ]
    test_setup:
      - type: docker
        env:
          - GOPATH /root/go
          - GOBIN /root/go/bin
          - PATH "${PATH}:/root/go/bin"
      - type: apt
        packages: [ golang, git ]
      - type: docker
        run: |
          go install golang.org/dl/go1.20.6@latest && go1.20.6 download && \
          git clone --branch v2.5.0 https://github.com/shenwei356/seqkit.git && \
          cd seqkit/seqkit/ && go1.20.6 build && cp seqkit /usr/bin/ && cd ../../ && rm -rf seqkit
  - type: nextflow
    directives:
      label: [ highmem, highcpu ]