functionality:
  name: "cellranger_mapping"
  namespace: "ingestion"
  description: "A pipeline for running Cell Ranger mapping."
  info:
    name: Cell Ranger mapping
  authors:
    - name: Angela Pisco
      roles: [ author ]
      props: { github: aopisco, orcid: "0000-0003-0142-2355" }
    - name: Samuel D'Souza
      roles: [ author ]
      props: { github: srdsam }
    - name: Robrecht Cannoodt
      email: robrecht@data-intuitive.com
      roles: [ author, maintainer ]
      props: { github: rcannood, orcid: "0000-0003-3641-729X" }
  arguments:
    - name: "--id"
      required: true
      type: string
      description: ID of the sample.
      example: foo
    - name: "--input"
      required: true
      type: file
      description: A fastq file.
      example: data.fastq
    - name: "--reference"
      required: true
      type: file
      description: Path to a Cell Ranger reference.
      example: reference.tar.gz
    - name: "--output_raw"
      type: file
      direction: output
      description: "The raw output folder."
      required: true
      example: output_dir/
    - name: "--output_h5mu"
      type: file
      direction: output
      description: "The converted h5mu file."
      required: true
      example: output.h5mu
  resources:
    - type: nextflow_script
      path: main.nf
  test_resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: test_wf