functionality:
  name: score_genes_cell_cycle
  description: |
    The script reads in a dataset of gene expression data, and then uses a machine learning algorithm to score the cell cycle phase of each cell in the dataset. The resulting scores are then written back to the dataset and saved to a specified location.
  arguments:
    - name: --input
      type: file
      description: Path to input h5mu file.
      required: true
    - name: --s_genes
      type: string
      required: true
      description: "Genes that define the S phase. Default: ['MCM5', 'PCNA', 'TYMS', 'FEN1', 'MCM2', 'MCM4', 'RRM1', 'UNG', 'GINS2', 'MCM6', 'CDCA7', 'DTL', 'PRIM1', 'UHRF1', 'MLF1IP', 'HELLS', 'RFC2', 'RPA2', 'NASP', 'RAD51AP1', 'GMNN', 'WDR76', 'SLBP', 'CCNE2', 'UBR7', 'POLD3', 'MSH2', 'ATAD2', 'RAD51', 'RRM2', 'CDC45', 'CDC6', 'EXO1', 'TIPIN', 'DSCC1', 'BLM', 'CASP8AP2', 'USP1', 'CLSPN', 'POLA1', 'CHAF1B', 'BRIP1', 'E2F8']"
    - name: --g2m_genes
      type: string
      required: true
      description: List of S/G2/M marker genes
    - name: --gene_pool
      type: string
      description: The gene pool from which to compute the cell cycle phase scores.
    - name: --n_bins
      type: integer
      description: Number of bins for binning the cell cycle genes. A large number of bins will result in more precise alignment, but can lead to overfitting. A small number of bins will lead to a more robust result, but might be too coarse.
    - name: --score_name
      type: string
      description: "Which score to use as cell cycle annotation. If not specified, the score will be stored in .uns['score'] as a structured array."
    - name: --random_state
      type: integer
      description: Random seed to ensure reproducibility
    - name: --copy
      type: boolean
      description: Copy adata object before computation or add score to adata.obs. Defaults to False.
    - name: --use_raw
      type: boolean
      description: Use .raw attribute of adata for resulting score.
    - name: --output
      type: file
      direction: output
      description: "Output h5mu file with score in .uns['score_genes_cell_cycle'] slot."
      example: output.h5mu
  resources:
    - path: script.py
      type: python_script
platforms:
  - type: docker
    image: python:3.8-slim
    setup:
      - type: python
        packages:
          - anndata
          - mudata
          - scanpy
