functionality:
  name: "qc_test"
  namespace: "test_workflows/qc"
  description: "This component test the output of the integration test of the QC workflow."
  authors:
    - __merge__: /src/authors/jakub_majercik.yaml
  argument_groups:
    - name: Inputs
      arguments:
        - name: "--input"
          type: file
          required: true
          description: Path to h5mu output.
          example: foo.final.h5mu
  resources:
    - type: python_script
      path: script.py
    - path: /src/utils/setup_logger.py
platforms:
  - type: docker
    image: python:3.12
    setup:
      - type: apt
        packages: 
          - procps
          - libhdf5-dev
      - type: python
        __merge__: [/src/base/requirements/anndata_mudata.yaml, .]
    __merge__: [/src/base/requirements/python_test_setup.yaml, .]
  - type: nextflow