functionality:
  name: "split_modalities_test"
  namespace: "test_workflows/multiomics"
  description: "This component test the output of the integration test of split_modalities."
  authors:
    - __merge__: /src/authors/kai_waldrant.yaml
  argument_groups:
    - name: Inputs
      arguments:
        - name: "--input"
          type: file
          required: true
          description: Path to modality summary csv.
          example: output_types.csv
        - name: "--mod_dir"
          type: file
          required: true
          description: Path to the directory containing the modality h5mu files.
          example: /path/to/h5mu_files
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: python:3.12-slim
    setup:
      - type: apt
        packages: 
          - procps
      - type: python
        pypi:
          - mudata
  - type: nextflow