functionality:
  name: "singlesample"
  namespace: "process_rna"
  description: "Processing unimodal single-sample RNA transcriptomics data."
  arguments:
    - name: "--id"
      required: true
      type: string
      description: ID of the sample.
      example: foo
    - name: "--input"
      type: file
      required: true
      description: Path to the sample.
      example: dataset.h5mu
  resources:
    - type: nextflow_script
      path: main.nf
  tests:
    - type: nextflow_script
      path: main.nf
      entrypoint: test_wf