functionality:
  name: "singlesample"
  namespace: "process_rna"
  description: "Processing unimodal single-sample RNA transcriptomics data."
  authors:
    - name: Dries De Maeyer
      email: ddemaeyer@gmail.com
      roles: [ author ]
      props: { account: ddemaey1 }
    - name: Robrecht Cannoodt
      email: rcannood@gmail.com
      roles: [ author, maintainer ]
      props: { github: rcannood, orcid: "0000-0003-3641-729X" }
  arguments:
    - name: "--id"
      required: true
      type: string
      description: ID of the sample.
      example: foo
    - name: "--input"
      type: file
      required: true
      description: Path to the sample.
      example: dataset.h5mu
    - name: "--output"
      type: file
      required: true
      direction: output
      description: Destination path to the output.
      example: output.h5mu
  resources:
    - type: nextflow_script
      path: main.nf
  test_resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: test_wf