functionality:
  name: embedding
  namespace: scgpt
  description: |
    Embedding of a batch of tokenized data for scGPT zero-shot or fine-tuning integration.
  authors:
    - __merge__: /src/authors/dorien_roosen.yaml
      roles: [ maintainer, author ]

  argument_groups:
    - name: Inputs
      arguments:
        - name: "--input"
          type: file
          direction: input
          required: true
          example: input.h5mu
          description: |
            The input h5mu file containing preprocessed data. 
        - name: "--modality"
          type: string
          default: "rna"
          required: false
        - name: "--model"
          type: file
          direction: input
          required: true
          example: best_model.pt
          description: |
            Path to model file.
        - name: "--model_vocab"
          type: file
          direction: input
          required: true
          example: vocab.json
          description: |
            Path to model vocabulary file.
        - name: "--model_config"
          type: file
          direction: input
          required: true
          example: args.json
          description: |
            Path to model config file.
        - name: "--input_obsm_gene_tokens"
          type: string
          default: "gene_id_tokens"
          description: |
            The key of the .obsm array containing the gene token ids
          example: values.pt
        - name: "--input_obsm_tokenized_values"
          type: string
          default: values_tokenized
          description: |
            The key of the .obsm array containing the count values of the tokenized genes
        - name: "--input_obsm_padding_mask"
          type: string
          default: padding_mask
          description: |
            The key of the .obsm array containing the padding mask.
        - name: "--input_var_gene_names"
          type: string
          description: |
            The name of the .var column containing gene names. When no gene_name_layer is provided, the .var index will be used.
        - name: "--input_obs_batch_label"
          type: string
          description: |
            The name of the adata.obs column containing the batch labels.

    - name: Outputs
      arguments:
        - name: "--output"
          type: file
          required: true
          description: |
            Path to output anndata file containing pre-processed data as well as scGPT embeddings.
          direction: output
          example: output.h5mu
        - name: "--output_compression"
          type: string
          example: "gzip"
          required: false
          choices: ["gzip", "lzf"]
          description: |
            The compression algorithm to use for the output h5mu file.
        - name: "--embedding_layer_key"
          type: string
          default: "X_scGPT"
          required: false
          description: |
            The name of the adata.obsm array to which scGPT embeddings will be written.

    - name: Arguments
      arguments:
        - name: "--pad_token"
          type: string
          default: "<pad>"
          required: false
          description: |
            The name of the layer to be padded and tokenized
        - name: "--pad_value"
          type: integer
          default: -2
          required: false
          description: |
            The value to be used for padding
        - name: "--dropout"
          type: double
          default: 0.2
          description: |
            Dropout value used for the transformer encoder layer
        - name: DSBN
          type: boolean
          default: true
          description: |
            Apply domain-specific batch normalization
        - name: "--batch_size"
          type: integer
          default: 64
          description: |
            The batch size to be used for inference

  resources:
    - type: python_script
      path: script.py
  test_resources:
    - type: python_script
      path: test.py
    - path: /resources_test/scgpt/source
    - path: /resources_test/scgpt/test_resources/Kim2020_Lung_subset.h5mu

platforms:
  - type: docker
    image: nvcr.io/nvidia/pytorch:23.09-py3
    run_args: [ "--shm-size 5000m" ]
    setup:
      - type: python
        __merge__: [ /src/base/requirements/anndata_mudata.yaml, /src/base/requirements/scanpy.yaml ]
      - type: python 
        packages:
          - scgpt==0.2.1
    test_setup:
      - type: python
        __merge__: [ /src/base/requirements/viashpy.yaml ]
  - type: nextflow
    directives:
      label: [midmem]
