functionality:
  name: "bd_rhapsody_wta"
  namespace: "mapping"
  version: "dev"
  description: |
    A wrapper for the BD Rhapsody Analysis CWL v1.9.1 pipeline.

    The CWL pipeline file is obtained by cloning 'https://bitbucket.org/CRSwDev/cwl/src/master/' and removing all objects with class 'DockerRequirement' from the YML.

    The reference_genome and transcriptome_annotation files can be downloaded from these locations:
      - Human: http://bd-rhapsody-public.s3-website-us-east-1.amazonaws.com/Rhapsody-WTA/GRCh38-PhiX-gencodev29/
      - Mouse: http://bd-rhapsody-public.s3-website-us-east-1.amazonaws.com/Rhapsody-WTA/GRCm38-PhiX-gencodevM19/
  authors:
    - name: Robrecht Cannoodt
      email: rcannood@gmail.com
      roles: [ maintainer ]
      props: { github: rcannood, orcid: "0000-0003-3641-729X" }
  arguments:
    # inputs
    - name: "--input"
      alternatives: [-i]
      type: file
      description: Path to your read files in the FASTQ.GZ format. You may specify as many R1/R2 read pairs as you want.
      required: true
      multiple: true
      multiple_sep: ':'
      example: input.fastq.gz
    - name: "--reference_genome"
      alternatives: [-r]
      type: file
      required: true
      description: "Path to STAR index as a tar.gz file."
      example: "reference_genome.tar.gz"
    - name: "--transcriptome_annotation"
      alternatives: [-t]
      type: file
      description: Path to GTF annotation file.
      required: true
      example: "transcriptome.gtf"
    - name: "--abseq_reference"
      alternatives: [-a]
      type: file
      description: Path to the AbSeq reference file in FASTA format. Only needed if BD AbSeq Ab-Oligos are used.
      multiple: true
      multiple_sep: ':'
    - name: "--supplemental_reference"
      alternatives: [-s]
      type: file
      description: Path to the supplemental reference file in FASTA format. Only needed if there are additional transgene sequences used in the experiment.
      multiple: true
      multiple_sep: ':'
    
    # outputs
    - name: "--output"
      alternatives: [-o]
      description: "Output folder. Output still needs to be processed further."
      required: true
      type: file
      direction: output
      example: output_dir/

    # putative cell calling settings
    - name: "--exact_cell_count"
      type: integer
      description: "Exact cell count - Set a specific number (>=1) of cells as putative, based on those with the highest error-corrected read count"
      example: 10000
    - name: "--disable_putative_calling"
      type: boolean_true
      description: "Disable Refined Putative Cell Calling - Determine putative cells using only the basic algorithm (minimum second derivative along the cumulative reads curve). The refined algorithm attempts to remove false positives and recover false negatives, but may not be ideal for certain complex mixtures of cell types. Does not apply if Exact Cell Count is set."
    
    # subsample settings
    - name: "--subsample"
      type: double
      description: A number >1 or fraction (0 < n < 1) to indicate the number or percentage of reads to subsample.
      example: 0.01
    - name: "--subsample_seed"
      type: integer
      description: A seed for replicating a previous subsampled run.
      example: 3445
    
    # multiplex settings
    - name: "--sample_tags_version"
      type: string
      description: "Specify if multiplexed run."
      choices: [human, hs, mouse, mm]
      example: human

    - name: "--tag_names"
      type: string
      description: |
        Tag_Names (optional) - Specify the tag number followed by '-' and the desired sample name to appear in Sample_Tag_Metrics.csv
        Do not use the special characters: &, (), [], {},  <>, ?, |
      multiple: true
      example: [4-mySample, 9-myOtherSample, 6-alsoThisSample]

    # cwl-runner settings
    - name: "--parallel"
      type: boolean
      description: "Run jobs in parallel."
      default: true
    - name: "--timestamps"
      type: boolean_true
      description: "Add timestamps to the errors, warnings, and notifications."
  resources:
    - type: python_script
      path: script.py
    - path: rhapsody_wta_1.9.1_nodocker.cwl
  tests:
    - type: bash_script
      path: run_test.sh
    - path: ../../../resources_test/bd_rhapsody_wta_test
platforms:
  - type: docker
    image: bdgenomics/rhapsody:1.9.1
    setup:
      # (1) workaround for debian buster
      # https://stackoverflow.com/questions/68802802/repository-http-security-debian-org-debian-security-buster-updates-inrelease
      # (2) Update picard (uses old Log4J). It is installed using conda, but 'conda update picard' does not work.
      # So download it manually and install
      - type: docker
        run: apt-get --allow-releaseinfo-change update && 
             apt upgrade -y &&
             conda install -y -c bioconda picard=2.27.3 ca-certificates=2022.6.15
      - type: apt
        packages: [ procps, nodejs]
      - type: python
        packages: [cwlref-runner, cwl-runner, ruamel.yaml]
  - type: nextflow
    variant: vdsl3
    directives:
      label: [ highmem, highcpu ]
