functionality:
  name: "rna_scgpt"
  namespace: "workflows/rna"
  version: "scgpt-preprocessor_build"
  authors:
  - name: "Dorien Roosen"
    roles:
    - "author"
    - "maintainer"
    info:
      role: "Contributor"
      links:
        email: "dorien@data-intuitive.com"
        github: "dorien-er"
        linkedin: "dorien-roosen"
      organizations:
      - name: "Data Intuitive"
        href: "https://www.data-intuitive.com"
        role: "Data Scientist"
  argument_groups:
  - name: "Input"
    arguments:
    - type: "string"
      name: "--id"
      description: "ID of the sample."
      info: null
      example:
      - "foo"
      required: true
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--input"
      description: "Path to the sample."
      info: null
      example:
      - "dataset.h5mu"
      must_exist: true
      create_parent: true
      required: true
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--modality"
      info: null
      default:
      - "rna"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--vocab_file"
      description: "Model vocabulary file directory.\n"
      info: null
      example:
      - "resources_test/scgpt/vocab.json"
      must_exist: true
      create_parent: true
      required: true
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--input_layer"
      description: "Input layer to start from."
      info: null
      default:
      - "X"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--gene_name_layer"
      description: "The name of the adata.var column containing gene names.\n"
      info: null
      example:
      - "gene_name"
      default:
      - "gene_name"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--n_input_bins"
      description: "The number of bins to discretize the data into. When no value\
        \ is provided, data won't be binned.\n"
      info: null
      default:
      - 51
      required: false
      min: 1
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  - name: "Outputs"
    arguments:
    - type: "file"
      name: "--output"
      description: "Destination path to the output."
      info: null
      example:
      - "output.h5mu"
      must_exist: true
      create_parent: true
      required: true
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--output_compression"
      description: "The compression algorithm to use for the output h5mu file.\n"
      info: null
      example:
      - "gzip"
      required: false
      choices:
      - "gzip"
      - "lzf"
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--binned_layer"
      description: "The name of the adata layer to write the binned data to.\n"
      info: null
      default:
      - "binned"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  - name: "Arguments"
    arguments:
    - type: "string"
      name: "--pad_token"
      description: "The padding token used in the model.\n"
      info: null
      default:
      - "<pad>"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  resources:
  - type: "nextflow_script"
    path: "main.nf"
    is_executable: true
    entrypoint: "run_wf"
  - type: "file"
    path: "./src/workflows/utils/labels.config"
    dest: "nextflow_labels.config"
  description: "Processing unimodal RNA transcriptomics data for scGPT-based applications."
  test_resources:
  - type: "file"
    path: "resources_test/scgpt/test_resources/Kim2020_Lung_subset.h5mu"
  - type: "file"
    path: "resources_test/scgpt/source/"
  - type: "file"
    path: "src/base/openpipelinetestutils"
    dest: "openpipelinetestutils"
  info: null
  status: "enabled"
  requirements:
    commands:
    - "ps"
  dependencies:
  - name: "scgpt/cross_check_genes"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/openpipeline/openpipeline/src/scgpt/cross_check_genes/config.vsh.yaml"
    configInfo:
      functionalityName: "cross_check_genes"
      git_tag: "0.2.0-1570-ge4c7703f20"
      git_remote: "https://github.com/openpipelines-bio/openpipeline"
      viash_version: "0.8.5"
      config: "/home/runner/work/openpipeline/openpipeline/src/scgpt/cross_check_genes/config.vsh.yaml"
      functionalityNamespace: "scgpt"
      output: ""
      platform: ""
      git_commit: "e4c7703f204bfe57e25edf5fed92228cb9242089"
      executable: "/nextflow/scgpt/cross_check_genes/main.nf"
    writtenPath: "/home/runner/work/openpipeline/openpipeline/target/nextflow/scgpt/cross_check_genes"
  - name: "scgpt/binning"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/openpipeline/openpipeline/src/scgpt/binning/config.vsh.yaml"
    configInfo:
      functionalityName: "binning"
      git_tag: "0.2.0-1570-ge4c7703f20"
      git_remote: "https://github.com/openpipelines-bio/openpipeline"
      viash_version: "0.8.5"
      config: "/home/runner/work/openpipeline/openpipeline/src/scgpt/binning/config.vsh.yaml"
      functionalityNamespace: "scgpt"
      output: ""
      platform: ""
      git_commit: "e4c7703f204bfe57e25edf5fed92228cb9242089"
      executable: "/nextflow/scgpt/binning/main.nf"
    writtenPath: "/home/runner/work/openpipeline/openpipeline/target/nextflow/scgpt/binning"
  set_wd_to_resources_dir: false
platforms:
- type: "nextflow"
  id: "nextflow"
  directives:
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      mem1gb: "memory = 1.GB"
      mem2gb: "memory = 2.GB"
      mem4gb: "memory = 4.GB"
      mem8gb: "memory = 8.GB"
      mem16gb: "memory = 16.GB"
      mem32gb: "memory = 32.GB"
      mem64gb: "memory = 64.GB"
      mem128gb: "memory = 128.GB"
      mem256gb: "memory = 256.GB"
      mem512gb: "memory = 512.GB"
      mem1tb: "memory = 1.TB"
      mem2tb: "memory = 2.TB"
      mem4tb: "memory = 4.TB"
      mem8tb: "memory = 8.TB"
      mem16tb: "memory = 16.TB"
      mem32tb: "memory = 32.TB"
      mem64tb: "memory = 64.TB"
      mem128tb: "memory = 128.TB"
      mem256tb: "memory = 256.TB"
      mem512tb: "memory = 512.TB"
      cpu1: "cpus = 1"
      cpu2: "cpus = 2"
      cpu5: "cpus = 5"
      cpu10: "cpus = 10"
      cpu20: "cpus = 20"
      cpu50: "cpus = 50"
      cpu100: "cpus = 100"
      cpu200: "cpus = 200"
      cpu500: "cpus = 500"
      cpu1000: "cpus = 1000"
    script:
    - "includeConfig(\"nextflow_labels.config\")"
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/openpipeline/openpipeline/src/workflows/rna/rna_scgpt/config.vsh.yaml"
  platform: "nextflow"
  output: "/home/runner/work/openpipeline/openpipeline/target/nextflow/workflows/rna/rna_scgpt"
  executable: "/home/runner/work/openpipeline/openpipeline/target/nextflow/workflows/rna/rna_scgpt/main.nf"
  viash_version: "0.8.5"
  git_commit: "e4c7703f204bfe57e25edf5fed92228cb9242089"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
  git_tag: "0.2.0-1570-ge4c7703f20"
