functionality:
  name: integration_qc
  namespace: "workflows/qc"
  description: |
    Workflow to add integration qc metrics to a MuData and generate an integration qc output report.
      
  authors:
    - __merge__: /src/authors/dorien_roosen.yaml
      roles: [ author, maintainer ]
  argument_groups:
    - name: Inputs
      arguments:
        - name: "--input"
          type: file
          description: Input h5mu file
          direction: input
          required: true
          example: input.h5mu
        - name: "--modality"
          type: string
          default: "rna"
        - name: "--var_gene_names"
          type: string
          required: false
          description: |
            The name of the adata var column containing gene names. When no gene_name_layer is provided, the var index will be used.
        - name: "--obsm_embeddings"
          type: string
          required: true
          example: "X_scGPT"
          description: |
            The name of the adata.obsm array containing scGPT cell embeddings.
        - name: "--obs_batch_label"
          type: string
          example: "sample"
          required: true
          description: |
            The name of the adata obs column containing the batch labels.
        - name: "--obs_cell_label"
          type: string
          example: "cell_type"
          required: true
          description: |
            The name of the adata obs column containing the cell type labels.
        - name: "--obs_cluster"
          type: string
          example: "cluster"
          required: true
          description: |
            The name of the adata obs column containing the cluster labels.
        - name: "--obsp_neighbor_connectivities"
          type: string
          example: "connectivities"
          required: true
          description: |
            The name of the adata obsp object containing the neighbor connectivities.
        - name: "--uns_neighbors"
          type: string
          example: "neighbors"
          required: true
          description:
            The name of the adata uns object containing the neighbors information.
        - name: "--obsm_umap"
          type: string
          example: "X_scGPT_umap"
          required: true
          description: "The obsm slot containing UMAP embeddings."

    - name: Outputs
      arguments:
        - name: "--output_report"
          type: file
          required: true
          description: Output .md file.
          direction: output
          example: output.md
        - name: "--output_umap_batch"
          type: file
          direction: output
          example: umap_batch.png
          required: true
          description: |
            Path to png image containing the UMAP visualization with batch labels
        - name: "--output_umap_label"
          type: file
          example: umap_label.png
          required: true
          direction: output
          description: |
            Path to png image containing the UMAP visualization with cell type labels
        - name: "--output_metrics"
          type: file
          direction: output
          description: |
            Path to json containing the calculated integration metrics.
          example: metrics.json
          required: false
        - name: "--output_compression"
          type: string
          description: The compression format to be used on the output h5mu object.
          choices: ["gzip", "lzf"]
          required: false
          example: "gzip"
  dependencies:
    - name: qc/integration_metrics
    - name: qc/integration_report
  resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: run_wf
   
platforms:
  - type: nextflow
