functionality:
  name: merge
  namespace: "integrate"
  version: "dev"
  description: |
    Combine one or more single-modality .h5mu files together into one .h5mu file.
  authors:
    - name: Dries Schaumont
      email: Dschaumo@its.jnj.com
      roles: [ maintainer ]
  arguments:
    - name: "--input"
      alternatives: ["-i"]
      type: file
      multiple: true
      multiple_sep: ','
      description: Paths to the single-modality .h5mu files that need to be combined
      required: true
      default: sample_paths
    - name: "--output"
      description: Path to the output file.
      alternatives: ["-o"]
      type: file
      direction: output
      default: "output.h5mu"
    - name: "--compression"
      type: string
      description: The compression format to be used on the final h5mu object.
      default: "gzip"
  resources:
    - type: python_script
      path: ./script.py
  tests:
    - type: python_script
      path: test.py
    - path: ../../../resources_test/merge/pbmc_1k_protein_v3_filtered_feature_bc_matrix_rna.h5mu
    - path: ../../../resources_test/merge/pbmc_1k_protein_v3_filtered_feature_bc_matrix_prot.h5mu
platforms:
  - type: docker
    image: python:3.10
    python:
      packages:
        - anndata<0.8
        - muon
  - type: native
  - type: nextflow
    variant: vdsl3