name: duplicate_obs
namespace: "metadata"
description: |
  Make a copy of an existing .obs column to another .obs column.
authors:
  - __merge__: /src/authors/dorien_roosen.yaml
    roles: [ author ]
argument_groups:
  - name: "MuData Input"
    arguments:
      - name: "--input"
        alternatives: ["-i"]
        type: file
        description: Input h5mu file
        direction: input
        required: true
        example: input.h5mu
      - name: "--modality"
        type: string
        default: "rna"
        required: false
      - name: "--input_obs_key"
        type: string
        description: .obs column to be copied. If no key is provided, the .var index will be copied.
        required: false
  - name: "Arguments"
    arguments:
      - name: "--disable_raise_on_identical_keys"
        type: boolean_true
        description: If provided, the function will not raise an error if the --output_obs_key already exists in the dataset.
  - name: "MuData Output"
    arguments:
      - name: "--output"
        alternatives: ["-o"]
        type: file
        description: Output h5mu file.
        direction: output
        required: true
        example: output.h5mu
      - name: "--output_obs_key"
        type: string
        description: .obs column where the copied --input_obs_key will be stored.
        required: true
      - name: "--output_compression"
        type: string
        description: The compression format to be used on the output h5mu object.
        choices: ["gzip", "lzf"]
        required: false
        example: "gzip"
resources:
  - type: python_script
    path: script.py
  - path: /src/utils/setup_logger.py
test_resources:
  - type: python_script
    path: test.py

engines:
- type: docker
  image: python:3.12-slim
  setup:
    - type: apt
      packages: 
        - procps
    - type: python
      __merge__: /src/base/requirements/anndata_mudata.yaml
  __merge__: [/src/base/requirements/python_test_setup.yaml, .]

runners:
- type: executable
- type: nextflow
  directives:
    label: [ singlecpu, lowmem ]
