# Outputs
# output: "$id.$key.output.h5mu"
# output_obs_predictions: ["foo"]
# output_obs_probability: ["foo"]
# output_compression: "gzip"

# Query input
id: # please fill in - example: "foo"
input: # please fill in - example: "input.h5mu"
modality: "rna"
# input_layer: "foo"
# var_gene_names_query: "foo"
# obs_batch_label: "foo"

# Reference input
reference: # please fill in - example: "reference.h5mu"
# var_gene_names_reference: "foo"
obs_reference_targets: # please fill in - example: ["ann_level_1", "ann_level_2", "ann_level_3", "ann_level_4", "ann_level_5", "ann_finest_level"]

# Model input
model: # please fill in - example: "best_model.pt"
model_config: # please fill in - example: "args.json"
model_vocab: # please fill in - example: "vocab.json"
finetuned_checkpoints_key: # please fill in - example: "model_state_dict"

# Padding arguments
pad_token: "<pad>"
pad_value: -2

# HVG subset arguments
n_hvg: 1200

# Tokenization arguments
# max_seq_len: 123

# Binning arguments
n_input_bins: 51
# seed: 123

# scGPT integration options
obsm_integrated: "X_scGPT"
dsbn: true
batch_size: 64

# Nextflow input-output arguments
publish_dir: # please fill in - example: "output/"
# param_list: "my_params.yaml"
