functionality:
  name: "rna_multisample"
  namespace: "workflows/rna"
  version: "main_build"
  authors:
  - name: "Dries De Maeyer"
    roles:
    - "author"
    info:
      role: "Core Team Member"
      links:
        email: "ddemaeyer@gmail.com"
        github: "ddemaeyer"
        linkedin: "dries-de-maeyer-b46a814"
      organizations:
      - name: "Janssen Pharmaceuticals"
        href: "https://www.janssen.com"
        role: "Principal Scientist"
  - name: "Robrecht Cannoodt"
    roles:
    - "author"
    - "maintainer"
    info:
      role: "Core Team Member"
      links:
        email: "robrecht@data-intuitive.com"
        github: "rcannood"
        orcid: "0000-0003-3641-729X"
        linkedin: "robrechtcannoodt"
      organizations:
      - name: "Data Intuitive"
        href: "https://www.data-intuitive.com"
        role: "Data Science Engineer"
      - name: "Open Problems"
        href: "https://openproblems.bio"
        role: "Core Member"
  - name: "Dries Schaumont"
    roles:
    - "author"
    info:
      role: "Core Team Member"
      links:
        email: "dries@data-intuitive.com"
        github: "DriesSchaumont"
        orcid: "0000-0002-4389-0440"
        linkedin: "dries-schaumont"
      organizations:
      - name: "Data Intuitive"
        href: "https://www.data-intuitive.com"
        role: "Data Scientist"
  argument_groups:
  - name: "Inputs"
    arguments:
    - type: "string"
      name: "--id"
      description: "ID of the concatenated file"
      info: null
      example:
      - "concatenated"
      required: true
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--input"
      description: "Path to the samples."
      info: null
      example:
      - "dataset.h5mu"
      must_exist: true
      create_parent: true
      required: true
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--modality"
      description: "Modality to process."
      info: null
      default:
      - "rna"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  - name: "Output"
    arguments:
    - type: "file"
      name: "--output"
      description: "Destination path to the output."
      info: null
      example:
      - "output.h5mu"
      must_exist: true
      create_parent: true
      required: true
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  - name: "Filtering highly variable genes"
    arguments:
    - type: "string"
      name: "--filter_with_hvg_var_output"
      description: "In which .var slot to store a boolean array corresponding to the\
        \ highly variable genes."
      info: null
      default:
      - "filter_with_hvg"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--filter_with_hvg_obs_batch_key"
      description: "If specified, highly-variable genes are selected within each batch\
        \ separately and merged. This simple \nprocess avoids the selection of batch-specific\
        \ genes and acts as a lightweight batch correction method. \nFor all flavors,\
        \ genes are first sorted by how many batches they are a HVG. For dispersion-based\
        \ flavors \nties are broken by normalized dispersion. If flavor = 'seurat_v3',\
        \ ties are broken by the median (across\nbatches) rank based on within-batch\
        \ normalized variance.\n"
      info: null
      default:
      - "sample_id"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--filter_with_hvg_flavor"
      description: "Choose the flavor for identifying highly variable genes. For the\
        \ dispersion based methods\nin their default workflows, Seurat passes the\
        \ cutoffs whereas Cell Ranger passes n_top_genes.\n"
      info: null
      default:
      - "seurat"
      required: false
      choices:
      - "seurat"
      - "cell_ranger"
      - "seurat_v3"
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--filter_with_hvg_n_top_genes"
      description: "Number of highly-variable genes to keep. Mandatory if filter_with_hvg_flavor\
        \ is set to 'seurat_v3'."
      info: null
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  - name: "QC metrics calculation options"
    arguments:
    - type: "string"
      name: "--var_qc_metrics"
      description: "Keys to select a boolean (containing only True or False) column\
        \ from .var.\nFor each cell, calculate the proportion of total values for\
        \ genes which are labeled 'True', \ncompared to the total sum of the values\
        \ for all genes.\n"
      info: null
      example:
      - "ercc,highly_variable"
      default:
      - "filter_with_hvg"
      required: false
      direction: "input"
      multiple: true
      multiple_sep: ","
      dest: "par"
    - type: "integer"
      name: "--top_n_vars"
      description: "Number of top vars to be used to calculate cumulative proportions.\n\
        If not specified, proportions are not calculated. `--top_n_vars 20,50` finds\n\
        cumulative proportion to the 20th and 50th most expressed vars.\n"
      info: null
      default:
      - 50
      - 100
      - 200
      - 500
      required: false
      direction: "input"
      multiple: true
      multiple_sep: ","
      dest: "par"
    - type: "string"
      name: "--output_obs_num_nonzero_vars"
      description: "Name of column in .obs describing, for each observation, the number\
        \ of stored values\n(including explicit zeroes). In other words, the name\
        \ of the column that counts\nfor each row the number of columns that contain\
        \ data.\n"
      info: null
      default:
      - "num_nonzero_vars"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--output_obs_total_counts_vars"
      description: "Name of the column for .obs describing, for each observation (row),\n\
        the sum of the stored values in the columns.\n"
      info: null
      default:
      - "total_counts"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--output_var_num_nonzero_obs"
      description: "Name of column describing, for each feature, the number of stored\
        \ values\n(including explicit zeroes). In other words, the name of the column\
        \ that counts\nfor each column the number of rows that contain data.\n"
      info: null
      default:
      - "num_nonzero_obs"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--output_var_total_counts_obs"
      description: "Name of the column in .var describing, for each feature (column),\n\
        the sum of the stored values in the rows.\n"
      info: null
      default:
      - "total_counts"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--output_var_obs_mean"
      description: "Name of the column in .obs providing the mean of the values in\
        \ each row.\n"
      info: null
      default:
      - "obs_mean"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--output_var_pct_dropout"
      description: "Name of the column in .obs providing for each feature the percentage\
        \ of\nobservations the feature does not appear on (i.e. is missing). Same\
        \ as `--num_nonzero_obs`\nbut percentage based.\n"
      info: null
      default:
      - "pct_dropout"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  resources:
  - type: "nextflow_script"
    path: "main.nf"
    is_executable: true
    entrypoint: "run_wf"
  description: "Processing unimodal multi-sample RNA transcriptomics data."
  test_resources:
  - type: "nextflow_script"
    path: "test.nf"
    is_executable: true
    entrypoint: "test_wf"
  - type: "file"
    path: "resources_test/concat_test_data"
  info:
    image: "/images/concepts/fig_workflow_multiomics_rna_multisample.svg"
  status: "enabled"
  requirements:
    commands:
    - "ps"
  dependencies:
  - name: "transform/normalize_total"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/openpipeline/openpipeline/src/transform/normalize_total/config.vsh.yaml"
    configInfo:
      functionalityName: "normalize_total"
      git_tag: ""
      git_remote: "https://github.com/openpipelines-bio/openpipeline"
      viash_version: "0.8.3"
      config: "/home/runner/work/openpipeline/openpipeline/src/transform/normalize_total/config.vsh.yaml"
      functionalityNamespace: "transform"
      output: ""
      platform: ""
      git_commit: "da5e86067ceace271f8356befbd5b47a2237436b"
      executable: "/nextflow/transform/normalize_total/main.nf"
    writtenPath: "/home/runner/work/openpipeline/openpipeline/target/nextflow/transform/normalize_total"
  - name: "transform/log1p"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/openpipeline/openpipeline/src/transform/log1p/config.vsh.yaml"
    configInfo:
      functionalityName: "log1p"
      git_tag: ""
      git_remote: "https://github.com/openpipelines-bio/openpipeline"
      viash_version: "0.8.3"
      config: "/home/runner/work/openpipeline/openpipeline/src/transform/log1p/config.vsh.yaml"
      functionalityNamespace: "transform"
      output: ""
      platform: ""
      git_commit: "da5e86067ceace271f8356befbd5b47a2237436b"
      executable: "/nextflow/transform/log1p/main.nf"
    writtenPath: "/home/runner/work/openpipeline/openpipeline/target/nextflow/transform/log1p"
  - name: "filter/filter_with_hvg"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/openpipeline/openpipeline/src/filter/filter_with_hvg/config.vsh.yaml"
    configInfo:
      functionalityName: "filter_with_hvg"
      git_tag: ""
      git_remote: "https://github.com/openpipelines-bio/openpipeline"
      viash_version: "0.8.3"
      config: "/home/runner/work/openpipeline/openpipeline/src/filter/filter_with_hvg/config.vsh.yaml"
      functionalityNamespace: "filter"
      output: ""
      platform: ""
      git_commit: "da5e86067ceace271f8356befbd5b47a2237436b"
      executable: "/nextflow/filter/filter_with_hvg/main.nf"
    writtenPath: "/home/runner/work/openpipeline/openpipeline/target/nextflow/filter/filter_with_hvg"
  - name: "workflows/qc/qc"
    alias: "rna_qc"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/openpipeline/openpipeline/src/workflows/qc/qc/config.vsh.yaml"
    configInfo:
      functionalityName: "qc"
      git_tag: ""
      git_remote: "https://github.com/openpipelines-bio/openpipeline"
      viash_version: "0.8.3"
      config: "/home/runner/work/openpipeline/openpipeline/src/workflows/qc/qc/config.vsh.yaml"
      functionalityNamespace: "workflows/qc"
      output: ""
      platform: ""
      git_commit: "da5e86067ceace271f8356befbd5b47a2237436b"
      executable: "/nextflow/workflows/qc/qc/main.nf"
    writtenPath: "/home/runner/work/openpipeline/openpipeline/target/nextflow/workflows/qc/qc"
  - name: "transform/delete_layer"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/openpipeline/openpipeline/src/transform/delete_layer/config.vsh.yaml"
    configInfo:
      functionalityName: "delete_layer"
      git_tag: ""
      git_remote: "https://github.com/openpipelines-bio/openpipeline"
      viash_version: "0.8.3"
      config: "/home/runner/work/openpipeline/openpipeline/src/transform/delete_layer/config.vsh.yaml"
      functionalityNamespace: "transform"
      output: ""
      platform: ""
      git_commit: "da5e86067ceace271f8356befbd5b47a2237436b"
      executable: "/nextflow/transform/delete_layer/main.nf"
    writtenPath: "/home/runner/work/openpipeline/openpipeline/target/nextflow/transform/delete_layer"
  - name: "metadata/add_id"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/openpipeline/openpipeline/src/metadata/add_id/config.vsh.yaml"
    configInfo:
      functionalityName: "add_id"
      git_tag: ""
      git_remote: "https://github.com/openpipelines-bio/openpipeline"
      viash_version: "0.8.3"
      config: "/home/runner/work/openpipeline/openpipeline/src/metadata/add_id/config.vsh.yaml"
      functionalityNamespace: "metadata"
      output: ""
      platform: ""
      git_commit: "da5e86067ceace271f8356befbd5b47a2237436b"
      executable: "/nextflow/metadata/add_id/main.nf"
    writtenPath: "/home/runner/work/openpipeline/openpipeline/target/nextflow/metadata/add_id"
  set_wd_to_resources_dir: false
platforms:
- type: "nextflow"
  id: "nextflow"
  directives:
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      mem1gb: "memory = 1.GB"
      mem2gb: "memory = 2.GB"
      mem4gb: "memory = 4.GB"
      mem8gb: "memory = 8.GB"
      mem16gb: "memory = 16.GB"
      mem32gb: "memory = 32.GB"
      mem64gb: "memory = 64.GB"
      mem128gb: "memory = 128.GB"
      mem256gb: "memory = 256.GB"
      mem512gb: "memory = 512.GB"
      mem1tb: "memory = 1.TB"
      mem2tb: "memory = 2.TB"
      mem4tb: "memory = 4.TB"
      mem8tb: "memory = 8.TB"
      mem16tb: "memory = 16.TB"
      mem32tb: "memory = 32.TB"
      mem64tb: "memory = 64.TB"
      mem128tb: "memory = 128.TB"
      mem256tb: "memory = 256.TB"
      mem512tb: "memory = 512.TB"
      cpu1: "cpus = 1"
      cpu2: "cpus = 2"
      cpu5: "cpus = 5"
      cpu10: "cpus = 10"
      cpu20: "cpus = 20"
      cpu50: "cpus = 50"
      cpu100: "cpus = 100"
      cpu200: "cpus = 200"
      cpu500: "cpus = 500"
      cpu1000: "cpus = 1000"
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/openpipeline/openpipeline/src/workflows/rna/rna_multisample/config.vsh.yaml"
  platform: "nextflow"
  output: "/home/runner/work/openpipeline/openpipeline/target/nextflow/workflows/rna/rna_multisample"
  executable: "/home/runner/work/openpipeline/openpipeline/target/nextflow/workflows/rna/rna_multisample/main.nf"
  viash_version: "0.8.3"
  git_commit: "da5e86067ceace271f8356befbd5b47a2237436b"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
