functionality:
  name: "scgpt_cell_type_annotation"
  namespace: "workflows/annotation"
  description: "scGPT cell type annotation through decoding of cell embeddings."
  authors:
    - __merge__: /src/authors/jakub_majercik.yaml
      roles: [ author, maintainer ]
    - __merge__: /src/authors/dorien_roosen.yaml
      roles: [ author, maintainer ]
  argument_groups:
    - name: "Input"
      arguments:
        - name: "--id"
          required: true
          type: string
          description: ID of the sample.
          example: foo
        - name: "--input"
          type: file
          required: true
          description: Path to the sample.
          example: dataset.h5mu
        - name: "--input_layer"
          type: string
          description: |
            The name of the adata layer containing (pre-processed) counts to use for the input. adata.X will be used if no layer is provided.
        - name: "--modality"
          type: string
          default: "rna"
          required: false
        - name: "--model_vocab"
          type: file
          direction: input
          required: true
          example: resources_test/scgpt/vocab.json
          description: |
            Model vocabulary file directory.
        - name: "--model"
          type: file
          required: true
          example: "resources_test/scgpt/source/best_model.pt"
          description: |
            The model file.
        - name: "--model_config"
          type: file
          required: true
          example: "resources_test/scgpt/source/args.json"
          description: |
            The model configuration file. 

    - name: "Outputs"
      arguments:
        - name: "--output"
          type: file
          required: true
          direction: output
          description: Destination path to the output.
          example: output.h5mu
        - name: "--output_compression"
          type: string
          example: "gzip"
          required: false
          choices: ["gzip", "lzf"]
          description: |
            The compression algorithm to use for the output h5mu file.

    - name: "Arguments"
      arguments:
        - name: "--pad_token"
          type: string
          default: "<pad>"
          required: false
          description: |
            The padding token used in the model.
        - name: "--pad_value"
          type: integer
          default: -2
          required: false
          description: |
            The value of the padding token.
        - name: "--max_seq_len"
          type: integer
          required: false
          description: |
            The maximum sequence length of the tokenized data.
        - name: "--gene_name_layer"
          type: string
          example: "gene_name"
          required: false
          default: "gene_name"
          description: |
            The name of the adata.var column containing gene names.
        - name: "--batch_id_layer"  
          type: string
          default: "batch_id"
          description: |
            The name of the adata.obs column to write categorical batch ids to.
        - name: "--n_cls"
          type: integer
          default: 8
          required: false
          description: |
            The number of classes.
        - name: "--n_input_bins"
          type: integer
          default: 51
          required: false
          description: |
            The number of input bins.
        - name: "--batch_size"
          type: integer
          default: 64
          required: false
          description: |
            The batch size. 
        - name: "--predicted_cell_type_id"
          type: string
          default: "predicted_cell_type"
          required: false
          description: |
            The name of the adata.obs column to write predicted cell types to.
        - name: "--DSBN"
          type: boolean
          default: true
          required: false
          description: |
            Whether to use domain-specific batch normalization.
        - name: "--n_hvg"
          type: integer
          default: 1200
          description: |
            Number of highly variable genes to subset for.
        - name: "--var_gene_names"
          type: string
          required: false
          description: |
            The name of the adata.var column containing gene names. When no gene_name_layer is provided, the .var index will be used.
        - name: "--binned_layer"
          type: string
          default: "binned"
          description: |
            The name of the adata layer to write the binned data to.
        - name: "--input_obs_batch_label"
          type: string
          default: "sample"
          description: |
            The name of the adata.obs column containing the batch labels.

  resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: run_wf
    - type: file
      path: /src/workflows/utils/
  dependencies:
    - name: scgpt/pad_tokenize
    - name: scgpt/cell_type_inference
    - name: scgpt/cross_check_genes
    - name: scgpt/binning
    - name: feature_annotation/highly_variable_features_scanpy
    - name: filter/do_filter
  test_resources:
    - type: nextflow_script
      path: test.nf
      entrypoint: test_wf
    - type: nextflow_script
      path: test.nf
      entrypoint: test_wf2
    - path: /resources_test/scgpt
platforms:
  - type: nextflow