# Outputs
# output: "$id.$key.output.h5mu"
# output_compression: "gzip"
obs_predicted_cell_type: "predicted_cell_type"

# Arguments
pad_token: "<pad>"
pad_value: -2
# max_seq_len: 123
gene_name_layer: "gene_name"
batch_id_layer: "batch_id"
n_cls: 8
n_input_bins: 51
batch_size: 64
dsbn: true
n_hvg: 1200
# var_gene_names: "foo"
binned_layer: "binned"
obs_batch_label: "sample"
# seed: 123

# Input
id: # please fill in - example: "foo"
input: # please fill in - example: "dataset.h5mu"
# input_layer: "foo"
modality: "rna"
model_vocab: # please fill in - example: "resources_test/scgpt/vocab.json"
model: # please fill in - example: "resources_test/scgpt/source/best_model.pt"
model_config: # please fill in - example: "resources_test/scgpt/source/args.json"

# Nextflow input-output arguments
publish_dir: # please fill in - example: "output/"
# param_list: "my_params.yaml"
