functionality:
  name: "fastqc"
  namespace: "qc"
  version: 0.0.1
  description: |
    Fastqc component, please see https://www.bioinformatics.babraham.ac.uk/projects/fastqc/. This component can take one or more files (by means of shell globbing) or a complete directory.
  arguments:
    - name: "--mode"
      alternatives: [ "-m" ]
      type: string
      choices: [ files, dir ]
      default: files
      description: The mode in which the component works. Can be either files or dir.
    - name: "--input"
      alternatives: [ "-i" ]
      type: file
      required: true
      description: Directory containing input fastq files.
      example: fastq_dir/
    - name: "--output"
      alternatives: [ "-o" ]
      type: file
      direction: output
      required: true
      description: Output directory to write reports to.
      example: qc/
  resources:
    - type: bash_script
      path: script.sh
  test_resources:
    - type: bash_script
      path: test.sh
    - path: ../../../resources_test/cellranger_tiny_fastq/cellranger_tiny_fastq
platforms:
  - type: docker
    image: ubuntu:22.04
    setup:
      - type: docker
        run: apt-get update
      - type: apt
        packages: [ bash, wget, unzip, libfindbin-libs-perl, default-jre ]
      - type: docker
        run:
          - mkdir -p /opt
          - wget http://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.9.zip -O /opt/fastqc.zip
          - cd /opt && unzip fastqc.zip && ln -s /opt/FastQC/fastqc /usr/bin/fastqc
          - chmod 755 /usr/bin/fastqc
  - type: nextflow
    variant: vdsl3
