functionality:
  name: integration_report
  namespace: "qc"
  description: |
    Generates a .md file containing an overview of integration metrics (calculated in qc/integration_metrics) and umap visualizations.
      
  authors:
    - __merge__: /src/authors/dorien_roosen.yaml
      roles: [ author ]
  argument_groups:
    - name: Inputs
      arguments:
        - name: "--input"
          type: file
          description: Input h5mu file
          direction: input
          required: true
          example: input.h5mu
        - name: "--modality"
          type: string
          default: "rna"
        - name: "--var_gene_names"
          type: string
          required: false
          description: |
            The name of the adata var column containing gene names. When no gene_name_layer is provided, the var index will be used.
        - name: "--obs_batch_label"
          type: string
          example: "sample"
          required: true
          description: |
            The name of the adata obs column containing the batch labels.
        - name: "--obs_cell_label"
          type: string
          example: "cell_type"
          required: true
          description: |
            The name of the adata obs column containing the cell type labels.
        - name: "--uns_neighbors"
          type: string
          example: "neighbors"
          required: true
          description:
            The name of the adata uns object containing the neighbors information.
        - name: "--obsm_umap"
          type: string
          example: "X_scGPT_umap"
          required: true
          description: "The obsm slot containing UMAP embeddings."

    - name: Outputs
      arguments:
        - name: "--output"
          type: file
          required: true
          description: Output .md file.
          direction: output
          example: output.md
        - name: "--output_umap_batch"
          type: file
          direction: output
          example: umap_batch.png
          required: true
          description: |
            Path to png image containing the UMAP visualization with batch labels
        - name: "--output_umap_label"
          type: file
          example: umap_label.png
          required: true
          direction: output
          description: |
            Path to png image containing the UMAP visualization with cell type labels
        - name: "--output_metrics"
          type: file
          direction: output
          description: |
            Path to json containing the calculated integration metrics.
          example: metrics.json
          required: false

  resources:
    - type: python_script
      path: script.py
    - path: report_template.md
   
platforms:
  - type: docker
    image: python:3.11
    setup:
      - type: apt
        packages: 
          - procps
          - libhdf5-dev
          - gfortran
          - cmake
          - libopenblas-dev
      - type: python
        __merge__: [ /src/base/requirements/anndata_mudata.yaml, /src/base/requirements/scanpy.yaml ]

    test_setup:
      - type: python
        __merge__: [ /src/base/requirements/viashpy.yaml, .]
  - type: nextflow
    directives:
      label: [singlecpu, lowmem]