functionality:
  name: split_modalities
  namespace: "split"
  version: "dev"
  description: |
    Split the modalities from a single .h5mu multimodal sample into seperate .h5mu files. 
  authors:
    - name: Dries Schaumont
      email: dries@data-intuitive.com
      roles: [ maintainer ]
  arguments:
    - name: "--input"
      alternatives: ["-i"]
      type: file
      description: Path to a single .hm5u file
      required: true
      default: sample_path
    - name: "--output"
      alternatives: ["-o"]
      type: file
      required: true
      direction: output
    - name: "--compression"
      type: string
      description: The compression format to be used on the final h5mu object.
      default: "gzip"
  resources:
    - type: python_script
      path: ./script.py
  test_resources:
    - type: python_script
      path: test.py
    - path: ../../../resources_test/pbmc_1k_protein_v3/pbmc_1k_protein_v3_filtered_feature_bc_matrix.h5mu
platforms:
  - type: docker
    image: python:3.10
    python:
      packages:
        - muon
        - mudata~=0.2.0
        - anndata~=0.8.0
  - type: native
  - type: nextflow
    variant: vdsl3
