functionality:
  name: "cellranger_atac_mkfastq"
  namespace: "demux"
  version: "main_build"
  authors:
  - name: "Vladimir Shitov"
    roles:
    - "author"
    info:
      role: "Contributor"
      links:
        email: "vladimir.shitov@helmholtz-muenchen.de"
        github: "vladimirshitov"
        orcid: "0000-0002-1960-8812"
        linkedin: "vladimir-shitov-9a659513b"
      organizations:
      - name: "Helmholtz Munich"
        href: "https://www.helmholtz-munich.de"
        role: "PhD Candidate"
  arguments:
  - type: "file"
    name: "--input"
    description: "Path of Illumina BCL run folder."
    info: null
    example:
    - "/path/to/bcl"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--csv"
    description: "The path to the simple layout sample sheet."
    info: null
    example:
    - "SampleSheet.csv"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "string"
    name: "--lanes"
    description: "bcl2fastq option. Semicolon-delimited series of lanes to demultiplex.\
      \ Use this if you have a sample sheet for an entire flow cell but only want\
      \ to generate a few lanes for further 10x Genomics analysis."
    info: null
    example:
    - "1,3"
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ";"
    dest: "par"
  - type: "string"
    name: "--use_bases_mask"
    description: "bcl2fastq option. Use to clip extra bases off a read if you ran\
      \ extra cycles for QC."
    info: null
    example:
    - "y50n,I6n,Y50n"
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ";"
    dest: "par"
  - type: "boolean_true"
    name: "--delete_undetermined"
    description: "bcl2fastq option. Delete the Undetermined FASTQs generated by bcl2fastq.\
      \ Useful if you are demultiplexing a small number of samples from a large flow\
      \ cell."
    info: null
    direction: "input"
    dest: "par"
  - type: "integer"
    name: "--barcode_mismatches"
    description: "bcl2fastq option. Use this option to change the number of allowed\
      \ mismatches per index adapter (0, 1, 2)."
    info: null
    default:
    - 1
    required: false
    min: 0
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output"
    description: "The folder to store the demux results"
    info: null
    example:
    - "/path/to/output"
    default:
    - "fastqs"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--reports"
    description: "Reports directory"
    info: null
    example:
    - "reports_dir"
    must_exist: true
    create_parent: true
    required: false
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  resources:
  - type: "bash_script"
    path: "script.sh"
    is_executable: true
  - type: "file"
    path: "src/utils/setup_logger.py"
  - type: "file"
    path: "./src/workflows/utils/labels.config"
    dest: "nextflow_labels.config"
  description: "Demultiplex raw sequencing data for ATAC experiments"
  usage: "cellranger_atac_mkfastq \\\n  --input /path/to/bcl \\\n  --csv simple_layout_sample_sheet.csv\
    \ \\\n  --output /path/to/output\n"
  test_resources:
  - type: "python_script"
    path: "test.py"
    is_executable: true
  - type: "file"
    path: "resources_test/cellranger_atac_tiny_bcl"
  - type: "file"
    path: "src/base/openpipelinetestutils"
    dest: "openpipelinetestutils"
  info: null
  status: "enabled"
  requirements:
    commands:
    - "ps"
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "ghcr.io/data-intuitive/cellranger_atac:2.1"
  target_organization: "openpipelines-bio"
  target_registry: "ghcr.io"
  target_tag: "main_build"
  namespace_separator: "/"
  resolve_volume: "Automatic"
  chown: true
  setup_strategy: "ifneedbepullelsecachedbuild"
  target_image_source: "https://github.com/openpipelines-bio/openpipeline"
  setup:
  - type: "docker"
    run:
    - "DEBIAN_FRONTEND=noninteractive apt update \\\n&& apt upgrade -y && apt install\
      \ -y procps && rm -rf /var/lib/apt/lists/*\n"
  test_setup:
  - type: "python"
    user: false
    packages:
    - "viashpy==0.6.0"
    upgrade: true
  entrypoint: []
  cmd: null
- type: "nextflow"
  id: "nextflow"
  directives:
    label:
    - "highmem"
    - "highcpu"
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      mem1gb: "memory = 1.GB"
      mem2gb: "memory = 2.GB"
      mem4gb: "memory = 4.GB"
      mem8gb: "memory = 8.GB"
      mem16gb: "memory = 16.GB"
      mem32gb: "memory = 32.GB"
      mem64gb: "memory = 64.GB"
      mem128gb: "memory = 128.GB"
      mem256gb: "memory = 256.GB"
      mem512gb: "memory = 512.GB"
      mem1tb: "memory = 1.TB"
      mem2tb: "memory = 2.TB"
      mem4tb: "memory = 4.TB"
      mem8tb: "memory = 8.TB"
      mem16tb: "memory = 16.TB"
      mem32tb: "memory = 32.TB"
      mem64tb: "memory = 64.TB"
      mem128tb: "memory = 128.TB"
      mem256tb: "memory = 256.TB"
      mem512tb: "memory = 512.TB"
      cpu1: "cpus = 1"
      cpu2: "cpus = 2"
      cpu5: "cpus = 5"
      cpu10: "cpus = 10"
      cpu20: "cpus = 20"
      cpu50: "cpus = 50"
      cpu100: "cpus = 100"
      cpu200: "cpus = 200"
      cpu500: "cpus = 500"
      cpu1000: "cpus = 1000"
    script:
    - "includeConfig(\"nextflow_labels.config\")"
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/openpipeline/openpipeline/src/demux/cellranger_atac_mkfastq/config.vsh.yaml"
  platform: "docker"
  output: "/home/runner/work/openpipeline/openpipeline/target/docker/demux/cellranger_atac_mkfastq"
  executable: "/home/runner/work/openpipeline/openpipeline/target/docker/demux/cellranger_atac_mkfastq/cellranger_atac_mkfastq"
  viash_version: "0.8.6"
  git_commit: "bb320cf9331bacda9e42f00c09f1340774cdc2a6"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
