name: run_cellxgene
namespace: interactive
description: ""
arguments:
- name: "--input"
  alternatives: ["-i"]
  type: file
  description: Directory to mount
  direction: input
  default: ./
- name: "--port"
  alternatives: ["-p"]
  type: string
  description: Port to use
  default: "5005"
resources:
  - type: bash_script
    path: script.sh
# test_resources: 
#   - type: bash_script
#     path: run_test.sh
engines:
  - type: docker
    image: ubuntu:focal
    setup:
      - type: docker
        run: apt update && apt upgrade -y
      - type: apt
        packages:
          - build-essential libxml2-dev python3-dev python3-pip zlib1g-dev python3-requests python3-aiohttp python-is-python3
      - type: python
        packages:
          - cellxgene
runners:
  - type: executable
    run_args: "$( echo $VIASH_PAR_PORT | sed 's/..*/-p &:&/' )"
  - type: nextflow
