functionality:
  name: "full_pipeline"
  namespace: "multiomics"
  description: "A pipeline to analyse multiple multiomics samples."
  authors:
    - __merge__: ../../../src/authors/dries_schaumont.yaml
      roles: [ author, maintainer ]
  argument_groups:
    - name: Inputs
      arguments:
        - name: "--id"
          required: true
          type: string
          description: ID of the sample.
          example: foo
        - name: "--input"
          alternatives: [-i]
          description: Path to the sample.
          required: true
          example: input.h5mu
          type: file
        - name: "--obs_covariates"
          type: string
          description: "The .obs field(s) that define the covariate(s) to regress out."
          example: ["batch", "sample"]
          default: ["sample_id"]
          multiple: true
          required: false
        - name: "--filter_with_hvg_var_output"
          required: false
          type: string
          default: "filter_with_hvg"
          description: In which .var slot to store a boolean array corresponding to the highly variable genes.
  resources:
    - type: nextflow_script
      path: main.nf
  test_resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: test_wf
