functionality:
  name: binning
  namespace: "scgpt"
  description: |
   Conversion of (pre-processed) expression count data into relative values (bins) to address scale differences across sequencing batches.
  authors:
    - __merge__: /src/authors/dorien_roosen.yaml
      roles: [ maintainer, author ]

  argument_groups:
    - name: Inputs
      arguments:
        - name: "--input"
          type: file
          direction: input
          required: true
          example: input.h5mu
          description: |
            Input h5mu file.
        - name: "--modality"
          type: string
          default: "rna"
          required: false
        - name: "--input_layer"
          type: string
          required: False
          description: |
            Mudata layer (key from .layers) to use as input data for binning. If not specified, .X is used.
        - name: "--n_input_bins"
          type: integer
          default: 51
          required: False
          min: 1
          description: |
            The number of bins to discretize the data into. When no value is provided, data won't be binned.
          
    - name: Outputs
      arguments:
        - name: "--output"
          direction: output
          type: file
          example: output.h5mu
          required: true
          description: |
            The output h5mu file containing the binned data.    
        - name: "--output_compression"
          type: string
          example: "gzip"
          required: false
          choices: ["gzip", "lzf"]
          description: |
            The compression algorithm to use for the output h5mu file.
        - name: "--binned_layer"
          type: string
          default: "binned"
          description: |
            The name of the adata layer to write the binned data to.
        - name: "--seed"
          type: integer
          default: 0
          description: |
            Seed for random number generation.
  resources:
    - type: python_script
      path: script.py
  test_resources:
    - type: python_script
      path: test.py
    - path: /resources_test/scgpt/test_resources/Kim2020_Lung_subset.h5mu

platforms:
  - type: docker
    image: python:3.10-slim
    setup:
      - type: apt
        packages: 
          - procps
      - type: python
        __merge__: [ /src/base/requirements/anndata_mudata.yaml, /src/base/requirements/scanpy.yaml, .]
    test_setup:
      - type: python
        __merge__: [ /src/base/requirements/viashpy.yaml ]
  - type: nextflow