functionality:
  name: "from_bdrhap_to_h5ad"
  namespace: "convert"
  version: "dev"
  description: |
    Create a h5ad file from BD Rhapsody output.
  authors:
    - name: Robrecht Cannoodt
      email: rcannood@gmail.com
      roles: [ maintainer ]
      props: { github: rcannood, orcid: "0000-0003-3641-729X" }
  arguments:
    - name: "--input"
      alternatives: [-i]
      type: file
      description: One or more folders containing the output of the BD Rhapsody workflow. If multiple are given, they are all combined into one h5ad file.
      multiple: true
      required: true
      example: input_dir/
    - name: "--id"
      type: string
      description: "A vector of ids with same length as --input."
      multiple: true
      example: my_id
    - name: "--output"
      alternatives: [-o]
      description: "Output h5ad file."
      required: true
      type: file
      direction: output
      example: output.h5ad
  resources:
    - type: r_script
      path: script.R
  tests:
    - type: python_script
      path: run_test.py
    - path: ../../../resources_test/bd_rhapsody_wta_test
platforms:
  - type: docker
    image: ghcr.io/data-intuitive/randpy:r4.0_py3.8
    setup: 
      - type: python
        pip: anndata<0.8
      - type: r
        cran: anndata
  - type: nextflow
    variant: vdsl3
