name: "celltypist"
namespace: "workflows/annotation"
description: "Run scGPT integration (cell embedding generation) followed by neighbour calculations, leiden clustering and run umap on the result."
authors:
  - __merge__: /src/authors/dorien_roosen.yaml
    roles: [ author, maintainer ]
  - __merge__: /src/authors/jakub_majercik.yaml
    roles: [ author ]
  # - __merge__: /src/authors/weiwei_schultz.yaml
  #   roles: [ contributor ]

argument_groups:
  - name: Query input
    arguments:
      - name: "--id"
        required: true
        type: string
        description: ID of the sample.
        example: foo
      - name: "--input"
        required: true
        type: file
        description: |
          Input dataset consisting of the (unlabeled) query observations. The dataset is expected to be pre-processed in the same way as the --reference dataset.
        example: input.h5mu
      - name: "--modality"
        description: Which modality to process.
        type: string
        default: "rna"
        required: false
      - name: "--input_layer"
        type: string
        required: False
        description: |
          Mudata layer (key from layers) to use as input data for scGPT-specific pre-processing (hvg subsetting and binning); if not specified, X is used.
      - name: "--var_query_gene_names"
        type: string
        required: false
        description: |
          The name of the adata var column containing gene names; when no gene_name_layer is provided, the var index will be used.

  - name: "Reference input"
    arguments:
      - name: "--reference"
        type: file
        description: "The reference data to train the CellTypist classifiers on. Only required if a pre-trained --model is not provided."
        example: reference.h5mu
        direction: input
        required: false
      - name: "--reference_layer"
        type: string
        description: The layer in the reference data to be used for cell type annotation if .X is not to be used. Data are expected to be processed in the same way as the --input query dataset.
        required: false
      - name: "--reference_obs_targets"
        type: string
        example: ["cell_ontology_class", "celltype"]
        default: "cell_ontology_class"
        multiple: true
      - name: "--var_reference_gene_names"
        type: string
        required: false
        description: |
          The name of the adata var column in the reference data containing gene names; when no gene_name_layer is provided, the var index will be used.
  
  - name: "Model input"
    arguments:
      - name: "--model"
        type: file
        description: "Pretrained model in pkl format. If not provided, the model will be trained on the reference data and --reference should be provided."
        required: false
        example: pretrained_model.pkl

  - name: "HVG subset arguments"
    arguments:
      - name: "--obs_reference_batch_label"
        type: string
        example: "sample"
        required: false
        description: |
          obs column in the reference dataset containing the batch labels.
      - name: "--n_hvg"
        type: integer
        required: false
        description: |
          Number of highly variable genes to subset for. Only relevant when a --reference dataset is provided to train celltypist model.

  - name: "Downsampling arguments"
    arguments:
      - name: "--n_subset"
        type: integer
        required: false
        description: |
          Number of cells to subset for. Only relevant when a --reference dataset is provided to train celltypist model.

  - name: "CellTypist training arguments"
    arguments: 
      - name: "--check_expression"
        type: boolean
        description: "Whether to check the expression of the reference dataset to the format reccomended by CellTypist."
        default: false

  - name: "celltypist annotation arguments"
    arguments: 
      - name: "--majority_voting"
        type: boolean
        description: "Whether to refine the predicted labels by running the majority voting classifier after over-clustering."
        default: false

  - name: "Outputs"
    arguments:
      - name: "--output"
        type: file
        required: true
        direction: output
        description: The query data in .h5mu format with predicted labels.
        example: output.h5mu
      - name: "--output_obs_predictions"
        type: string
        required: false
        default: celltypist_pred
        description: |
          In which `.obs` slots to store the predicted information.
      - name: "--output_obs_probability"
        type: string
        required: false
        default: celltypist_probabilities
        description: |
          In which `.obs` slots to store the probability of the predictions.
      - name: "--output_compression"
        type: string
        description: |
          The compression format to be used on the output h5mu object.
        choices: ["gzip", "lzf"]
        required: false
        example: "gzip"

resources:
  - type: nextflow_script
    path: main.nf
    entrypoint: run_wf

test_resources:
  - type: nextflow_script
    path: test.nf
    entrypoint: test_wf
  - path: /resources_test

dependencies:
  - name: annotate/celltypist
    alias: celltypist_annotation
  - name: feature_annotation/highly_variable_features_scanpy
  - name: filter/do_filter
  - name: filter/subset_h5mu

runners:
  - type: nextflow