functionality:
  name: "from_bdrhap_to_h5mu"
  namespace: "convert"
  version: "dev"
  description: |
    Convert the output of a BD Rhapsody WTA pipeline to a MuData h5 file.
  authors:
    - name: Robrecht Cannoodt
      email: robrecht@data-intuitive.com
      roles: [ maintainer ]
      props: { github: rcannood, orcid: "0000-0003-3641-729X" }
  argument_groups:
    - name: Inputs
      arguments:
        - name: "--id"
          type: string
          description: "A sample ID."
          example: my_id
          required: true
        - name: "--input"
          alternatives: [-i]
          type: file
          description: The output of a BD Rhapsody workflow.
          required: true
          example: input_dir/
    - name: Outputs
      arguments:
        - name: "--output"
          alternatives: [-o]
          direction: output
          type: file
          description: "Output h5mu file."
          required: true
          example: output.h5mu
  resources:
    - type: r_script
      path: script.R
  test_resources:
    - type: python_script
      path: run_test.py
    - path: ../../../resources_test/bdrhap_5kjrt/processed/WTA.bd_rhapsody.output_raw
platforms:
  - type: docker
    image: ghcr.io/data-intuitive/randpy:r4.0_py3.8
    setup:
      - type: docker
        run: apt update && apt upgrade -y
      - type: python
        pip: [anndata~=0.8, mudata~=0.2.0]
      - type: r
        cran: anndata
  - type: nextflow
    variant: vdsl3
