functionality:
  name: "from_bdrhap_to_h5mu"
  namespace: "convert"
  description: |
    Convert the output of a BD Rhapsody WTA pipeline to a MuData h5 file.
  authors:
    - __merge__: /src/authors/robrecht_cannoodt.yaml
      roles: [ maintainer ]
  argument_groups:
    - name: Inputs
      arguments:
        - name: "--id"
          type: string
          description: "A sample ID."
          example: my_id
          required: true
        - name: "--input"
          alternatives: [-i]
          type: file
          description: The output of a BD Rhapsody workflow.
          required: true
          example: input_dir/
    - name: Outputs
      arguments:
        - name: "--output"
          alternatives: [-o]
          direction: output
          type: file
          description: "Output h5mu file."
          required: true
          example: output.h5mu
        - name: "--output_compression"
          type: string
          choices: ["gzip", "lzf"]
          required: false
          example: "gzip"
  resources:
    - type: r_script
      path: script.R
  test_resources:
    - type: python_script
      path: run_test.py
    - path: /resources_test/bdrhap_5kjrt/processed/WTA.bd_rhapsody.output_raw
platforms:
  - type: docker
    image: rocker/r2u:22.04
    setup:
      - type: docker
        run:
          - apt update && apt upgrade -y
          # - echo RETICULATE_PYTHON=/usr/bin/python3 > /etc/bash.bashrc
      - type: apt
        packages: 
          - python3
          - python3-pip
          - python3-dev
          - python-is-python3
      - type: python
        __merge__: [/src/base/requirements/scanpy.yaml, /src/base/requirements/anndata_mudata.yaml, .]
      - type: r
        cran: [ anndata, testthat, tidyverse ]
  - type: nextflow
    directives:
      label: [lowmem, singlecpu]