name: "harmony_knn"
namespace: "workflows/annotation"
version: "integration_build"
authors:
- name: "Dorien Roosen"
  roles:
  - "author"
  - "maintainer"
  info:
    role: "Core Team Member"
    links:
      email: "dorien@data-intuitive.com"
      github: "dorien-er"
      linkedin: "dorien-roosen"
    organizations:
    - name: "Data Intuitive"
      href: "https://www.data-intuitive.com"
      role: "Data Scientist"
- name: "Weiwei Schultz"
  roles:
  - "contributor"
  info:
    role: "Contributor"
    organizations:
    - name: "Janssen R&D US"
      role: "Associate Director Data Sciences"
argument_groups:
- name: "Query Input"
  arguments:
  - type: "string"
    name: "--id"
    description: "ID of the sample."
    info: null
    example:
    - "foo"
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--input"
    description: "Input dataset consisting of the (unlabeled) query observations.\
      \ The dataset is expected to be pre-processed in the same way as --reference."
    info: null
    example:
    - "input.h5mu"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--modality"
    description: "Which modality to process. Should match the modality of the --reference\
      \ dataset."
    info: null
    default:
    - "rna"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--input_obsm_embedding"
    description: "Embedding .obsm column to use as input for integration. Should match\
      \ the embedding .obsm columng of the --reference dataset."
    info: null
    example:
    - "X_pca"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--input_obs_batch_label"
    description: "The .obs field in the input (query) dataset containing the batch\
      \ labels."
    info: null
    example:
    - "sample"
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "boolean_true"
    name: "--overwrite_existing_key"
    description: "If provided, will overwrite existing fields in the input dataset\
      \ when data are copied during the reference alignment process."
    info: null
    direction: "input"
- name: "Reference input"
  arguments:
  - type: "file"
    name: "--reference"
    description: "Reference dataset consisting of the labeled observations to train\
      \ the KNN classifier on. The dataset is expected to be pre-processed in the\
      \ same way as the --input query dataset."
    info: null
    example:
    - "reference.h5mu"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--reference_obs_targets"
    description: "The `.obs` key(s) of the target labels to transfer."
    info: null
    example:
    - "ann_level_1"
    - "ann_level_2"
    - "ann_level_3"
    - "ann_level_4"
    - "ann_level_5"
    - "ann_finest_level"
    required: true
    direction: "input"
    multiple: true
    multiple_sep: ";"
  - type: "string"
    name: "--reference_obs_batch_label"
    description: "The .obs field in the reference dataset containing the batch labels."
    info: null
    example:
    - "sample"
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "Harmony integration options"
  arguments:
  - type: "double"
    name: "--theta"
    description: "Diversity clustering penalty parameter. Can be set as a single value\
      \ for all batch observations or as multiple values, one for each observation\
      \ in the batches defined by --input_obs_batch_label. theta=0 does not encourage\
      \ any diversity. Larger values of theta result in more diverse clusters.\"\n"
    info: null
    default:
    - 2.0
    required: false
    min: 0.0
    direction: "input"
    multiple: true
    multiple_sep: ";"
- name: "Leiden clustering options"
  arguments:
  - type: "double"
    name: "--leiden_resolution"
    description: "Control the coarseness of the clustering. Higher values lead to\
      \ more clusters."
    info: null
    default:
    - 1.0
    required: false
    min: 0.0
    direction: "input"
    multiple: true
    multiple_sep: ";"
- name: "Neighbor classifier arguments"
  arguments:
  - type: "string"
    name: "--weights"
    description: "Weight function used in prediction. Possible values are:\n`uniform`\
      \ (all points in each neighborhood are weighted equally) or \n`distance` (weight\
      \ points by the inverse of their distance)\n"
    info: null
    default:
    - "uniform"
    required: false
    choices:
    - "uniform"
    - "distance"
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "integer"
    name: "--n_neighbors"
    description: "The number of neighbors to use in k-neighbor graph structure used\
      \ for fast approximate nearest neighbor search with PyNNDescent. \nLarger values\
      \ will result in more accurate search results at the cost of computation time.\n"
    info: null
    default:
    - 15
    required: false
    min: 5
    direction: "input"
    multiple: false
    multiple_sep: ";"
- name: "Outputs"
  arguments:
  - type: "file"
    name: "--output"
    description: "The query data in .h5mu format with predicted labels predicted from\
      \ the classifier trained on the reference."
    info: null
    example:
    - "output.h5mu"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--output_obs_predictions"
    description: "In which `.obs` slots to store the predicted cell labels.\nIf provided,\
      \ must have the same length as `--reference_obs_targets`.\nIf empty, will default\
      \ to the `reference_obs_targets` combined with the `\"_pred\"` suffix.\n"
    info: null
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ";"
  - type: "string"
    name: "--output_obs_probability"
    description: "In which `.obs` slots to store the probability of the predictions.\n\
      If provided, must have the same length as `--reference_obs_targets`.\nIf empty,\
      \ will default to the `reference_obs_targets` combined with the `\"_probability\"\
      ` suffix.\n"
    info: null
    required: false
    direction: "input"
    multiple: true
    multiple_sep: ";"
  - type: "string"
    name: "--output_obsm_integrated"
    description: "In which .obsm slot to store the integrated embedding."
    info: null
    default:
    - "X_integrated_harmony"
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "string"
    name: "--output_compression"
    description: "The compression format to be used on the output h5mu object.\n"
    info: null
    example:
    - "gzip"
    required: false
    choices:
    - "gzip"
    - "lzf"
    direction: "input"
    multiple: false
    multiple_sep: ";"
resources:
- type: "nextflow_script"
  path: "main.nf"
  is_executable: true
  entrypoint: "run_wf"
- type: "file"
  path: "nextflow_labels.config"
  dest: "nextflow_labels.config"
description: "Cell type annotation workflow by performing harmony integration of reference\
  \ and query dataset followed by KNN label transfer."
test_resources:
- type: "nextflow_script"
  path: "test.nf"
  is_executable: true
  entrypoint: "test_wf"
- type: "file"
  path: "scgpt"
- type: "file"
  path: "openpipelinetestutils"
  dest: "openpipelinetestutils"
info:
  name: "Harmony integration followed by KNN label transfer"
  test_dependencies:
  - name: "harmony_knn_test"
    namespace: "test_workflows/annotation"
status: "enabled"
dependencies:
- name: "workflows/integration/harmony_leiden"
  alias: "harmony_leiden_workflow"
  repository:
    type: "local"
- name: "labels_transfer/knn"
  repository:
    type: "local"
- name: "dataflow/split_h5mu"
  repository:
    type: "local"
- name: "dataflow/concatenate_h5mu"
  repository:
    type: "local"
- name: "metadata/add_id"
  repository:
    type: "local"
- name: "metadata/duplicate_obs"
  repository:
    type: "local"
links:
  repository: "https://github.com/openpipelines-bio/openpipeline"
  docker_registry: "ghcr.io"
runners:
- type: "nextflow"
  id: "nextflow"
  directives:
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      mem1gb: "memory = 1000000000.B"
      mem2gb: "memory = 2000000000.B"
      mem5gb: "memory = 5000000000.B"
      mem10gb: "memory = 10000000000.B"
      mem20gb: "memory = 20000000000.B"
      mem50gb: "memory = 50000000000.B"
      mem100gb: "memory = 100000000000.B"
      mem200gb: "memory = 200000000000.B"
      mem500gb: "memory = 500000000000.B"
      mem1tb: "memory = 1000000000000.B"
      mem2tb: "memory = 2000000000000.B"
      mem5tb: "memory = 5000000000000.B"
      mem10tb: "memory = 10000000000000.B"
      mem20tb: "memory = 20000000000000.B"
      mem50tb: "memory = 50000000000000.B"
      mem100tb: "memory = 100000000000000.B"
      mem200tb: "memory = 200000000000000.B"
      mem500tb: "memory = 500000000000000.B"
      mem1gib: "memory = 1073741824.B"
      mem2gib: "memory = 2147483648.B"
      mem4gib: "memory = 4294967296.B"
      mem8gib: "memory = 8589934592.B"
      mem16gib: "memory = 17179869184.B"
      mem32gib: "memory = 34359738368.B"
      mem64gib: "memory = 68719476736.B"
      mem128gib: "memory = 137438953472.B"
      mem256gib: "memory = 274877906944.B"
      mem512gib: "memory = 549755813888.B"
      mem1tib: "memory = 1099511627776.B"
      mem2tib: "memory = 2199023255552.B"
      mem4tib: "memory = 4398046511104.B"
      mem8tib: "memory = 8796093022208.B"
      mem16tib: "memory = 17592186044416.B"
      mem32tib: "memory = 35184372088832.B"
      mem64tib: "memory = 70368744177664.B"
      mem128tib: "memory = 140737488355328.B"
      mem256tib: "memory = 281474976710656.B"
      mem512tib: "memory = 562949953421312.B"
      cpu1: "cpus = 1"
      cpu2: "cpus = 2"
      cpu5: "cpus = 5"
      cpu10: "cpus = 10"
      cpu20: "cpus = 20"
      cpu50: "cpus = 50"
      cpu100: "cpus = 100"
      cpu200: "cpus = 200"
      cpu500: "cpus = 500"
      cpu1000: "cpus = 1000"
    script:
    - "includeConfig(\"nextflow_labels.config\")"
  debug: false
  container: "docker"
build_info:
  config: "src/workflows/annotation/harmony_knn/config.vsh.yaml"
  runner: "nextflow"
  engine: "native"
  output: "target/nextflow/workflows/annotation/harmony_knn"
  executable: "target/nextflow/workflows/annotation/harmony_knn/main.nf"
  viash_version: "0.9.0"
  git_commit: "84120c987046ae5ea1bc49c65ac20a3f564c9860"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
  dependencies:
  - "target/nextflow/workflows/integration/harmony_leiden"
  - "target/nextflow/labels_transfer/knn"
  - "target/nextflow/dataflow/split_h5mu"
  - "target/nextflow/dataflow/concatenate_h5mu"
  - "target/nextflow/metadata/add_id"
  - "target/nextflow/metadata/duplicate_obs"
package_config:
  name: "openpipeline"
  info:
    test_resources:
    - type: "s3"
      path: "s3://openpipelines-data"
      dest: "resources_test"
  viash_version: "0.9.0"
  source: "src"
  target: "target"
  config_mods:
  - ".test_resources += {path: '/src/base/openpipelinetestutils', dest: 'openpipelinetestutils'}\n\
    .resources += {path: '/src/workflows/utils/labels.config', dest: 'nextflow_labels.config'}\n\
    .runners[.type == 'nextflow'].directives.tag := '$id'\n.runners[.type == 'nextflow'].config.script\
    \ := 'includeConfig(\"nextflow_labels.config\")'"
  - ".version := \"integration_build\""
  organization: "openpipelines-bio"
  links:
    repository: "https://github.com/openpipelines-bio/openpipeline"
    docker_registry: "ghcr.io"
    homepage: "https://openpipelines.bio"
    documentation: "https://openpipelines.bio/fundamentals"
    issue_tracker: "https://github.com/openpipelines-bio/openpipeline/issues"
