functionality:
  name: "harmony_knn"
  namespace: "workflows/annotation"
  version: "annotation-workflow_build"
  authors:
  - name: "Dorien Roosen"
    roles:
    - "author"
    - "maintainer"
    info:
      role: "Contributor"
      links:
        email: "dorien@data-intuitive.com"
        github: "dorien-er"
        linkedin: "dorien-roosen"
      organizations:
      - name: "Data Intuitive"
        href: "https://www.data-intuitive.com"
        role: "Data Scientist"
  - name: "Weiwei Schultz"
    roles:
    - "contributor"
    info:
      role: "Contributor"
      organizations:
      - name: "Janssen R&D US"
        role: "Associate Director Data Sciences"
  argument_groups:
  - name: "Leiden clustering options"
    arguments:
    - type: "double"
      name: "--leiden_resolution"
      description: "Control the coarseness of the clustering. Higher values lead to\
        \ more clusters."
      info: null
      default:
      - 1.0
      required: false
      direction: "input"
      multiple: true
      multiple_sep: ";"
      dest: "par"
  - name: "Neighbor classifier arguments"
    arguments:
    - type: "string"
      name: "--weights"
      description: "Weight function used in prediction. Possible values are:\n`uniform`\
        \ (all points in each neighborhood are weighted equally) or \n`distance` (weight\
        \ points by the inverse of their distance)\n"
      info: null
      default:
      - "uniform"
      required: false
      choices:
      - "uniform"
      - "distance"
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--n_neighbors"
      description: "The number of neighbors to use in k-neighbor graph structure used\
        \ for fast approximate nearest neighbor search with PyNNDescent. \nLarger\
        \ values will result in more accurate search results at the cost of computation\
        \ time."
      info: null
      default:
      - 15
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  - name: "Harmony integration options"
    arguments:
    - type: "double"
      name: "--theta"
      description: "Diversity clustering penalty parameter. Specify for each variable\
        \ in group.by.vars. \ntheta=0 does not encourage any diversity. Larger values\
        \ of theta\nresult in more diverse clusters.\"\n"
      info: null
      default:
      - 2.0
      required: false
      direction: "input"
      multiple: true
      multiple_sep: ";"
      dest: "par"
    - type: "string"
      name: "--obs_covariates"
      description: "The .obs field(s) that define the covariate(s) to regress out."
      info: null
      example:
      - "batch"
      - "sample"
      required: true
      direction: "input"
      multiple: true
      multiple_sep: ";"
      dest: "par"
    - type: "string"
      name: "--obsm_integrated"
      description: "In which .obsm slot to store the resulting integrated embedding."
      info: null
      default:
      - "X_integrated_harmony"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  resources:
  - type: "nextflow_script"
    path: "main.nf"
    is_executable: true
    entrypoint: "run_wf"
  - type: "file"
    path: "./src/workflows/utils/labels.config"
    dest: "nextflow_labels.config"
  description: "Pipeline for cell type annotation using leiden integration of reference\
    \ and query dataset followed by KNN label transfer."
  test_resources:
  - type: "file"
    path: "src/base/openpipelinetestutils"
    dest: "openpipelinetestutils"
  info: null
  status: "enabled"
  requirements:
    commands:
    - "ps"
  dependencies:
  - name: "workflows/integration/harmony_leiden"
    alias: "harmony_leiden_workflow"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/openpipeline/openpipeline/src/workflows/integration/harmony_leiden/config.vsh.yaml"
    configInfo:
      functionalityName: "harmony_leiden"
      git_tag: "0.2.0-1630-gb55e6ab01d"
      git_remote: "https://github.com/openpipelines-bio/openpipeline"
      viash_version: "0.8.6"
      config: "/home/runner/work/openpipeline/openpipeline/src/workflows/integration/harmony_leiden/config.vsh.yaml"
      functionalityNamespace: "workflows/integration"
      output: ""
      platform: ""
      git_commit: "b55e6ab01d1acfc3e3eed55dda376684c3964e24"
      executable: "/nextflow/workflows/integration/harmony_leiden/main.nf"
    writtenPath: "/home/runner/work/openpipeline/openpipeline/target/nextflow/workflows/integration/harmony_leiden"
  - name: "labels_transfer/pynndescent_knn"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/openpipeline/openpipeline/src/labels_transfer/pynndescent_knn/config.vsh.yaml"
    configInfo:
      functionalityName: "pynndescent_knn"
      git_tag: "0.2.0-1630-gb55e6ab01d"
      git_remote: "https://github.com/openpipelines-bio/openpipeline"
      viash_version: "0.8.6"
      config: "/home/runner/work/openpipeline/openpipeline/src/labels_transfer/pynndescent_knn/config.vsh.yaml"
      functionalityNamespace: "labels_transfer"
      output: ""
      platform: ""
      git_commit: "b55e6ab01d1acfc3e3eed55dda376684c3964e24"
      executable: "/nextflow/labels_transfer/pynndescent_knn/main.nf"
    writtenPath: "/home/runner/work/openpipeline/openpipeline/target/nextflow/labels_transfer/pynndescent_knn"
  - name: "dataflow/split_samples"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/openpipeline/openpipeline/src/dataflow/split_samples/config.vsh.yaml"
    configInfo:
      functionalityName: "split_samples"
      git_tag: "0.2.0-1630-gb55e6ab01d"
      git_remote: "https://github.com/openpipelines-bio/openpipeline"
      viash_version: "0.8.6"
      config: "/home/runner/work/openpipeline/openpipeline/src/dataflow/split_samples/config.vsh.yaml"
      functionalityNamespace: "dataflow"
      output: ""
      platform: ""
      git_commit: "b55e6ab01d1acfc3e3eed55dda376684c3964e24"
      executable: "/nextflow/dataflow/split_samples/main.nf"
    writtenPath: "/home/runner/work/openpipeline/openpipeline/target/nextflow/dataflow/split_samples"
  - name: "dataflow/concatenate_h5mu"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/openpipeline/openpipeline/src/dataflow/concatenate_h5mu/config.vsh.yaml"
    configInfo:
      functionalityName: "concatenate_h5mu"
      git_tag: "0.2.0-1630-gb55e6ab01d"
      git_remote: "https://github.com/openpipelines-bio/openpipeline"
      viash_version: "0.8.6"
      config: "/home/runner/work/openpipeline/openpipeline/src/dataflow/concatenate_h5mu/config.vsh.yaml"
      functionalityNamespace: "dataflow"
      output: ""
      platform: ""
      git_commit: "b55e6ab01d1acfc3e3eed55dda376684c3964e24"
      executable: "/nextflow/dataflow/concatenate_h5mu/main.nf"
    writtenPath: "/home/runner/work/openpipeline/openpipeline/target/nextflow/dataflow/concatenate_h5mu"
  - name: "metadata/add_id"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/openpipeline/openpipeline/src/metadata/add_id/config.vsh.yaml"
    configInfo:
      functionalityName: "add_id"
      git_tag: "0.2.0-1630-gb55e6ab01d"
      git_remote: "https://github.com/openpipelines-bio/openpipeline"
      viash_version: "0.8.6"
      config: "/home/runner/work/openpipeline/openpipeline/src/metadata/add_id/config.vsh.yaml"
      functionalityNamespace: "metadata"
      output: ""
      platform: ""
      git_commit: "b55e6ab01d1acfc3e3eed55dda376684c3964e24"
      executable: "/nextflow/metadata/add_id/main.nf"
    writtenPath: "/home/runner/work/openpipeline/openpipeline/target/nextflow/metadata/add_id"
  set_wd_to_resources_dir: false
platforms:
- type: "nextflow"
  id: "nextflow"
  directives:
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      mem1gb: "memory = 1.GB"
      mem2gb: "memory = 2.GB"
      mem4gb: "memory = 4.GB"
      mem8gb: "memory = 8.GB"
      mem16gb: "memory = 16.GB"
      mem32gb: "memory = 32.GB"
      mem64gb: "memory = 64.GB"
      mem128gb: "memory = 128.GB"
      mem256gb: "memory = 256.GB"
      mem512gb: "memory = 512.GB"
      mem1tb: "memory = 1.TB"
      mem2tb: "memory = 2.TB"
      mem4tb: "memory = 4.TB"
      mem8tb: "memory = 8.TB"
      mem16tb: "memory = 16.TB"
      mem32tb: "memory = 32.TB"
      mem64tb: "memory = 64.TB"
      mem128tb: "memory = 128.TB"
      mem256tb: "memory = 256.TB"
      mem512tb: "memory = 512.TB"
      cpu1: "cpus = 1"
      cpu2: "cpus = 2"
      cpu5: "cpus = 5"
      cpu10: "cpus = 10"
      cpu20: "cpus = 20"
      cpu50: "cpus = 50"
      cpu100: "cpus = 100"
      cpu200: "cpus = 200"
      cpu500: "cpus = 500"
      cpu1000: "cpus = 1000"
    script:
    - "includeConfig(\"nextflow_labels.config\")"
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/openpipeline/openpipeline/src/workflows/annotation/harmony_knn/config.vsh.yaml"
  platform: "nextflow"
  output: "/home/runner/work/openpipeline/openpipeline/target/nextflow/workflows/annotation/harmony_knn"
  executable: "/home/runner/work/openpipeline/openpipeline/target/nextflow/workflows/annotation/harmony_knn/main.nf"
  viash_version: "0.8.6"
  git_commit: "b55e6ab01d1acfc3e3eed55dda376684c3964e24"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
  git_tag: "0.2.0-1630-gb55e6ab01d"
