functionality:
  name: "scgpt_cell_type_annotation"
  namespace: "workflows/annotation"
  version: "integration_build"
  authors:
  - name: "Jakub Majercik"
    roles:
    - "author"
    - "maintainer"
    info:
      role: "Contributor"
      links:
        email: "jakub@data-intuitive.com"
        github: "jakubmajercik"
        linkedin: "jakubmajercik"
      organizations:
      - name: "Data Intuitive"
        href: "https://www.data-intuitive.com"
        role: "Bioinformatics Engineer"
  - name: "Dorien Roosen"
    roles:
    - "author"
    - "maintainer"
    info:
      role: "Contributor"
      links:
        email: "dorien@data-intuitive.com"
        github: "dorien-er"
        linkedin: "dorien-roosen"
      organizations:
      - name: "Data Intuitive"
        href: "https://www.data-intuitive.com"
        role: "Data Scientist"
  argument_groups:
  - name: "Input"
    arguments:
    - type: "string"
      name: "--id"
      description: "ID of the sample."
      info: null
      example:
      - "foo"
      required: true
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--input"
      description: "Path to the sample."
      info: null
      example:
      - "dataset.h5mu"
      must_exist: true
      create_parent: true
      required: true
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--input_layer"
      description: "Mudata layer (key from layers) to use as input data for hvg subsetting\
        \ and binning; if not specified, X is used.\n"
      info: null
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--modality"
      info: null
      default:
      - "rna"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--model_vocab"
      description: "Model vocabulary file directory.\n"
      info: null
      example:
      - "resources_test/scgpt/vocab.json"
      must_exist: true
      create_parent: true
      required: true
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--model"
      description: "The model file.\n"
      info: null
      example:
      - "resources_test/scgpt/source/best_model.pt"
      must_exist: true
      create_parent: true
      required: true
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--model_config"
      description: "The model configuration file. \n"
      info: null
      example:
      - "resources_test/scgpt/source/args.json"
      must_exist: true
      create_parent: true
      required: true
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  - name: "Outputs"
    arguments:
    - type: "file"
      name: "--output"
      description: "Destination path to the output."
      info: null
      example:
      - "output.h5mu"
      must_exist: true
      create_parent: true
      required: true
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--output_compression"
      description: "The compression algorithm to use for the output h5mu file.\n"
      info: null
      example:
      - "gzip"
      required: false
      choices:
      - "gzip"
      - "lzf"
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--obs_predicted_cell_type"
      description: "The name of the adata.obs column to write predicted cell types\
        \ to.\n"
      info: null
      default:
      - "predicted_cell_type"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  - name: "Arguments"
    arguments:
    - type: "string"
      name: "--pad_token"
      description: "The padding token used in the model.\n"
      info: null
      default:
      - "<pad>"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--pad_value"
      description: "The value of the padding token.\n"
      info: null
      default:
      - -2
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--max_seq_len"
      description: "The maximum sequence length of the tokenized data.\n"
      info: null
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--gene_name_layer"
      description: "The name of the adata.var column containing gene names.\n"
      info: null
      example:
      - "gene_name"
      default:
      - "gene_name"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--batch_id_layer"
      description: "The name of the adata.obs column to write categorical batch ids\
        \ to.\n"
      info: null
      default:
      - "batch_id"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--n_cls"
      description: "The number of classes.\n"
      info: null
      default:
      - 8
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--n_input_bins"
      description: "The number of input bins.\n"
      info: null
      default:
      - 51
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--batch_size"
      description: "The batch size. \n"
      info: null
      default:
      - 64
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "boolean"
      name: "--dsbn"
      description: "Whether to use domain-specific batch normalization.\n"
      info: null
      default:
      - true
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--n_hvg"
      description: "Number of highly variable genes to subset for.\n"
      info: null
      default:
      - 1200
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--var_gene_names"
      description: "The name of the adata.var column containing gene names. When no\
        \ gene_name_layer is provided, the .var index will be used.\n"
      info: null
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--binned_layer"
      description: "The name of the adata layer to write the binned data to.\n"
      info: null
      default:
      - "binned"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--obs_batch_label"
      description: "The name of the adata.obs column containing the batch labels.\n"
      info: null
      default:
      - "sample"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--seed"
      description: "Seed for random number generation. If not specified, no seed is\
        \ used.\n"
      info: null
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  resources:
  - type: "nextflow_script"
    path: "main.nf"
    is_executable: true
    entrypoint: "run_wf"
  - type: "file"
    path: "src/workflows/utils/"
  - type: "file"
    path: "./src/workflows/utils/labels.config"
    dest: "nextflow_labels.config"
  description: "scGPT cell type annotation through decoding of cell embeddings."
  test_resources:
  - type: "nextflow_script"
    path: "test.nf"
    is_executable: true
    entrypoint: "test_wf"
  - type: "file"
    path: "resources_test/scgpt"
  - type: "file"
    path: "src/base/openpipelinetestutils"
    dest: "openpipelinetestutils"
  info: null
  status: "enabled"
  requirements:
    commands:
    - "ps"
  dependencies:
  - name: "scgpt/pad_tokenize"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/openpipeline/openpipeline/src/scgpt/pad_tokenize/config.vsh.yaml"
    configInfo:
      functionalityName: "pad_tokenize"
      git_tag: ""
      git_remote: "https://github.com/openpipelines-bio/openpipeline"
      viash_version: "0.8.5"
      config: "/home/runner/work/openpipeline/openpipeline/src/scgpt/pad_tokenize/config.vsh.yaml"
      functionalityNamespace: "scgpt"
      output: ""
      platform: ""
      git_commit: "990cf3e717412711e547b1268f4cad0ba4c15592"
      executable: "/nextflow/scgpt/pad_tokenize/main.nf"
    writtenPath: "/home/runner/work/openpipeline/openpipeline/target/nextflow/scgpt/pad_tokenize"
  - name: "scgpt/cell_type_annotation"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/openpipeline/openpipeline/src/scgpt/cell_type_annotation/config.vsh.yaml"
    configInfo:
      functionalityName: "cell_type_annotation"
      git_tag: ""
      git_remote: "https://github.com/openpipelines-bio/openpipeline"
      viash_version: "0.8.5"
      config: "/home/runner/work/openpipeline/openpipeline/src/scgpt/cell_type_annotation/config.vsh.yaml"
      functionalityNamespace: "scgpt"
      output: ""
      platform: ""
      git_commit: "990cf3e717412711e547b1268f4cad0ba4c15592"
      executable: "/nextflow/scgpt/cell_type_annotation/main.nf"
    writtenPath: "/home/runner/work/openpipeline/openpipeline/target/nextflow/scgpt/cell_type_annotation"
  - name: "scgpt/cross_check_genes"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/openpipeline/openpipeline/src/scgpt/cross_check_genes/config.vsh.yaml"
    configInfo:
      functionalityName: "cross_check_genes"
      git_tag: ""
      git_remote: "https://github.com/openpipelines-bio/openpipeline"
      viash_version: "0.8.5"
      config: "/home/runner/work/openpipeline/openpipeline/src/scgpt/cross_check_genes/config.vsh.yaml"
      functionalityNamespace: "scgpt"
      output: ""
      platform: ""
      git_commit: "990cf3e717412711e547b1268f4cad0ba4c15592"
      executable: "/nextflow/scgpt/cross_check_genes/main.nf"
    writtenPath: "/home/runner/work/openpipeline/openpipeline/target/nextflow/scgpt/cross_check_genes"
  - name: "scgpt/binning"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/openpipeline/openpipeline/src/scgpt/binning/config.vsh.yaml"
    configInfo:
      functionalityName: "binning"
      git_tag: ""
      git_remote: "https://github.com/openpipelines-bio/openpipeline"
      viash_version: "0.8.5"
      config: "/home/runner/work/openpipeline/openpipeline/src/scgpt/binning/config.vsh.yaml"
      functionalityNamespace: "scgpt"
      output: ""
      platform: ""
      git_commit: "990cf3e717412711e547b1268f4cad0ba4c15592"
      executable: "/nextflow/scgpt/binning/main.nf"
    writtenPath: "/home/runner/work/openpipeline/openpipeline/target/nextflow/scgpt/binning"
  - name: "feature_annotation/highly_variable_features_scanpy"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/openpipeline/openpipeline/src/feature_annotation/highly_variable_features_scanpy/config.vsh.yaml"
    configInfo:
      functionalityName: "highly_variable_features_scanpy"
      git_tag: ""
      git_remote: "https://github.com/openpipelines-bio/openpipeline"
      viash_version: "0.8.5"
      config: "/home/runner/work/openpipeline/openpipeline/src/feature_annotation/highly_variable_features_scanpy/config.vsh.yaml"
      functionalityNamespace: "feature_annotation"
      output: ""
      platform: ""
      git_commit: "990cf3e717412711e547b1268f4cad0ba4c15592"
      executable: "/nextflow/feature_annotation/highly_variable_features_scanpy/main.nf"
    writtenPath: "/home/runner/work/openpipeline/openpipeline/target/nextflow/feature_annotation/highly_variable_features_scanpy"
  - name: "filter/do_filter"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/openpipeline/openpipeline/src/filter/do_filter/config.vsh.yaml"
    configInfo:
      functionalityName: "do_filter"
      git_tag: ""
      git_remote: "https://github.com/openpipelines-bio/openpipeline"
      viash_version: "0.8.5"
      config: "/home/runner/work/openpipeline/openpipeline/src/filter/do_filter/config.vsh.yaml"
      functionalityNamespace: "filter"
      output: ""
      platform: ""
      git_commit: "990cf3e717412711e547b1268f4cad0ba4c15592"
      executable: "/nextflow/filter/do_filter/main.nf"
    writtenPath: "/home/runner/work/openpipeline/openpipeline/target/nextflow/filter/do_filter"
  set_wd_to_resources_dir: false
platforms:
- type: "nextflow"
  id: "nextflow"
  directives:
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      mem1gb: "memory = 1.GB"
      mem2gb: "memory = 2.GB"
      mem4gb: "memory = 4.GB"
      mem8gb: "memory = 8.GB"
      mem16gb: "memory = 16.GB"
      mem32gb: "memory = 32.GB"
      mem64gb: "memory = 64.GB"
      mem128gb: "memory = 128.GB"
      mem256gb: "memory = 256.GB"
      mem512gb: "memory = 512.GB"
      mem1tb: "memory = 1.TB"
      mem2tb: "memory = 2.TB"
      mem4tb: "memory = 4.TB"
      mem8tb: "memory = 8.TB"
      mem16tb: "memory = 16.TB"
      mem32tb: "memory = 32.TB"
      mem64tb: "memory = 64.TB"
      mem128tb: "memory = 128.TB"
      mem256tb: "memory = 256.TB"
      mem512tb: "memory = 512.TB"
      cpu1: "cpus = 1"
      cpu2: "cpus = 2"
      cpu5: "cpus = 5"
      cpu10: "cpus = 10"
      cpu20: "cpus = 20"
      cpu50: "cpus = 50"
      cpu100: "cpus = 100"
      cpu200: "cpus = 200"
      cpu500: "cpus = 500"
      cpu1000: "cpus = 1000"
    script:
    - "includeConfig(\"nextflow_labels.config\")"
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/openpipeline/openpipeline/src/workflows/annotation/scgpt_cell_type_annotation/config.vsh.yaml"
  platform: "nextflow"
  output: "/home/runner/work/openpipeline/openpipeline/target/nextflow/workflows/annotation/scgpt_cell_type_annotation"
  executable: "/home/runner/work/openpipeline/openpipeline/target/nextflow/workflows/annotation/scgpt_cell_type_annotation/main.nf"
  viash_version: "0.8.5"
  git_commit: "990cf3e717412711e547b1268f4cad0ba4c15592"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
