functionality:
  name: make_reference
  namespace: reference
  description: Make a reference build.
  authors:
    - name: Angela Pisco
      roles: [ author ]
      props: { github: aopisco, orcid: "0000-0003-0142-2355" }
    - name: Robrecht Cannoodt
      email: robrecht@data-intuitive.com
      roles: [ author, maintainer ]
      props: { github: rcannood, orcid: "0000-0003-3641-729X" }
  arguments:
    # inputs
    - type: string
      name: --genome_fasta
      required: true
      description: Reference genome fasta.
      example: https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_41/GRCh38.primary_assembly.genome.fa.gz
    - type: string
      name: --transcriptome_gtf
      required: true
      description: Reference transcriptome annotation.
      example: https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_41/gencode.v41.annotation.gtf.gz
    - type: string
      name: --ercc
      description: ERCC sequence and annotation file.
      example: https://assets.thermofisher.com/TFS-Assets/LSG/manuals/ERCC92.zip
    - type: string
      name: --subset_regex
      description: Will subset the reference chromosomes using the given regex.
      example: (ERCC-00002|chr1)
    - type: file
      name: --output_fasta
      direction: output
      required: true
      description: Output genome sequence fasta.
      example: genome_sequence.fa.gz
    - type: file
      name: --output_gtf
      direction: output
      required: true
      description: Output transcriptome annotation gtf.
      example: transcriptome_annotation.tar.gz
  resources:
    - type: bash_script
      path: script.sh
  test_resources:
    - type: bash_script
      path: run_test.sh
platforms:
  - type: docker
    image: ubuntu:22.04
    setup:
      - type: apt
        packages: [ pigz, seqkit, curl, wget, unzip ]
  - type: nextflow
    variant: vdsl3
    directives:
      label: [ highmem, highcpu ]