functionality:
  name: split_data
  namespace: "scgpt"
  description: |
    Split data into training (and validation) and test sets.
  authors:
    - __merge__: /src/authors/jakub_majercik.yaml
      roles: [ maintainer, author ]
  argument_groups:
    - name: Inputs
      arguments:
        - name: "--input"
          type: file
          direction: input
          required: true
          example: input.h5mu
          description: |
            The input h5mu file containing pre-processed data.
        - name: "--modality"
          type: string
          default: "rna"
          required: false

    - name: Outputs
      arguments:
        - name: "--output"
          type: file
          direction: output
          required: true
          example: output.h5mu
          description: |
            The output cross-checked anndata file.

    - name: Arguments
      arguments:
        - name: "--train_size"
          type: float
          default: 0.8
          required: false
          description: |
            The fraction of the data to be used for training. If None, the value is automatically set to the complement of the test size.
        - name: "--test_size"
          type: float
          default: 0.2
          required: false
          description: |
            The fraction of the data to be used for testing. f None, the value is set to the complement of the train size. If train_size is also None, it will be set to 0.25.
        - name: "--val_size"
          type: float
          required: false
          description: |
            The fraction of the data to be used for validation.
        - name: "--shuffle"
          type: boolean
          default: true
          required: false
          description: |
            Whether or not to shuffle the data before splitting.
        - name: "--stratify"
          type: boolean
          default: false
          required: false
          description: |
            Whether or not to stratify the data before splitting.
        
  resources:
    - type: python_script
      path: script.py
    - path: /src/utils/setup_logger.py
  test_resources:
    - type: python_script
      path: test.py
    - path: /resources_test/scgpt/test_resources/Kim2020_Lung.h5mu

platforms:
  - type: docker
    image: nvcr.io/nvidia/pytorch:23.09-py3
    setup:
      - type: python
        __merge__: /src/base/requirements/anndata_mudata.yaml
      - type: docker
        run:
          echo "build --jobs 4" >> /etc/bazel.bazelrc
      - type: python
        packages:
          - scgpt==0.2.1
    test_setup:
      - type: python
        __merge__: [ /src/base/requirements/viashpy.yaml ]
    __merge__: [ /src/base/requirements/python_test_setup.yaml, .]
  - type: nextflow