functionality:
  name: "scgpt_annotation"
  namespace: "workflows/annotation"
  description: "Run scGPT integration (cell embedding generation) followed by neighbour calculations, leiden clustering and run umap on the result."
  authors:
    - __merge__: /src/authors/dorien_roosen.yaml
      roles: [ author, maintainer ]
    - __merge__: /src/authors/jakub_majercik.yaml
      roles: [ author ]

  argument_groups:
    - name: "Query input"
      arguments:
        - name: "--id"
          required: true
          type: string
          description: ID of the sample.
          example: foo
        - name: "--input"
          type: file
          required: true
          description: Path to the input file.
          example: input.h5mu
        - name: "--modality"
          type: string
          default: "rna"
          required: false
        - name: "--input_layer"
          type: string
          required: False
          description: |
            Mudata layer (key from layers) to use as input data for hvg subsetting and binning; if not specified, X is used.
        - name: "--var_gene_names"
          type: string
          required: false
          description: |
            The name of the adata var column containing gene names; when no gene_name_layer is provided, the var index will be used.
        - name: "--obs_batch_label"
          type: string
          description: |
            The name of the adata obs column containing the batch labels.
    - name: "Model input"
      arguments:
        - name: "--model"
          type: file
          required: true
          example: best_model.pt
          description: |
            The model file containing checkpoints and cell type label mapper.
        - name: "--model_config"
          type: file
          required: true
          example: args.json
          description: |
            The model configuration file. 
        - name: "--model_vocab"
          type: file
          required: true
          example: vocab.json
          description: |
            Model vocabulary file directory.
        - name: "--finetuned_checkpoints_key"
          type: string
          default: model_state_dict
          description: |
            Key in the model  file containing the pretrained checkpoints.
        - name: "--label_mapper_key"
          type: string
          default: id_to_class
          description: |
            Key in the model file containing the cell type class to label mapper dictionary.
    - name: "Outputs"
      arguments:
        - name: "--output"
          type: file
          required: true
          direction: output
          description: Output file path
          example: output.h5mu
        - name: "--output_compression"
          type: string
          example: "gzip"
          required: false
          choices: ["gzip", "lzf"]
          description: |
            The compression algorithm to use for the output h5mu file.
        - name: "--output_obs_predictions"
          type: string
          default: "scgpt_pred"
          required: false
          description: |
            The name of the adata.obs column to write predicted cell type labels to.
        - name: "--output_obs_probability"
          type: string
          default: "scgpt_probability"
          required: false
          description: |
            The name of the adata.obs column to write predicted cell type labels to.
            
    - name: "Padding arguments"
      arguments:
        - name: "--pad_token"
          type: string
          default: "<pad>"
          required: false
          description: |
            Token used for padding.
        - name: "--pad_value"
          type: integer
          default: -2
          required: false
          description: |
            The value of the padding token.
    
    - name: "HVG subset arguments"
      arguments:
        - name: "--n_hvg"
          type: integer
          default: 1200
          description: |
            Number of highly variable genes to subset for.
    - name: "Tokenization arguments"
      arguments:
        - name: "--max_seq_len"
          type: integer
          required: false
          description: |
            The maximum sequence length of the tokenized data.
    - name: "Embedding arguments"
      arguments:
        - name: --dsbn
          type: boolean
          default: true
          description: |
            Apply domain-specific batch normalization
        - name: "--batch_size"
          type: integer
          default: 64
          description: |
            The batch size to be used for embedding inference.
    - name: "Binning arguments"
      arguments:
        - name: "--n_input_bins"
          type: integer
          default: 51
          required: False
          min: 1
          description: |
            The number of bins to discretize the data into; When no value is provided, data won't be binned.
        - name: "--seed"
          type: integer
          required: false
          description: |
            Seed for random number generation used for binning. If not set, no seed is used.
  
  resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: run_wf

  test_resources:
    - type: nextflow_script
      path: test.nf
      entrypoint: test_wf
    - path: /resources_test/scgpt

  dependencies:
    - name: scgpt/cross_check_genes
    - name: scgpt/binning
    - name: feature_annotation/highly_variable_features_scanpy
    - name: filter/do_filter
    - name: scgpt/pad_tokenize
    - name: scgpt/annotation

platforms:
  - type: nextflow
