functionality:
  name: mermaid
  namespace: "report"
  version: "dev"
  description: |
    Generates a network from mermaid code.
  authors:
    - __merge__: ../../authors/dries_de_maeyer.yaml
      roles: [ maintainer ]
  arguments:
    - name: "--input"
      alternatives: [-i]
      type: file
      description: Input directory
      direction: input
      required: true
    - name: "--output"
      alternatives: ["-o"]
      type: file
      description: Generated network as output.
      direction: output
      required: true
    - name: "--output_format"
      type: string
      description: |
        Output format for the generated image. By default will be inferred from the extension 
        of the file specified with --output.
      choices: ["svg", "png", "pdf"]
    - name: "--width"
      type: integer
      description: "Width of the page"
      default: 800
    - name: "--height"
      type: integer
      description: "Height of the page"
      default: 600
    - name: "--background_color"
      type: string
      description: "Background color for pngs/svgs (not pdfs)"
      default: "white"
      example: ["#F0F0F0"]
  resources:
    - type: bash_script
      path: script.sh
    - path: ./puppeteer-config.json
  test_resources:
    - type: python_script
      path: test.py
platforms:
  - type: docker
    image: "node:20-bullseye"
    setup:
      - type: javascript
        npm: 
         - "@mermaid-js/mermaid-cli"
      - type: apt
        packages: 
          - libx11-xcb1
          - libxcomposite1
          - libasound2
          - libatk1.0-0
          - libatk-bridge2.0-0
          - libcairo2
          - libcups2
          - libdbus-1-3 
          - libexpat1
          - libfontconfig1 
          - libgbm1
          - libgcc1
          - libglib2.0-0
          - libgtk-3-0
          - libnspr4
          - libpango-1.0-0
          - libpangocairo-1.0-0
          - libstdc++6
          - libx11-6
          - libx11-xcb1
          - libxcb1
          - libxcomposite1
          - libxcursor1
          - libxdamage1
          - libxext6
          - libxfixes3
          - libxi6
          - libxrandr2
          - libxrender1
          - libxss1
          - libxtst6
          - libnss3-dev
          - chromium
    test_setup:
      - type: apt
        packages: 
          - python3
          - python3-pip
          - python-is-python3
      - type: python
        packages:
          - viashpy
  - type: nextflow
