name: svm_annotation
namespace: annotate
description: Automated cell type annotation tool for scRNA-seq datasets on the basis of SVMs.
authors:
  - __merge__: /src/authors/jakub_majercik.yaml
    roles: [ author ]

argument_groups:
  - name: Inputs
    description: Input dataset (query) arguments
    arguments:
      - name: "--input"
        type: file
        description: The input (query) data to be labeled. Should be a .h5mu file.
        direction: input
        required: true
        example: input.h5mu
      - name: "--modality"
        description: Which modality to process.
        type: string
        default: "rna"
        required: false
      - name: "--input_layer"
        type: string
        description: The layer in the input data to be used for cell type annotation if .X is not to be used. 
  - name: Reference
    description: Arguments related to the reference dataset.
    arguments:
      - name: "--reference"
        type: file
        description: "The reference data to train the CellTypist classifiers on. Only required if a pre-trained --model is not provided."
        example: reference.h5mu
        direction: input
        required: false
      - name: "--reference_layer"
        type: string
        description: The layer in the reference data to be used for cell type annotation if .X is not to be used. Data are expected to be processed in the same way as the --input query dataset.
        required: false
      - name: "--reference_obs_target"
        type: string
        description:
        required: true
  - name: Outputs
    description: Output arguments.
    arguments:
      - name: "--output"
        type: file
        description: Output h5mu file.
        direction: output
        example: output.h5mu
      - name: "--output_compression"
        type: string
        choices: ["gzip", "lzf"]
        required: false
        example: "gzip"
      - name: "--output_obs_prediction"
        type: string
        default: svm_pred
        required: false
        description: |
          In which `.obs` slots to store the predicted information.
      - name: "--output_obs_probability"
        type: string
        default: svm_probability
        required: false
        description: |
          In which `.obs` slots to store the probability of the predictions.
  - name: Model arguments
    description: Model arguments.
    arguments:
      - name: "--model"
        type: file
        description: "Pretrained model in pkl format. If not provided, the model will be trained on the reference data and --reference should be provided."
        required: false
        example: pretrained_model.pkl
      - name: "--feature_selection"
        type: boolean
        description: "Whether to perform feature selection."
        default: true
      - name: "--max_iter"
        type: integer
        description: "Maximum number of iterations for the SVM."
        min: 1
        default: 5000
      - name: "--c_reg"
        type: double
        description: "Regularization parameter for the SVM."
        min: 0.0
        default: 1.0
      - name: "--class_weight"
        type: string
        description: |
          "Class weights for the SVM.  The `uniform` mode gives all classes a weight  of one. 
          The `balanced` mode (default) uses the values of y to automatically adjust weights inversely 
          proportional to class frequencies in the input data as n_samples / (n_classes * np.bincount(y))"
        choices: ["balanced", "uniform"]
        default: "balanced"

resources:
  - type: python_script
    path: script.py
  - path: /src/utils/setup_logger.py
  
test_resources:
  - type: python_script
    path: test.py
  - path: /resources_test/annotation_test_data/
  - path: /resources_test/pbmc_1k_protein_v3/

engines:
  - type: docker
    image: python:3.12-slim
    setup:
      - type: apt
        packages:
          - libhdf5-dev
          - procps
      - type: python
        packages:
          - scikit-learn==1.5.2
      - type: python
        __merge__: [ /src/base/requirements/anndata_mudata.yaml, .]
    __merge__: [ /src/base/requirements/python_test_setup.yaml, .]
runners:
  - type: executable 
  - type: nextflow