functionality:
  name: "rna_multisample"
  namespace: "workflows/multiomics"
  description: "Processing unimodal multi-sample RNA transcriptomics data."
  info:
    image: /images/concepts/fig_workflow_multiomics_rna_multisample.svg
  authors:
    - __merge__: /src/authors/dries_de_maeyer.yaml
      roles: [ author ]
    - __merge__: /src/authors/robrecht_cannoodt.yaml
      roles: [ author, maintainer ]
    - __merge__: /src/authors/dries_schaumont.yaml
      roles: [ author ]
  argument_groups:
    - name: "Inputs"
      arguments:
        - name: "--id"
          required: true
          type: string
          description: ID of the concatenated file
          example: concatenated
        - name: "--input"
          required: true
          type: file
          description: Path to the samples.
          example: dataset.h5mu
        - name: "--modality"
          type: string
          description: Modality to process.
          default: "rna"
    - name: "Output"
      arguments:
        - name: "--output"
          type: file
          required: true
          direction: output
          description: Destination path to the output.
          example: output.h5mu
    - name: "Filtering highly variable genes"
      arguments:
        - name: "--filter_with_hvg_var_output"
          required: false
          type: string
          default: "filter_with_hvg"
          description: In which .var slot to store a boolean array corresponding to the highly variable genes.
        - name: "--filter_with_hvg_obs_batch_key"
          type: string
          default: "sample_id"
          required: false
          description: |
            If specified, highly-variable genes are selected within each batch separately and merged. This simple 
            process avoids the selection of batch-specific genes and acts as a lightweight batch correction method. 
            For all flavors, genes are first sorted by how many batches they are a HVG. For dispersion-based flavors 
            ties are broken by normalized dispersion. If flavor = 'seurat_v3', ties are broken by the median (across
            batches) rank based on within-batch normalized variance.
        - name: "--filter_with_hvg_flavor"
          type: string
          default: "seurat"
          choices: ["seurat", "cell_ranger", "seurat_v3"]
          description: |
            Choose the flavor for identifying highly variable genes. For the dispersion based methods
            in their default workflows, Seurat passes the cutoffs whereas Cell Ranger passes n_top_genes.
        - name: "--filter_with_hvg_n_top_genes"
          required: false
          type: integer
          description: Number of highly-variable genes to keep. Mandatory if filter_with_hvg_flavor is set to 'seurat_v3'.
    - name: "QC metrics calculation options"
      arguments:
        - name: "--var_qc_metrics"
          description: |
            Keys to select a boolean (containing only True or False) column from .var.
            For each cell, calculate the proportion of total values for genes which are labeled 'True', 
            compared to the total sum of the values for all genes.
          type: string
          multiple: True
          multiple_sep: ','
          required: false
          default: ["filter_with_hvg"]
          example: "ercc,highly_variable"
        - name: "--top_n_vars"
          type: integer
          description: |
            Number of top vars to be used to calculate cumulative proportions.
            If not specified, proportions are not calculated. `--top_n_vars 20,50` finds
            cumulative proportion to the 20th and 50th most expressed vars.
          multiple: true
          multiple_sep: ','
          required: false
          default: [50, 100, 200, 500]
  dependencies:
    - name: transform/normalize_total
    - name: transform/log1p
    - name: filter/filter_with_hvg
    - name: qc/calculate_qc_metrics
    - name: transform/delete_layer
    - name: metadata/add_id
  resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: run_wf
  test_resources:
    - type: nextflow_script
      path: test.nf
      entrypoint: test_wf
    - path: /resources_test/concat_test_data
platforms:
  - type: nextflow