functionality:
  name: "build_bdrhap_reference"
  namespace: "reference"
  version: "0.11.3"
  authors:
  - name: "Angela Oliveira Pisco"
    roles:
    - "author"
    info:
      role: "Contributor"
      links:
        github: "aopisco"
        orcid: "0000-0003-0142-2355"
        linkedin: "aopisco"
      organizations:
      - name: "Insitro"
        href: "https://insitro.com"
        role: "Director of Computational Biology"
      - name: "Open Problems"
        href: "https://openproblems.bio"
        role: "Core Member"
  - name: "Robrecht Cannoodt"
    roles:
    - "author"
    - "maintainer"
    info:
      role: "Core Team Member"
      links:
        email: "robrecht@data-intuitive.com"
        github: "rcannood"
        orcid: "0000-0003-3641-729X"
        linkedin: "robrechtcannoodt"
      organizations:
      - name: "Data Intuitive"
        href: "https://www.data-intuitive.com"
        role: "Data Science Engineer"
      - name: "Open Problems"
        href: "https://openproblems.bio"
        role: "Core Member"
  arguments:
  - type: "file"
    name: "--genome_fasta"
    description: "Reference genome fasta."
    info: null
    example:
    - "genome_sequence.fa.gz"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--transcriptome_gtf"
    description: "Reference transcriptome annotation."
    info: null
    example:
    - "transcriptome_annotation.gtf.gz"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output"
    description: "Star index"
    info: null
    example:
    - "star_index.tar.gz"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  resources:
  - type: "bash_script"
    path: "script.sh"
    is_executable: true
  description: "Compile a reference into a STAR index compatible with the BD Rhapsody\
    \ pipeline."
  test_resources:
  - type: "bash_script"
    path: "run_test.sh"
    is_executable: true
  - type: "file"
    path: "resources_test/reference_gencodev41_chr1"
  info: null
  status: "enabled"
  requirements:
    commands:
    - "ps"
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "bdgenomics/rhapsody:1.10.1"
  target_organization: "openpipelines-bio"
  target_registry: "ghcr.io"
  target_tag: "0.11.0"
  namespace_separator: "_"
  resolve_volume: "Automatic"
  chown: true
  setup_strategy: "ifneedbepullelsecachedbuild"
  target_image_source: "https://github.com/openpipelines-bio/openpipeline"
  setup:
  - type: "apt"
    packages:
    - "pigz"
    interactive: false
  test_setup:
  - type: "docker"
    env:
    - "GOPATH /root/go"
    - "GOBIN /root/go/bin"
    - "PATH \"${PATH}:/root/go/bin\""
  - type: "apt"
    packages:
    - "golang"
    interactive: false
  - type: "docker"
    run:
    - "go get golang.org/dl/go1.20.6 && go1.20.6 download && \\\ngit clone --branch\
      \ v2.5.0 https://github.com/shenwei356/seqkit.git && \\\ncd seqkit/seqkit/ &&\
      \ go1.20.6 build && cp seqkit /usr/bin/ && cd ../../ && rm -rf seqkit\n"
  entrypoint: []
  cmd: null
- type: "nextflow"
  id: "nextflow"
  directives:
    label:
    - "highmem"
    - "highcpu"
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      mem1gb: "memory = 1.GB"
      mem2gb: "memory = 2.GB"
      mem4gb: "memory = 4.GB"
      mem8gb: "memory = 8.GB"
      mem16gb: "memory = 16.GB"
      mem32gb: "memory = 32.GB"
      mem64gb: "memory = 64.GB"
      mem128gb: "memory = 128.GB"
      mem256gb: "memory = 256.GB"
      mem512gb: "memory = 512.GB"
      mem1tb: "memory = 1.TB"
      mem2tb: "memory = 2.TB"
      mem4tb: "memory = 4.TB"
      mem8tb: "memory = 8.TB"
      mem16tb: "memory = 16.TB"
      mem32tb: "memory = 32.TB"
      mem64tb: "memory = 64.TB"
      mem128tb: "memory = 128.TB"
      mem256tb: "memory = 256.TB"
      mem512tb: "memory = 512.TB"
      cpu1: "cpus = 1"
      cpu2: "cpus = 2"
      cpu5: "cpus = 5"
      cpu10: "cpus = 10"
      cpu20: "cpus = 20"
      cpu50: "cpus = 50"
      cpu100: "cpus = 100"
      cpu200: "cpus = 200"
      cpu500: "cpus = 500"
      cpu1000: "cpus = 1000"
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/openpipeline/openpipeline/src/reference/build_bdrhap_reference/config.vsh.yaml"
  platform: "docker"
  output: "/home/runner/work/openpipeline/openpipeline/target/docker/reference/build_bdrhap_reference"
  executable: "/home/runner/work/openpipeline/openpipeline/target/docker/reference/build_bdrhap_reference/build_bdrhap_reference"
  viash_version: "0.7.5"
  git_commit: "ebf8e7489f021faef61ec7b8c2b592ef07e033be"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
  git_tag: "0.11.2-3-gebf8e7489f"
