functionality:
  name: "bd_rhapsody_test"
  namespace: "test_workflows/ingestion/bd_rhapsody"
  description: "This component test the output of the integration test of the bd_rhapsody workflow."
  authors:
    - __merge__: /src/authors/jakub_majercik.yaml
  argument_groups:
    - name: Inputs
      arguments:
        - name: "--input"
          type: file
          required: true
          description: Path to h5mu output.
          example: foo.final.h5mu
  resources:
    - type: python_script
      path: script.py
    - path: /src/utils/setup_logger.py
platforms:
  - type: docker
    image: python:3.12-slim
    setup:
      - type: apt
        packages: 
          - procps
      - type: python
        pypi:
          - mudata
          - pytest
  - type: nextflow