functionality:
  name: "rna_singlesample"
  namespace: "multiomics"
  description: "Processing unimodal single-sample RNA transcriptomics data."
  authors:
    - __merge__: ../../../src/authors/dries_de_maeyer.yaml
      roles: [ author ]
    - __merge__: ../../../src/authors/robrecht_cannoodt.yaml
      roles: [ author, maintainer ]
    - __merge__: ../../../src/authors/dries_schaumont.yaml
      roles: [ author ]
  arguments:
    - name: "--id"
      required: true
      type: string
      description: ID of the sample.
      example: foo
    - name: "--input"
      type: file
      required: true
      description: Path to the sample.
      example: dataset.h5mu
    - name: "--output"
      type: file
      required: true
      direction: output
      description: Destination path to the output.
      example: output.h5mu
  resources:
    - type: nextflow_script
      path: main.nf
  test_resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: test_wf