# Outputs
# output: "$id.$key.output.h5mu"
# output_compression: "gzip"

# Input
id: # please fill in - example: "foo"
input: # please fill in - example: "input.h5mu"
modality: "rna"
model: # please fill in - example: "resources_test/scgpt/best_model.pt"
model_vocab: # please fill in - example: "resources_test/scgpt/vocab.json"
model_config: # please fill in - example: "args.json"
# input_layer: "foo"
# var_gene_names: "foo"
# obs_batch_label: "foo"

# scGPT integration options
binned_layer: "binned"
obsm_embeddings: "X_scGPT"
obsm_gene_tokens: "gene_id_tokens"
obsm_tokenized_values: "values_tokenized"
obsm_padding_mask: "padding_mask"
pad_token: "<pad>"
pad_value: -2
n_input_bins: 51
n_hvg: 1200
# max_seq_len: 123
dropout: 0.2
DSBN: true
batch_size: 64

# Neighbors and UMAP options
uns_neighbors: "scGPT_integration_neighbors"
obsp_neighbor_distances: "scGPT_integration_distances"
obsp_neighbor_connectivities: "scGPT_integration_connectivities"
obsm_umap: "X_scGPT_umap"

# Nextflow input-output arguments
publish_dir: # please fill in - example: "output/"
# param_list: "my_params.yaml"
