functionality:
  name: "qc"
  namespace: "qc"
  description: "A pipeline to add basic qc statistics to a MuData "
  authors:
    - __merge__: /src/authors/dries_schaumont.yaml
      roles: [ author, maintainer ]
  argument_groups:
    - name: Inputs
      arguments:
        - name: "--id"
          required: true
          type: string
          description: ID of the sample.
          example: foo
        - name: "--input"
          alternatives: [-i]
          description: Path to the sample.
          required: true
          example: input.h5mu
          type: file
        - name: "--modality"
          description: Which modality to process.
          type: string
          default: "rna"
          required: false
        - name: "--layer"
          description: "Layer to calculate qc metrics for."
          type: string
          example: "raw_counts"
          required: false
    - name: "Mitochondrial Gene Detection"
      arguments:
        - name: "--var_name_mitochondrial_genes"
          type: string
          required: false
          description: |
            In which .var slot to store a boolean array corresponding the mitochondrial genes.
        - name: "--obs_name_mitochondrial_fraction"
          type: string
          required: false
          description: |
            .Obs slot to store the fraction of reads found to be mitochondrial. Defaults to 'fraction_' suffixed by the value of --var_name_mitochondrial_genes
        - name: "--var_gene_names"
          required: false
          example: "gene_symbol"
          type: string
          description: |
            .var column name to be used to detect mitochondrial genes instead of .var_names (default if not set).
            Gene names matching with the regex value from --mitochondrial_gene_regex will be identified
            as a mitochondrial gene.
        - name: --mitochondrial_gene_regex
          type: string
          description: |
            Regex string that identifies mitochondrial genes from --var_gene_names.
            By default will detect human and mouse mitochondrial genes from a gene symbol.
          required: false
          default: "^[mM][tT]-"
    - name: "QC metrics calculation options"
      arguments:
        - name: "--var_qc_metrics"
          description: |
            Keys to select a boolean (containing only True or False) column from .var.
            For each cell, calculate the proportion of total values for genes which are labeled 'True', 
            compared to the total sum of the values for all genes. Defaults to the value from
            --var_name_mitochondrial_genes.
          type: string
          multiple: True
          multiple_sep: ','
          required: false
          example: "ercc,highly_variable"
        - name: "--top_n_vars"
          type: integer
          description: |
            Number of top vars to be used to calculate cumulative proportions.
            If not specified, proportions are not calculated. `--top_n_vars 20,50` finds
            cumulative proportion to the 20th and 50th most expressed vars.
          multiple: true
          multiple_sep: ','
          required: false
          default: [50, 100, 200, 500]
    - name: "Outputs"
      arguments:
        - name: "--output"
          type: file
          required: true
          direction: output
          description: Destination path to the output.
          example: output.h5mu
  resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: qc_entrypoint
  test_resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: test_wf
    - path: /resources_test/concat_test_data
    - path: /resources_test/pbmc_1k_protein_v3
