functionality:
  name: cellbender_remove_background
  namespace: "correction"
  description: |
    Eliminating technical artifacts from high-throughput single-cell RNA sequencing data.

    This module removes counts due to ambient RNA molecules and random barcode swapping from (raw) UMI-based scRNA-seq count matrices. 
    At the moment, only the count matrices produced by the CellRanger count pipeline is supported. Support for additional tools and protocols 
    will be added in the future. A quick start tutorial can be found here.

    Fleming et al. 2022, bioRxiv.
  argument_groups:
    - name: Inputs
      arguments:
        - name: "--input"
          alternatives: [-i]
          type: file
          description: Input file.
          direction: input
          required: true
          example: input.h5
        - name: "--modality"
          description: List of modalities to process.
          type: string
          default: "rna"
          required: false
    - name: Outputs
      arguments:
        - name: "--output"
          alternatives: [-o]
          type: file
          description: Full count matrix as an h5mu file, with background RNA removed. This file contains all the original droplet barcodes.
          direction: output
          required: true
          example: output.h5
        - name: "--layer_output"
          description: Output layer
          type: string
          default: "corrected"
        - name: "--obs_latent_rt_efficiency"
          type: string
          default: "latent_rt_efficiency"
        - name: "--obs_latent_cell_probability"
          type: string
          default: "latent_cell_probability"
        - name: "--obs_latent_scale"
          type: string
          default: "latent_scale"
        - name: "--var_ambient_expression"
          type: string
          default: "ambient_expression"
        # - name: "--obsm_latent_gene_encoding"
        #   type: string
        #   default: "latent_gene_encoding"
    - name: Arguments
      arguments:
        - name: "--model"
          type: string
          choices: [simple, ambient, swapping, full]
          description: |
            Which model is being used for count data. 'simple'
            does not model either ambient RNA or random barcode
            swapping (for debugging purposes -- not recommended).
            'ambient' assumes background RNA is incorporated into
            droplets. 'swapping' assumes background RNA comes from
            random barcode swapping. 'full' uses a combined
            ambient and swapping model. Defaults to 'full'.
        - name: "--total_droplets_included"
          type: integer
          description: |
            The number of droplets from the rank-ordered UMI plot
            that will be analyzed. The largest 'total_droplets'
            droplets will have their cell probabilities inferred
            as an output.
          example: 50000
        - name: "--epochs"
          type: integer
          description: |
            Number of epochs to train
          example: 150
        - name: "--fpr"
          type: double
          description: |
            Target false positive rate in (0, 1). A false positive
            is a true signal count that is erroneously removed.
            More background removal is accompanied by more signal
            removal at high values of FPR. You can specify
            multiple values, which will create multiple output
            files.
          example: 0.01
        - name: "--exclude_antibody_capture"
          type: boolean_true
          description: |
            Including the flag --exclude-antibody-capture will
            cause remove-background to operate on gene counts
            only, ignoring other features.
        - name: "--learning_rate"
          type: double
          description: |
            Training detail: lower learning rate for inference. A
            OneCycle learning rate schedule is used, where the
            upper learning rate is ten times this value. (For this
            value, probably do not exceed 1e-3).
          example: 0.0001
        - name: "--cuda"
          type: boolean_true
          description: |
            Including the flag --cuda will run the inference on a
            GPU.
  resources:
    - type: python_script
      path: script.py
    - path: helper.py
  test_resources:
    - type: python_script
      path: test.py
    # normally cellbender should only be run on unfiltered data, but for the purposes of the unit test the filtered data will do.
    - path: ../../../resources_test/pbmc_1k_protein_v3/pbmc_1k_protein_v3_raw_feature_bc_matrix.h5
platforms:
  - type: docker
    image: python:3.10
    setup:
      - type: python
        packages: 
          - muon
          - mudata~=0.2.0
        github:  broadinstitute/CellBender
  - type: nextflow
    directives:
      label: [highcpu, highmem, gpu]
