functionality:
  name: scarches
  namespace: "integrate"
  version: "dev"
  description: "Performs reference mapping with scArches"
  authors:
    - name: Vladimir Shitov
      email: vladimir.shitov@helmholtz-muenchen.de
      roles: [ author ]
      props: { github: vladimirshitov, orcid: "0000-0002-1960-8812" }
  argument_groups:
    - name: Inputs
      arguments:
        - name: "--input"
          alternatives: ["-i"]
          type: file
          description: Input h5mu file to use as a query
          direction: input
          required: true
        - name: "--base_model"
          choices: ["scvi", "scanvi", "totalvi"]
          alternatives: ["-m"]
          type: string
          description: Model to use for the integration
          default: "scvi"
          required: false
        - name: "--query_modality"
          type: string
          default: "rna"
          required: false
        - name: "--query_proteins_key"
          type: string
          description: Name of the modality containing proteins in the query
          required: false
        - name: "--reference"
          choices: ["HLCA"]
          alternatives: ["-r"]
          type: string
          description: Name of the reference dataset
          required: false
        - name: "--reference_modality"
          type: string
          default: "rna"
          required: false
        - name: "--reference_proteins_key"
          type: string
          description: Name of the modality containing proteins in the reference
          required: false
        - name: "--unlabeled_category"
          type: string
          description: "Value used for unlabeled cells. Used by scanvi base model"
          default: "Unknown"
          required: false
        - name: "--labels_key"
          type: string
          description: "Name of the column containing cell types. Used by scanvi base model"
          default: "leiden"
          required: false
        - name: "--predicted_labels_key"
          type: string
          description: Name of the column that will contain cell types predicted by scanvi base model
          default: "predicted_labels"
          required: false
        - name: "--input_layer"
          type: string
          required: false
          description: "Input layer to use. If None, X is used"
        - name: "--obs_batch"
          type: string
          default: "sample_id"
          required: false
          description: Column name discriminating between your batches.
        - name: "--var_input"
          type: string
          required: false
          description: ".var column containing highly variable genes. By default, do not subset genes."
    - name: Outputs
      arguments:
        - name: "--output"
          alternatives: ["-o"]
          type: file
          description: Output h5mu file.
          direction: output
          required: true
        - name: "--obsm_output"
          type: string
          default: "X_integrated_{base_model}"
          required: false
          description: "In which .obsm slot to store the resulting integrated embedding."
    - name: "Early stopping arguments"
      arguments:
        - name: "--early_stopping"
          required: false
          type: boolean
          description: "Whether to perform early stopping with respect to the validation set."
        - name: "--early_stopping_monitor"
          choices: ["elbo_validation", "reconstruction_loss_validation", "kl_local_validation"]
          default: "elbo_validation"
          type: string
          description: "Metric logged during validation set epoch."
        - name: "--early_stopping_patience"
          type: integer
          min: 1
          default: 45
          description: "Number of validation epochs with no improvement after which training will be stopped."
        - name: "--early_stopping_min_delta"
          min: 0
          type: double
          default: 0.0
          description: "Minimum change in the monitored quantity to qualify as an improvement, 
                        i.e. an absolute change of less than min_delta, will count as no improvement."
    - name: "Learning parameters"
      arguments:
        - name: "--max_epochs"
          type: integer
          description: "Number of passes through the dataset, defaults to (20000 / number of cells) * 400 or 400; whichever is smallest."
          required: true
        - name: "--reduce_lr_on_plateau"
          description: "Whether to monitor validation loss and reduce learning rate when validation set `lr_scheduler_metric` plateaus."
          type: boolean
          default: True
        - name: "--lr_factor"
          description: "Factor to reduce learning rate."
          type: double
          default: 0.6
          min: 0
        - name: "--lr_patience"
          description: "Number of epochs with no improvement after which learning rate will be reduced."
          type: double
          default: 30
          min: 0
  resources:
    - type: python_script
      path: script.py
  test_resources:
    - type: python_script
      path: test.py
    - path: ../../../resources_test/pbmc_1k_protein_v3/pbmc_1k_protein_v3_mms.h5mu
platforms:
  - type: docker
    image: python:3.8
    setup:
      - type: apt
        packages:
          - libopenblas-dev
          - liblapack-dev
          - gfortran
      - type: python
        packages:
          - mudata~=0.2.0
          - anndata~=0.8.0
          - torchmetrics~=0.6.0
          - scvi-tools
          - pandas
  - type: nextflow
    variant: vdsl3
    directives:
      label: [highmem, highcpu]