# Outputs
# output: "$id.$key.output.h5mu"
output_compression: "gzip"
obs_predicted_cell_class: "predicted_cell_class"
obs_predicted_cell_label: "predicted_cell_label"

# Arguments
pad_token: "<pad>"
pad_value: -2
n_input_bins: 51
batch_size: 64
dsbn: true
# seed: 123

# Model input
model: # please fill in - example: "best_model.pt"
model_config: # please fill in - example: "args.json"
model_vocab: # please fill in - example: "vocab.json"
finetuned_checkpoints_key: "model_state_dict"
label_mapper_key: "id_to_class"

# Query input
input: # please fill in - example: "resources_test/scgpt/test_resources/Kim2020_Lung_preprocessed.h5mu"
modality: "rna"
# obs_batch_label: "foo"
obsm_gene_tokens: "gene_id_tokens"
obsm_tokenized_values: "values_tokenized"

# Nextflow input-output arguments
publish_dir: # please fill in - example: "output/"
# param_list: "my_params.yaml"
