functionality:
  name: harmonypy
  namespace: "integrate"
  version: "dev"
  description: "Performs Harmony integration based as described in https://github.com/immunogenomics/harmony.
                Based on an implementation in python from https://github.com/slowkow/harmonypy"
  authors:
    - name: Dries Schaumont
      email: dries.schaumont@its.jnj.com
      roles: [ maintainer ]
  arguments:
    - name: "--input"
      alternatives: ["-i"]
      type: file
      description: Input h5mu file
      direction: input
      required: true
    - name: "--output"
      alternatives: ["-o"]
      type: file
      description: Output h5mu file.
      direction: output
      required: true
    - name: "--modality"
      type: string
      multiple: true
      default: "rna"
      required: false
    - name: "--pca_key"
      type: string
      default: "X_pca"
      required: false
      description: The field in the obs object that defined the input PCA embedding.
    - name: "--output_key_suffix"
      type: string
      default: "harmonypy"
      required: false
      description: "Suffix for the key in .obsm where the results will be stored.
                    The resulting key will be a comination of the pca key and the output key suffix."
    - name: "--theta"
      description: Theta value to perform correction on.
      type: double
      default: 0
      multiple: true
    - name: "--sample_key"
      type: string
      description: The field in the obs object that defines batches to perform correction to.
      default: "batch"
      multiple: true
  resources:
    - type: python_script
      path: ./script.py
  test_resources:
    - type: python_script
      path: test.py
    - path: ../../../resources_test/pbmc_1k_protein_v3/pbmc_1k_protein_v3_mms.h5mu
platforms:
  - type: docker
    image: python:3.10
    setup:
      - type: python
        packages:
          - mudata~=0.2.0
          - anndata~=0.8.0
          - harmonypy~=0.0.6
          - scanpy
  - type: nextflow
    variant: vdsl3
    directives:
      label: highmem