functionality:
  name: scanvi
  namespace: annotate
  description: Semi-supervised model for single-cell transcriptomics data. A scVI extension that can leverage the cell type knowledge for a subset of the cells present in the data sets to infer the states of the rest of the cells.
  authors:
    - __merge__: /src/authors/jakub_majercik.yaml
      roles: [ author ]

  argument_groups:
    - name: Inputs
      description: Arguments related to the input (aka query) dataset.
      arguments:
        - name: "--input"
          alternatives: [-i]
          type: file
          description: Input h5mu file.
          direction: input
          required: true
          example: input.h5mu
        - name: "--modality"
          description: Which modality to process.
          type: string
          default: "rna"
          required: false

    - name: Reference
      description: Arguments related to the reference dataset.
      arguments:
        - name: "--reference"
          type: file
          description: Reference h5ad file.
          direction: input
          required: true
          example: reference.h5ad
        - name: "--scvi_reference_model"
          type: file
          description: "Pretrained scvi reference model"
          example: scvi_model.pt
          direction: input
          required: true
        - name: "--reference_obs_label"
          type: string
          description: Key in obs field of reference AnnData with cell-type information.
          default: "cell_ontology_class"
          required: false
        - name: "--reference_obs_batch"
          type: string
          description: Key in obs field of reference AnnData with batch information.
          required: false

  #  - name: "SCVI options"
  #     arguments:
  #       - name: --n_hidden_nodes
  #         type: integer
  #         required: false
  #         default: 128 # this is not the default in SCVI
  #         description: "Number of nodes per hidden layer."
  #       - name: --n_dimensions_latent_space
  #         type: integer
  #         required: false
  #         default: 30 # this is not the default in SCVI
  #         description: "Dimensionality of the latent space."
  #       - name: "--n_hidden_layers"
  #         required: false
  #         type: integer
  #         default: 2 # this is not the default in SCVI
  #         description:  Number of hidden layers used for encoder and decoder neural-networks.
  #       - name: --dropout_rate
  #         type: double
  #         required: false
  #         default: 0.1 
  #         description: "Dropout rate for the neural networks."
  #       - name: "--dispersion"
  #         type: string
  #         required: false
  #         choices: ["gene", "gene-batch", "gene-label", "gene-cell"]
  #         default: "gene"
  #         description: |
  #           Set the behavior for the dispersion for negative binomial distributions:
  #           - gene: dispersion parameter of negative binomial is constant per gene across cells
  #           - gene-batch: dispersion can differ between different batches
  #           - gene-label: dispersion can differ between different labels
  #           - gene-cell:  dispersion can differ for every gene in every cell
  #       - name: "--gene_likelihood"
  #         type: string
  #         default: "nb" # This is not the default in SCVI
  #         choices: ["nb", "zinb", "poisson"]
  #         description: |
  #           Model used to generate the expression data from a count-based likelihood distribution.
  #           - nb: Negative binomial distribution
  #           - zinb: Zero-inflated negative binomial distribution
  #           - poisson: Poisson distribution
  #   - name: "Variational auto-encoder model options"
  #     arguments:
  #       - name: "--use_layer_normalization"
  #         description: |
  #           Neural networks for which to enable layer normalization. 
  #         type: string
  #         choices: ["encoder", "decoder", "none", "both"]
  #         default: "both" # This is not the default in SCVI
  #       - name: "--use_batch_normalization"
  #         description: |
  #           Neural networks for which to enable batch normalization. 
  #         type: string
  #         choices: ["encoder", "decoder", "none", "both"]
  #         default: "none" # This is not the default in SCVI
  #       - name: "--encode_covariates"
  #         type: boolean_false # This is not the default in SCVI
  #         description: "Whether to concatenate covariates to expression in encoder"
  #       - name: "--deeply_inject_covariates"
  #         type: boolean_true
  #         description: |
  #           Whether to concatenate covariates into output of hidden layers in encoder/decoder. 
  #           This option only applies when n_layers > 1. The covariates are concatenated to
  #           the input of subsequent hidden layers.
  #       - name: "--use_observed_lib_size"
  #         type: boolean_true # This is not the default in SCVI
  #         description: |
  #           Use observed library size for RNA as scaling factor in mean of conditional distribution.
  #   - name: "Early stopping arguments"
  #     arguments:
  #       - name: "--early_stopping"
  #         required: false
  #         type: boolean
  #         description: "Whether to perform early stopping with respect to the validation set."
  #       - name: "--early_stopping_monitor"
  #         choices: ["elbo_validation", "reconstruction_loss_validation", "kl_local_validation"]
  #         default: "elbo_validation"
  #         type: string
  #         description: "Metric logged during validation set epoch."
  #       - name: "--early_stopping_patience"
  #         type: integer
  #         min: 1
  #         default: 45
  #         description: "Number of validation epochs with no improvement after which training will be stopped."
  #       - name: "--early_stopping_min_delta"
  #         min: 0
  #         type: double
  #         default: 0.0
  #         description: "Minimum change in the monitored quantity to qualify as an improvement, 
  #                       i.e. an absolute change of less than min_delta, will count as no improvement."
  #   - name: "Learning parameters"
  #     arguments:
  #       - name: "--max_epochs"
  #         type: integer
  #         description: "Number of passes through the dataset, defaults to (20000 / number of cells) * 400 or 400; whichever is smallest."
  #         required: false
  #       - name: "--reduce_lr_on_plateau"
  #         description: "Whether to monitor validation loss and reduce learning rate when validation set `lr_scheduler_metric` plateaus."
  #         type: boolean
  #         default: True
  #       - name: "--lr_factor"
  #         description: "Factor to reduce learning rate."
  #         type: double
  #         default: 0.6
  #         min: 0
  #       - name: "--lr_patience"
  #         description: "Number of epochs with no improvement after which learning rate will be reduced."
  #         type: double
  #         default: 30
  #         min: 0

    - name: Outputs
      description: Arguments related to the output.
      arguments:
        - name: "--output"
          type: file
          description: Output h5mu file.
          direction: output
          required: true
          example: output.h5mu
        - name: "--output_compression"
          type: string
          choices: ["gzip", "lzf"]
          required: false
          example: "gzip"

  resources:
    - type: python_script
      path: script.py
    - path: /src/utils/setup_logger.py

  test_resources:
    - type: python_script
      path: test.py
    - path: /resources_test/annotation_test_data/
    - path: /resources_test/pbmc_1k_protein_v3/

platforms:
  - type: docker
    image: python:3.10-slim
    setup:
      - type: apt
        packages:
          - libhdf5-dev
          - procps
      - type: python
        __merge__: [ /src/base/requirements/scanpy.yaml, .]
      - type: python
        packages:
          - scvi-tools==1.1.5
      - type: python
        __merge__: [ /src/base/requirements/anndata_mudata.yaml, .]
    __merge__: [ /src/base/requirements/python_test_setup.yaml, .]
  - type: nextflow
    