functionality:
  name: "from_velocyto_to_h5mu"
  namespace: "convert"
  version: "dev"
  description: |
    Convert a velocyto .loom file to h5mu
  authors:
    - __inherits__: ../../authors/dries_schaumont.yaml
      roles: [ maintainer ]
  arguments:
    - name: "--input"
      alternatives: ["-i"]
      type: file
      description: Input velocyto .loom file.
      example: input.loom
      direction: input
      required: true
    - name: "--output"
      alternatives: ["-o"]
      type: file
      description: Output h5mu file.
      example: output.h5mu
      direction: output
  resources:
    - type: python_script
      path: script.py
  test_resources:
    - type: python_script
      path: test.py
    - path: ../../../resources_test/rna_velocity/velocyto_processed/cellranger_tiny.loom
platforms:
  - type: docker
    image: python:3.8-slim
    setup:
      - type: python
        packages: [ muon, anndata<0.8, scanpy]
  - type: nextflow
  - type: native