functionality:
  name: "annotation_service"
  namespace: "workflows/annotation"
  version: "annotation-workflow_build"
  authors:
  - name: "Dorien Roosen"
    roles:
    - "author"
    - "maintainer"
    info:
      role: "Contributor"
      links:
        email: "dorien@data-intuitive.com"
        github: "dorien-er"
        linkedin: "dorien-roosen"
      organizations:
      - name: "Data Intuitive"
        href: "https://www.data-intuitive.com"
        role: "Data Scientist"
  argument_groups:
  - name: "Inputs"
    arguments:
    - type: "string"
      name: "--id"
      description: "ID of the sample."
      info: null
      example:
      - "foo"
      required: true
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "file"
      name: "--input"
      description: "Input query dataset(s) to be annotated"
      info: null
      example:
      - "input.h5mu"
      must_exist: true
      create_parent: true
      required: true
      direction: "input"
      multiple: true
      multiple_sep: ";"
      dest: "par"
    - type: "string"
      name: "--annotation_methods"
      info: null
      example:
      - "harmony_knn"
      required: true
      choices:
      - "harmony_knn"
      direction: "input"
      multiple: true
      multiple_sep: ";"
      dest: "par"
    - type: "string"
      name: "--reference_url"
      description: "The reference dataset to be used as a reference mapper and to\
        \ train annotation algorithms on.\n"
      info: null
      example:
      - "https://zenodo.org/records/7587774/files/TS_Lung_filtered.h5ad"
      required: true
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--query_rna_layer"
      description: "Input layer for the gene expression modality of the query datasets.\
        \ If not specified, .X is used."
      info: null
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--obs_reference_batch"
      description: "The .obs column of the reference dataset containing the batch\
        \ information.\n"
      info: null
      required: true
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--reference_rna_layer"
      description: "Input layer for the gene expression modality of the reference\
        \ dataset. If not specified, .X is used."
      info: null
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--obs_reference_targets"
      description: "The `.obs` key(s) of the target labels to tranfer."
      info: null
      example:
      - "ann_level_1"
      - "ann_level_2"
      - "ann_level_3"
      - "ann_level_4"
      - "ann_level_5"
      - "ann_finest_level"
      required: true
      direction: "input"
      multiple: true
      multiple_sep: ";"
      dest: "par"
  - name: "Pre-processing options: RNA filtering"
    arguments:
    - type: "integer"
      name: "--rna_min_counts"
      description: "Minimum number of counts captured per cell."
      info: null
      example:
      - 200
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--rna_max_counts"
      description: "Maximum number of counts captured per cell."
      info: null
      example:
      - 5000000
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--rna_min_genes_per_cell"
      description: "Minimum of non-zero values per cell."
      info: null
      example:
      - 200
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--rna_max_genes_per_cell"
      description: "Maximum of non-zero values per cell."
      info: null
      example:
      - 1500000
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--rna_min_cells_per_gene"
      description: "Minimum of non-zero values per gene."
      info: null
      example:
      - 3
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "double"
      name: "--rna_min_fraction_mito"
      description: "Minimum fraction of UMIs that are mitochondrial."
      info: null
      example:
      - 0.0
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "double"
      name: "--rna_max_fraction_mito"
      description: "Maximum fraction of UMIs that are mitochondrial."
      info: null
      example:
      - 0.2
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  - name: "Pre-processing options: Highly variable features detection"
    arguments:
    - type: "string"
      name: "--highly_variable_features_var_output"
      alternatives:
      - "--filter_with_hvg_var_output"
      description: "In which .var slot to store a boolean array corresponding to the\
        \ highly variable genes."
      info: null
      default:
      - "filter_with_hvg"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--highly_variable_features_obs_batch_key"
      alternatives:
      - "--filter_with_hvg_obs_batch_key"
      description: "If specified, highly-variable genes are selected within each batch\
        \ separately and merged. This simple \nprocess avoids the selection of batch-specific\
        \ genes and acts as a lightweight batch correction method.\n"
      info: null
      default:
      - "sample_id"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  - name: "Pre-processing options: Mitochondrial Gene Detection"
    arguments:
    - type: "string"
      name: "--var_name_mitochondrial_genes"
      description: "In which .var slot to store a boolean array corresponding the\
        \ mitochondrial genes.\n"
      info: null
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--obs_name_mitochondrial_fraction"
      description: "When specified, write the fraction of counts originating from\
        \ mitochondrial genes \n(based on --mitochondrial_gene_regex) to an .obs column\
        \ with the specified name.\nRequires --var_name_mitochondrial_genes.\n"
      info: null
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--var_gene_names"
      description: ".var column name to be used to detect mitochondrial genes instead\
        \ of .var_names (default if not set).\nGene names matching with the regex\
        \ value from --mitochondrial_gene_regex will be identified\nas a mitochondrial\
        \ gene.\n"
      info: null
      example:
      - "gene_symbol"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "string"
      name: "--mitochondrial_gene_regex"
      description: "Regex string that identifies mitochondrial genes from --var_gene_names.\n\
        By default will detect human and mouse mitochondrial genes from a gene symbol.\n"
      info: null
      default:
      - "^[mM][tT]-"
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  - name: "Pre-processing options: QC metrics calculation options"
    arguments:
    - type: "string"
      name: "--var_qc_metrics"
      description: "Keys to select a boolean (containing only True or False) column\
        \ from .var.\nFor each cell, calculate the proportion of total values for\
        \ genes which are labeled 'True', \ncompared to the total sum of the values\
        \ for all genes. Defaults to the combined values specified for\n--var_name_mitochondrial_genes\
        \ and --highly_variable_features_var_output.\n"
      info: null
      example:
      - "ercc,highly_variable"
      required: false
      direction: "input"
      multiple: true
      multiple_sep: ";"
      dest: "par"
    - type: "integer"
      name: "--top_n_vars"
      description: "Number of top vars to be used to calculate cumulative proportions.\n\
        If not specified, proportions are not calculated. `--top_n_vars 20,50` finds\n\
        cumulative proportion to the 20th and 50th most expressed vars.\n"
      info: null
      default:
      - 50
      - 100
      - 200
      - 500
      required: false
      direction: "input"
      multiple: true
      multiple_sep: ";"
      dest: "par"
  - name: "Harmony integration options"
    arguments:
    - type: "double"
      name: "--theta"
      description: "Diversity clustering penalty parameter. Specify for each variable\
        \ in group.by.vars. \ntheta=0 does not encourage any diversity. Larger values\
        \ of theta\nresult in more diverse clusters.\"\n"
      info: null
      default:
      - 2.0
      required: false
      direction: "input"
      multiple: true
      multiple_sep: ";"
      dest: "par"
  - name: "KNN label transfer options"
    arguments:
    - type: "string"
      name: "--weights"
      description: "Weight function used in prediction. Possible values are:\n‘uniform’\
        \ (all points in each neighborhood are weighted equally) or \n'distance' (weight\
        \ points by the inverse of their distance)\n"
      info: null
      default:
      - "uniform"
      required: false
      choices:
      - "uniform"
      - "distance"
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
    - type: "integer"
      name: "--n_neighbors"
      description: "The number of neighbors to use in k-neighbor graph structure used\
        \ for fast approximate nearest neighbor search with PyNNDescent. \nLarger\
        \ values will result in more accurate search results at the cost of computation\
        \ time.\n"
      info: null
      default:
      - 15
      required: false
      direction: "input"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  - name: "Outputs"
    arguments:
    - type: "file"
      name: "--output"
      description: "The output file.\n"
      info: null
      example:
      - "output.h5mu"
      must_exist: true
      create_parent: true
      required: true
      direction: "output"
      multiple: false
      multiple_sep: ":"
      dest: "par"
  resources:
  - type: "nextflow_script"
    path: "main.nf"
    is_executable: true
    entrypoint: "run_wf"
  - type: "file"
    path: "./src/workflows/utils/labels.config"
    dest: "nextflow_labels.config"
  description: "A pipeline to process and annotate gene expression data."
  test_resources:
  - type: "file"
    path: "src/base/openpipelinetestutils"
    dest: "openpipelinetestutils"
  info: null
  status: "enabled"
  requirements:
    commands:
    - "ps"
  dependencies:
  - name: "download/download_file"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/openpipeline/openpipeline/src/download/download_file/config.vsh.yaml"
    configInfo:
      functionalityName: "download_file"
      git_tag: "0.2.0-1623-g939b74370c"
      git_remote: "https://github.com/openpipelines-bio/openpipeline"
      viash_version: "0.8.5"
      config: "/home/runner/work/openpipeline/openpipeline/src/download/download_file/config.vsh.yaml"
      functionalityNamespace: "download"
      output: ""
      platform: ""
      git_commit: "939b74370c3224d813f62184005915b5e0c739c9"
      executable: "/nextflow/download/download_file/main.nf"
    writtenPath: "/home/runner/work/openpipeline/openpipeline/target/nextflow/download/download_file"
  - name: "convert/from_h5ad_to_h5mu"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/openpipeline/openpipeline/src/convert/from_h5ad_to_h5mu/config.vsh.yaml"
    configInfo:
      functionalityName: "from_h5ad_to_h5mu"
      git_tag: "0.2.0-1623-g939b74370c"
      git_remote: "https://github.com/openpipelines-bio/openpipeline"
      viash_version: "0.8.5"
      config: "/home/runner/work/openpipeline/openpipeline/src/convert/from_h5ad_to_h5mu/config.vsh.yaml"
      functionalityNamespace: "convert"
      output: ""
      platform: ""
      git_commit: "939b74370c3224d813f62184005915b5e0c739c9"
      executable: "/nextflow/convert/from_h5ad_to_h5mu/main.nf"
    writtenPath: "/home/runner/work/openpipeline/openpipeline/target/nextflow/convert/from_h5ad_to_h5mu"
  - name: "dataflow/split_samples"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/openpipeline/openpipeline/src/dataflow/split_samples/config.vsh.yaml"
    configInfo:
      functionalityName: "split_samples"
      git_tag: "0.2.0-1623-g939b74370c"
      git_remote: "https://github.com/openpipelines-bio/openpipeline"
      viash_version: "0.8.5"
      config: "/home/runner/work/openpipeline/openpipeline/src/dataflow/split_samples/config.vsh.yaml"
      functionalityNamespace: "dataflow"
      output: ""
      platform: ""
      git_commit: "939b74370c3224d813f62184005915b5e0c739c9"
      executable: "/nextflow/dataflow/split_samples/main.nf"
    writtenPath: "/home/runner/work/openpipeline/openpipeline/target/nextflow/dataflow/split_samples"
  - name: "workflows/multiomics/process_samples"
    alias: "process_samples_workflow"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/openpipeline/openpipeline/src/workflows/multiomics/process_samples/config.vsh.yaml"
    configInfo:
      functionalityName: "process_samples"
      git_tag: "0.2.0-1623-g939b74370c"
      git_remote: "https://github.com/openpipelines-bio/openpipeline"
      viash_version: "0.8.5"
      config: "/home/runner/work/openpipeline/openpipeline/src/workflows/multiomics/process_samples/config.vsh.yaml"
      functionalityNamespace: "workflows/multiomics"
      output: ""
      platform: ""
      git_commit: "939b74370c3224d813f62184005915b5e0c739c9"
      executable: "/nextflow/workflows/multiomics/process_samples/main.nf"
    writtenPath: "/home/runner/work/openpipeline/openpipeline/target/nextflow/workflows/multiomics/process_samples"
  - name: "workflows/annotation/harmony_knn"
    alias: "harmony_knn_workflow"
    repository:
      type: "local"
      localPath: ""
    foundConfigPath: "/home/runner/work/openpipeline/openpipeline/src/workflows/annotation/harmony_knn/config.vsh.yaml"
    configInfo:
      functionalityName: "harmony_knn"
      git_tag: "0.2.0-1623-g939b74370c"
      git_remote: "https://github.com/openpipelines-bio/openpipeline"
      viash_version: "0.8.5"
      config: "/home/runner/work/openpipeline/openpipeline/src/workflows/annotation/harmony_knn/config.vsh.yaml"
      functionalityNamespace: "workflows/annotation"
      output: ""
      platform: ""
      git_commit: "939b74370c3224d813f62184005915b5e0c739c9"
      executable: "/nextflow/workflows/annotation/harmony_knn/main.nf"
    writtenPath: "/home/runner/work/openpipeline/openpipeline/target/nextflow/workflows/annotation/harmony_knn"
  set_wd_to_resources_dir: false
platforms:
- type: "nextflow"
  id: "nextflow"
  directives:
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      mem1gb: "memory = 1.GB"
      mem2gb: "memory = 2.GB"
      mem4gb: "memory = 4.GB"
      mem8gb: "memory = 8.GB"
      mem16gb: "memory = 16.GB"
      mem32gb: "memory = 32.GB"
      mem64gb: "memory = 64.GB"
      mem128gb: "memory = 128.GB"
      mem256gb: "memory = 256.GB"
      mem512gb: "memory = 512.GB"
      mem1tb: "memory = 1.TB"
      mem2tb: "memory = 2.TB"
      mem4tb: "memory = 4.TB"
      mem8tb: "memory = 8.TB"
      mem16tb: "memory = 16.TB"
      mem32tb: "memory = 32.TB"
      mem64tb: "memory = 64.TB"
      mem128tb: "memory = 128.TB"
      mem256tb: "memory = 256.TB"
      mem512tb: "memory = 512.TB"
      cpu1: "cpus = 1"
      cpu2: "cpus = 2"
      cpu5: "cpus = 5"
      cpu10: "cpus = 10"
      cpu20: "cpus = 20"
      cpu50: "cpus = 50"
      cpu100: "cpus = 100"
      cpu200: "cpus = 200"
      cpu500: "cpus = 500"
      cpu1000: "cpus = 1000"
    script:
    - "includeConfig(\"nextflow_labels.config\")"
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/openpipeline/openpipeline/src/workflows/annotation/annotation_service/config.vsh.yaml"
  platform: "nextflow"
  output: "/home/runner/work/openpipeline/openpipeline/target/nextflow/workflows/annotation/annotation_service"
  executable: "/home/runner/work/openpipeline/openpipeline/target/nextflow/workflows/annotation/annotation_service/main.nf"
  viash_version: "0.8.5"
  git_commit: "939b74370c3224d813f62184005915b5e0c739c9"
  git_remote: "https://github.com/openpipelines-bio/openpipeline"
  git_tag: "0.2.0-1623-g939b74370c"
