name: viash test CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  # phase 1
  list_components:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Fetch viash
      run: |
        bin/init
        bin/viash -h
    - id: set-matrix
      uses: sergeysova/jq-action@v2
      run: |
        echo "::set-output name=matrix::$(bin/viash ns list --format json | jq '[ .[] | { name: .functionality.name, path: .info.config } ]')"

  # phase 2
  viash-test:
    runs-on: ${{ matrix.config.os }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    strategy:
      fail-fast: false
      matrix:
        config:
        - {name: 'main', os: ubuntu-latest }

    steps:
    - uses: actions/checkout@v2

    - name: Fetch viash
      run: |
        bin/init
        bin/viash -h

    - name: Sync test resources
      run: |
        bin/viash_build -q sync_test_resources
        target/docker/download/sync_test_resources/sync_test_resources --quiet --exclude bd_rhapsody_wta_test/*

    - name: Run build
      run: |
        bin/viash_build 

    - name: Run tests
      run: |
        # run tests
        bin/viash test ${{ matrix.config.path }}

