name: viash test CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  # phase 1
  list_components:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
    - uses: actions/checkout@v2
    - name: Fetch viash
      run: |
        bin/init
        bin/viash -h
    - id: set_matrix
      run: |
        echo "::set-output name=matrix::$( bin/viash ns list -p docker --format json | jq -c '[ .[] | .info.config ]' )"
    outputs:
        matrix: ${{ steps.set_matrix.outputs.matrix }}

  # phase 2
  viash_test:
    needs: list_components

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    strategy:
      fail-fast: false
      matrix:
        component_path: ${{ fromJson(needs.list_components.outputs.matrix) }}

    steps:
    - uses: actions/checkout@v2

    - name: Fetch viash
      run: |
        bin/init
        bin/viash -h

    - name: Sync test resources
      run: |
        bin/viash_build -q sync_test_resources
        target/docker/download/sync_test_resources/sync_test_resources --quiet --exclude bd_rhapsody_wta_test/*

    - name: Run test
      run: |
        bin/viash test -p docker ${{ matrix.component_path }}

