functionality:
  name: "cellranger_demux"
  namespace: "ingestion"
  description: "Cell Ranger demux pipeline."
  authors:
    - name: Angela Pisco
      roles: [ author ]
      props: { github: aopisco, orcid: "0000-0003-0142-2355" }
    - name: Samuel D'Souza
      roles: [ author ]
      props: { github: srdsam }
    - name: Robrecht Cannoodt
      email: rcannood@gmail.com
      roles: [ author, maintainer ]
      props: { github: rcannood, orcid: "0000-0003-3641-729X" }
  arguments:
    - name: "--id"
      required: true
      type: string
      description: ID of the sample.
      example: foo
    - name: "--input"
      required: true
      type: file
      description: A BCL directory.
      example: /path/to/bcl
    - name: "--sample_sheet"
      required: true
      type: file
      description: The sample sheet for the samples to be demultiplexed.
      example: sample_sheet.csv
    - type: integer
      name: --cores
      description:  Set max cores the pipeline may request at one time.
      example: 2
    - type: integer
      name: --memory
      description: Set max GB the pipeline may request at one time.
      example: 10
  resources:
    - type: nextflow_script
      path: main.nf
  test_resources:
    - type: nextflow_script
      path: main.nf
      entrypoint: test_wf
platforms:
  - type: native